### ISSUE TITLE
How to bypass or disable authenticator for Google account

### ISSUE THREAD

**Issue by stijnkarel** [simonrob/email-oauth2-proxy#105]
I know the password of my gmail address. No recovery code and recovery email address and recovery phone number are not registered. It was only protected by authenticator and password. My phone malfunctioned, I had to do a soft reset. I didn't have an Authenticator backup. So I can't login to my gmail account. My important documents were in my drive account. I need access. I wonder if there is a web app so I can bypass or disable gmail authenticator and only login with password? How can I recover? Can this be done with the app?

**Comment by simonrob** [comment]
No, I'm afraid not - you need to be able to log in to your account to use this proxy.
