### ISSUE TITLE
Grant Admin consent

### ISSUE THREAD

**Issue by D4rki91** [simonrob/email-oauth2-proxy#107]
Hey, maybe someone can help me with this issue.

![image](https://user-images.githubusercontent.com/107997738/206426124-6ec725b9-1565-49f0-a394-2d704670e6f2.png)

Proxy is working fine, Microsoft Graph permissions and everything else is fine.
But there are unfortunately some restrictions in the companies Azure AD so the ability for regular users to consent to applications is disabled.

![image](https://user-images.githubusercontent.com/107997738/206442174-f3098884-62e2-4d83-a292-5257786ca38d.png)
![image](https://user-images.githubusercontent.com/107997738/206442241-dbdbb900-7129-43c8-bf27-6019e24997ab.png)

So I think the problem here is when the admin account is approving it on behalf the proxy will actually write the information for the wrong user account (Admin) inside his config file?

Is there any kind of workaround or is it just neccessary to allow all users to consent applications.
Adding the User as owner did also not help.

Thanks!

**Comment by D4rki91** [comment]
I also found out that the Microsoft Graph API permissions dont got their Admin consent from a Global tennant Admin, maybe this can be an issue too? The administrator told me that his account has all the required permissions but Im not sure about that ...

**Comment by michaelstepner** [comment]
@D4rki91 I think your issue is with the [OAuth 2.0 client credentials](https://github.com/simonrob/email-oauth2-proxy#oauth-20-client-credentials) not being authorized by your O365 admin.

**Comment by D4rki91** [comment]
Hey, thanks for your help.

I told the Administrator to delete the Enterprise App registration and re-register it and it worked. Not sure what happened there, maybe he misconfigured something in first place.
