### ISSUE TITLE
Azure App SMTP

### ISSUE THREAD

**Issue by DJR-FP** [simonrob/email-oauth2-proxy#111]
I'm looking to setup smtp to OAuth but am struggling with the  setup of the Microsoft identity application. Do you have any example config ?

thanks

**Comment by simonrob** [comment]
The instructions for setting up an OAuth client are not something I have time to maintain because the various providers change their interfaces so often, but there are plenty of tutorials elsewhere ([here](https://github.com/tarickb/sasl-xoauth2#outlookoffice-365-configuration), for example).

**Comment by DJR-FP** [comment]
thanks for the info. I'll happily leave an example of my azure config should I get it up and running. Thanks for the great work !!
