### ISSUE TITLE
Caught asyncore exception

### ISSUE THREAD

**Issue by RoyDonk** [simonrob/email-oauth2-proxy#112]
Proxy stopped working getting error message in log

"Caught asyncore exception in main loop; attempting to continue: OSError(10038, 'An operation was attempted on something that is not a socket', None, 10038, None)"

Running on Windows Server 2019 Standard version 1809. 
Python v3.11

Quiting the proxy and restarting it seemed to fix it, but just curious if this is just a random error or if there is something that we can adjust to avoid this in the future.
Thanks,

**Comment by simonrob** [comment]
Was this after a long time running, or just after starting? Sometimes, for reasons that are not quite clear, sockets on Windows fail to actually open.

The proxy should wait a short while (one second × the number of times the error has occurred) and then try again. Did you let it do this?

**Comment by RoyDonk** [comment]
It was running for about 3 full days before the error started.

The error started around 3am and kept going until around 11am until I restarted the proxy. According the logs the error occurred 6 times every second during that time period.

**Comment by simonrob** [comment]
Thanks for following up. Strange that it occurred with such frequency – the only time that this should happen is on a specific error (`BADF` / error number 8) that can occur when restarting the proxy (see [here](https://github.com/simonrob/email-oauth2-proxy/blob/db5889bca1659e9523b521581aca58da2fe2e78e/emailproxy.py#L2573)).

Regardless, unless you're able to pinpoint a way to reproduce this, I'm afraid there's not much that can be done. I don't use Windows myself, so haven't encountered it except for once (unreproducibly) in testing.

**Comment by RoyDonk** [comment]
Alright, thanks for the response. I have it running on multiple windows servers without any issues. If it happens again and I can find a trigger I'll reopen the issue. Thanks

**Comment by RoyDonk** [comment]
I think I know what is triggering the errors. I have the proxy installed at about 10 remote offices that can only get internet through spotty cell connection. The exception seems to occur when the office has been offline for a few hours, but then keeps happening even after connection is reestablished.

**Comment by simonrob** [comment]
Thanks for following up here – next time I have access to a Windows environment to simulate this I'll take a look.

In the meantime, if you find a way to reliably replicate this (perhaps start the proxy then disconnect the network?) then please do let me know. Incidentally, on macOS the proxy [proactively shuts down sockets when it detects network loss](https://github.com/simonrob/email-oauth2-proxy/blob/db5889bca1659e9523b521581aca58da2fe2e78e/emailproxy.py#L2000) precisely to combat this sort of issue, so hopefully there is a similar approach that can be used on Windows.

**Comment by RoyDonk** [comment]
This has not been happening anymore, even when the servers have been disconnected for awhile. I'm going to close the issue
