### ISSUE TITLE
https_proxy

### ISSUE THREAD

**Issue by sebaswatts** [simonrob/email-oauth2-proxy#113]
Can you add an https_proxy configuration option?  In Linux environments, python doesn't take the global environment variable http_proxy nor https_proxy.   Thanks.

**Comment by simonrob** [comment]
I'm not really sure what you're requesting to add here, or how it would be achieved, but from a quick search it seems like this is [already possible](https://stackoverflow.com/a/31641300) on Linux.

**Comment by sebaswatts** [comment]
Hi!

According to documentation 
https://docs.python.org/3.5/howto/urllib2.html#proxies I can't renew 
tokens through https, I had a highly restrictive connectivity environment.

I'm requesting a way to migrate urllib to requests, or extend urllib2 
according to documentation.

**Comment by simonrob** [comment]
That documentation link is for a very old version of Python, and I can't replicate your issue myself. Setting an environment variable `https_proxy` correctly directs traffic through the given channel. For example, try the following one-liner from a terminal:

```
https_proxy=localhost python -c "import urllib.request; print(urllib.request.urlopen(urllib.request.Request('https://example.com')).read())"
```

Note that the scheme of the environment variable must match, and you seem to be implying that your token renewal URL is not `https`; but `http`; in that case you would set an environment variable `http_proxy` instead.

**Comment by sebaswatts** [comment]
you're right, the daemon wasn't see the http_proxy values.

I solved wraping the python in a shell script that forces http_proxy and 
https_proxy environment variables.

Thank you so much for your time and effort.

**Comment by simonrob** [comment]
Great – glad you were able to resolve this.
