### ISSUE TITLE
New sections disappear from configuration after service restart

### ISSUE THREAD

**Issue by warlin1** [simonrob/email-oauth2-proxy#115]
Good afternoon.
I have a question about adding new accounts in emailproxy.config
The problem is that if I add a new section when emailproxy is running then without restarting this setting will not apply and I get the error "Proxy config file entry missing for account", at the same time if I restart the proxy "systemctl restart emailproxy" then the section I added disappears from the configuration file . It seems to be a defect.
So at the moment the only option is to stop the proxy, make changes to emailproxy.config and start again.
How relevant do you think it is for the settings to be applied on the fly.
Thanks.

**Comment by simonrob** [comment]
Thanks for opening the discusion about this.

The proxy was initially designed as a GUI-only application, and if you run it in that mode you'll see that there's a menu option to reload the configuration file. If you make configuration changes and reload this way then your edits will not be overwritten (except in the unlikely event that an OAuth 2.0 token refresh happens while you are editing).

The proxy has subsequently been extended to support non-GUI operation, and in that mode you can use a `SIGHUP` signal to trigger reloading the configuration (e.g., `pkill -SIGHUP -f emailproxy.py`). However, this signal is not available on Windows, so in non-GUI mode there it is necessary to stop and start the proxy as you are doing.

The reason your changes are being overwritten is that when the proxy exits it automatically saves the most recent configuration state. This used to be essential, but the way configuration is managed has evolved over time, and I am tempted to remove [this behaviour](https://github.com/simonrob/email-oauth2-proxy/blob/db5889bca1659e9523b521581aca58da2fe2e78e/emailproxy.py#L2583), at least in non-GUI mode.

**Comment by warlin1** [comment]
Greetings Simon.
Thank you for your detailed reply. 
I am using the application in headless mode on a Linux server, so SIGHUP is fine for me.
I have an idea for improvement. 
It seems storing tokens in a config file becomes problematic, what if storing tokens in a separate file or SQLite?
This would not require overwriting the configuration file when updating the token. In this case, the application will open the configuration file for reading only and we will be able to freely reload the configuration on "Proxy config file entry missing for account" event and eliminate the need to restart/stop the application.

**Comment by simonrob** [comment]
Great - `SIGHUP` should solve your issue here then.

The suggestion to separate cached tokens from configuration is something that has been discussed before, but there are benefits to having everything in one place, particularly in a server setting (for example, copying a fully-authenticated configuration from one setup to another). It's also normally the case that the configuration file is rarely updated, so for now I think the extra complexity (and potential for confusion) is not needed.

**Comment by simonrob** [comment]
I'm going to close this issue as `SIGHUP` solves your issue. As outlined above, separating configuration and token caching is not currently a feature I'm planning.
