### ISSUE TITLE
Missing tag for 2022-12-23 release

### ISSUE THREAD

**Issue by michaelstepner** [simonrob/email-oauth2-proxy#117]
The commit a26edc6e1370f399894059c1fe96beee666eda7a updated the package version:
```
__version__ = '2022-12-23'  # ISO 8601 (YYYY-MM-DD)
```

But there isn't a new [tagged release](https://github.com/simonrob/email-oauth2-proxy/tags) associated with the commit.

**Comment by simonrob** [comment]
I tend to bump the version number with any reasonably meaningful change, but don't currently make a release every time this happens, as I don't really see the need. Is this causing any issues?

**Comment by michaelstepner** [comment]
No issue, I just noticed the discrepancy as I was working on testing PR #114 and didn't realize it was intentional! Closing the issue.
