### ISSUE TITLE
Unclear/incomplete installation instructions for self-contained executable

### ISSUE THREAD

**Issue by bwbug** [simonrob/email-oauth2-proxy#125]
Following the instructions [here (penultimate paragraph)](https://github.com/simonrob/email-oauth2-proxy#dependencies-and-setup), I attempted a bare-metal installation on Windows (i.e., no prior installation of Python or any Python modules) using the following PowerShell expression:

```
pyinstaller --onefile emailproxy.py --hidden-import timeago.locales.en
```

Running the resulting `emailproxy.exe` executable results in the error message "ModuleNotFoundError: No module named 'cryptography'".

What steps am I missing?  Prior to executing the above expression, I installed Python 3.11.1 and PyInstaller 5.7.0, then edited the emailproxy.config file, but otherwise did not install or download any other modules.

**Comment by simonrob** [comment]
> ModuleNotFoundError: No module named 'cryptography'

This is the key error – you have not installed the script's requirements first. Please follow the main instructions first before doing this (I'll clarify this part).
