### ISSUE TITLE
Cannot Delete email in the mailbox

### ISSUE THREAD

**Issue by StefKQ** [simonrob/email-oauth2-proxy#127]
Accessing the MS 365 mailbox through the email proxy works fine in our environment.
There is only one situation where it does not work as expected. We are running a Perl script that is accessing the mailbox through the proxy. It can access the email but when it should delete an email in that mailbox it does not work (the delete command was working before when connecting directly to MS365 with the same script).
Do you have an idea why the delete command would not work through the proxy?

Thanks a lot
Stefan

**Comment by simonrob** [comment]
There should be no impact on normal IMAP operation - the proxy ignores further traffic once authentication is complete.

Please post the proxy's log including an attempt to delete a message with debug mode enabled (`--debug`).

**Comment by simonrob** [comment]
I'm going to assume this was resolved, but feel free to reopen if needed.

**Comment by simonrob** [comment]
There is a chance that this could be related to a regression in 4651993 (#121). It's worth trying the latest proxy version in the main branch to see whether this fixes your issue.
