### ISSUE TITLE
Proxy Infrastructure

### ISSUE THREAD

**Issue by Stefan-Schulze-SIMTEVA** [simonrob/email-oauth2-proxy#130]
Hello,

the python is working perfectly. But we want use this on a Server with require a Proxy Configuration to get access to internet.
I didn´t found a way to get this running.
Can you tell me how to provide the local Proxy configuration to the IMAP Proxy for getting internet access?

**Comment by simonrob** [comment]
The answer is the same as #113 and #123 - use the `https_proxy` environment variable that Python checks to instruct it to use your proxy. I'll add this to the readme going forward.
