### ISSUE TITLE
Redirect URI does not match

### ISSUE THREAD

**Issue by bwbug** [simonrob/email-oauth2-proxy#133]
I have set up my emailproxy.config file following the provided [instructions](https://github.com/simonrob/email-oauth2-proxy#oauth-20-client-credentials) for re-using a `client_id` and `client_secret` from an open-source client.  At the end of the authentication process, I get the following error message from Microsoft in the browser window:

>Message: AADSTS50011: The redirect URI 'http://localhost' specified in the request does not match the redirect URIs configured for the application '3514cf2c-e7a3-45a2-80d4-6a3c3498eca0'. Make sure the redirect URI sent in the request matches one added to your application in the Azure portal. Navigate to https://aka.ms/redirectUriMismatchError to learn more about how to fix this.

How do I fix this issue?   I can try some of the other open source projects listed in the documentation, but many of them do not appear to have a `client_secret` value, and what are the chances that any of them would have authorized `http://localhost` as a redirect URI?

**Comment by simonrob** [comment]
`http://localhost` was until recently the default `redirect_uri` in almost all setups. I am reluctant to point to specific client credentials that could be reused, but certainly some of the ones linked in the readme do use this configuration. The other alternative here is to create your own via Azure AD. I'm afraid I don't currently have time to provide dedicated support for these sorts of cases though.

**Comment by simonrob** [comment]
It would be the client you use - the proxy is not part of the OAuth 2.0 flow, it just facilitates it.
