### ISSUE TITLE
Authorise account appears in GUI but nothing happens when I click the account

### ISSUE THREAD

**Issue by PeteCharles** [simonrob/email-oauth2-proxy#136]
I'm running Kubuntu and have configured everything right up to the point of seeing 'Authorisation request received for email.address@xcompany.com'. I have clicked on the account listed in the Authorise Account section of the GUI but nothing happens. Am I missing something?

Partial config file: - 

[email.address@xcompany.com]
permission_url = https://login.microsoftonline.com/common/oauth2/v2.0/authorize
token_url = https://login.microsoftonline.com/common/oauth2/v2.0/token
oauth2_scope = https://outlook.office365.com/IMAP.AccessAsUser.All https://outlook.office365.com/POP.AccessAsUser.All https://outlook.office365.com/SMTP.Send offline_access
redirect_uri = http://localhost
client_id = xxxxxxx
client_secret = xxxxxxx

**Comment by simonrob** [comment]
I suspect this is something to do with your installation of pywebview. You can diagnose this by trying the basic [pywebview example](https://pywebview.flowrl.com/guide/usage.html#basics) using the same Python setup that you are using for the proxy. If you don't see a browser window then this is the issue.

In the meantime, you can get your account authorised by using one of the `--no-gui` methods: `--local-server-auth` or `--external-auth`.

**Comment by PeteCharles** [comment]
Thank you, that lead me to this: - 

sudo apt install python3-gi python3-gi-cairo gir1.2-gtk-3.0 gir1.2-webkit2-4.0

And it's working perfectly now.

**Comment by simonrob** [comment]
Great - glad this was resolved.
