### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by andre13794** [simonrob/email-oauth2-proxy#137]
Hi all,

today I installed a new proxy - we already have multiple proxies running - but I am getting the following error:
2023-02-15 22:28:59: Returning authorisation request result for mail@domain.com
2023-02-15 22:28:59: Caught exception while requesting OAuth 2.0 credentials for mail@domain.com: PermissionError(13, 'Permission denied`)

The error message only appears after I did the login to authorize the account.
In the logfile in azure / m365 I am able to see that the login itself was successful.

Do you have any Ideas what I am doing wrong here?
(IDs are correct and were checked)

[SMTP-1587]
local_address = IP Address from Proxy
server_address = smtp.office365.com
server_port = 587
starttls = True

[mail@domain.com]
permission_url = https://login.microsoftonline.com/TENANT_ID/oauth2/v2.0/authorize
token_url = https://login.microsoftonline.com/TENANT_ID/oauth2/v2.0/token
oauth2_scope = https://outlook.office365.com/IMAP.AccessAsUser.All https://outlook.office365.com/POP.AccessAsUser.All https://outlook.office365.com/SMTP.Send offline_access
redirect_uri = http://localhost
client_id = Client_ID
client_secret = Client_SECRET

Thanks in advance!
Kind regard
André

**Comment by simonrob** [comment]
I suspect this is a permission issue with the O366 client you are using.

You've requested IMAP, POP and SMTP scopes - did you include all of these when setting up the client?

**Comment by andre13794** [comment]
I´m using:

IMAP.AccessAsUser.All
offline_access
openid
POP.AccessAsUser.All
Delegiert
SMTP.Send
User.Read

What I missed telling:
I try to send the mail using powershells send-mailmessage cmdlet which is using SMTP.

**Comment by simonrob** [comment]
These sorts of issues are very tricky to diagnose remotely, and I don't really have anything else to suggest I'm afraid. It's unlikely to be an issue with the proxy though. Are you sure you've enabled IMAP/POP/SMTP for this account?

**Comment by simonrob** [comment]
I'm going to close this under the assumption that it has been resolved. Feel free to reopen if you found that it was an issue with the proxy itself.

**Comment by andre13794** [comment]
Sorry for the late response.
We were finally able to fix the issue - which where made by a wrong configuration.

The user under which the proxy was running did not have access to write to the emailproxy.conf file.
Thus leading to the "permission denied" message - which better should be "accesss denied".
So in the end the proxy clould not store the tokens into this file.

Maybe it`s possible to implement a startup check wheter this file is writable or not und print a message cleary viewing this problem und then exiting the proxy.

Think you for your feedback anyway!

**Comment by simonrob** [comment]
Thanks for following up again with this extra detail – I agree that the proxy should try to handle this if possible. I'll add a check when the file is saved, which should at least give a more useful error message.
