### ISSUE TITLE
Only IPv6 is bound

### ISSUE THREAD

**Issue by wtcline-intc** [simonrob/email-oauth2-proxy#152]
Since version `2023-03-09`, only the IPv6 interface is being bound.  I tracked this down to commit `966e6e23376afc08c4429e8d6b3b56e23b175565`.  The issue affects a fresh installation of Fedora 37 and Ubuntu 22.04 (minimal install) with the default proxy configuration.

Expected: The proxy continues to bind to IPv4 as before.

Ubuntu 22.04:
```
$ pip3 install -r requirements.txt
$ sudo apt-get install gir1.2-ayatanaappindicator3-0.1
```
Command output gives:
```
2023-03-30 11:15:16: Initialising Email OAuth 2.0 Proxy (version 2023-03-28) from config file /home/wtcline/email-oauth2-proxy/emailproxy.config
2023-03-30 11:15:16: Starting IMAP server at localhost:1993 (unsecured) proxying outlook.office365.com:993 (SSL/TLS)
2023-03-30 11:15:16: Starting POP server at localhost:1995 (unsecured) proxying outlook.office365.com:995 (SSL/TLS)
```
Viewing bound interfaces with `netstat` shows:
```
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp6       0      0 ::1:1993                :::*                    LISTEN      2784/python3
tcp6       0      0 ::1:1995                :::*                    LISTEN      2784/python3
```

Fedora 37:
```
$ sudo yum install gnome-shell-extension-appindicator python3-pip
$ pip3 install -r requirements.txt
<log out and back in>
$ gnome-extensions enable appindicatorsupport@rgcjonas.gmail.com
```
Command output gives:
```
2023-03-30 11:34:49: Initialising Email OAuth 2.0 Proxy (version 2023-03-28) from config file /home/wtcline/email-oauth2-proxy/emailproxy.config
2023-03-30 11:34:49: Starting IMAP server at localhost:1993 (unsecured) proxying outlook.office365.com:993 (SSL/TLS)
2023-03-30 11:34:49: Starting POP server at localhost:1995 (unsecured) proxying outlook.office365.com:995 (SSL/TLS)
```
Viewing bound interfaces with `netstat` shows:
```
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp6       0      0 ::1:1995                :::*                    LISTEN      3916/python3
tcp6       0      0 ::1:1993                :::*                    LISTEN      3916/python3
```

EDIT: Correct "since version `2023-03-28`" to `2023-03-09`.

**Comment by simonrob** [comment]
I think there is a misunderstanding here. The proxy supports both IPv4 and IPv6, and when using a hostname (rather than IP address), will connect to the first address that is returned by the system. I suspect you have both `::1` and `127.0.0.1` mapped to `localhost` (as is usual), and `::1` is being returned first.

If don't want to update your `/etc/hosts` file, but want to use an equivalent for `localhost`, how about using `0.0.0.0`?

If you are happy to listen on _both_ IPv4 and IPv6 you can use the special value `::` if your system supports this feature (see the [documentation](https://github.com/simonrob/email-oauth2-proxy/blob/b7f788a500890db27a6a9cb018b4413dedebe5b0/emailproxy.config#L28)).

**Comment by wtcline-intc** [comment]
> I suspect you have both ::1 and 127.0.0.1 mapped to localhost (as is usual), and ::1 is being returned first.

Looking at `/etc/hosts` does *not* show  `::1` being mapped to `localhost`:
```
$ cat /etc/hosts
127.0.0.1	localhost
127.0.1.1	wtcline-whatever

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```
Yet looking up `localhost` with `nslookup` does show `localhost` mapping to `::1`:
```
$ nslookup  localhost
Server:		127.0.0.53
Address:	127.0.0.53#53

Name:	localhost
Address: 127.0.0.1
Name:	localhost
Address: ::1
```
Weird.  This also shows the IPv4 address before the IPv6 address, but perhaps that's just how `nslookup` displays the results and does not reflect any order returned by system calls.  Yet when I run `ping`, it's IPv4 that's chosen first:
```
$ ping localhost
PING localhost (127.0.0.1) 56(84) bytes of data.
64 bytes from localhost (127.0.0.1): icmp_seq=1 ttl=64 time=0.060 ms
```
I'd expect that `ping`'s default would correspond to the proxy's default, but perhaps that's an erroneous assumption on my part.  The code itself looks to me like it's trying to listen on IPv6 first:
```
socket_family = socket.AF_INET6 if socket_family == socket.AF_UNSPEC else socket_family
```

> If don't want to update your /etc/hosts file, but want to use an equivalent for localhost, how about using 0.0.0.0?

Looks like `127.0.0.1` works, though it will probably brake self-signed certificates issued for `localhost`.

> If you are happy to listen on both IPv4 and IPv6 you can use the special value :: if your system supports this feature (see the [documentation](https://github.com/simonrob/email-oauth2-proxy/blob/b7f788a500890db27a6a9cb018b4413dedebe5b0/emailproxy.config#L28)).

This is only listening on IPv6 (note the extra `:`):
```
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp6       0      0 :::1995                 :::*                    LISTEN      4663/python3        
tcp6       0      0 :::1587                 :::*                    LISTEN      4663/python3        
```
From reading the documentation:
>The `local_address` property can be used to set an IP address or hostname for the proxy to listen on (both IPv4 and IPv6 are supported). If not specified, this value is set to `localhost`. When running the proxy using python 3.8 or later, and in an environment with dual-stack support, the proxy will attempt to listen on both IPv4 and IPv6 hosts simultaneously.

From this, I'd expect the *default* configuration of `localhost` to have the proxy to listen on both IPv4 and IPv6 if available.

>To request this for the local host, set `local_address = ::`.

Now this sentence suggests that dual-stack listening needs to be enabled *explicitly*.  Either way, I tried using `::` and it only appears to listen on IPv6.

I think the common practice in general is for programs to bind to all available stacks for a given name and also have options to explicitly enable/disable other stacks.  So in this case `localhost` would bind to IPv4 and IPv6 by default, and there would be `ipv4 = false` and `ipv6 = false` options available if users needed it.  Thoughts?

**Comment by simonrob** [comment]
Python (and hence the proxy) uses [`getaddrinfo`](https://www.man7.org/linux/man-pages/man3/getaddrinfo.3.html) to look up addresses.

You're correct that the proxy defaults to IPv6. The reason for this is that it needs to use IPv6 to be able to support dual-stack listening.

When using `::` have you actually tried to connect to the proxy on IPv6 and IPv4? (i.e., ignoring `netstat` for a moment). `telnet 127.0.0.1 1993` and `telnet ::1 1993` should both connect if your system supports this.

As far as I know, it isn't possible to bind to `localhost` in a dual-stack manner (multiple sockets are needed instead). The reason for still sticking to this as a default is as you suggest – a self-signed certificate for `localhost` is more flexible (and I don't really want to change the core defaults between proxy versions).

I do appreciate it might sometimes be preferable to bind by name to IPv4, but for what it's worth, I can connect just fine using `openssl s_client -crlf -connect localhost:1993` to a server whose `local_address` is any of `localhost`, `::`, `::1`, `0.0.0.0` or `127.0.0.1`. This is using a self-signed certificate created for `localhost` (not any specific IP addresses) via [`mkcert`](https://github.com/FiloSottile/mkcert).

**Comment by wtcline-intc** [comment]
> You're correct that the proxy defaults to IPv6. The reason for this is that it needs to use IPv6 to be able to support dual-stack listening.

I see, though I find it unintuitive to have this differ from the presumably distro-default stack (as evidenced by `ping`).

> When using `::` have you actually tried to connect to the proxy on IPv6 and IPv4? (i.e., ignoring `netstat` for a moment). `telnet 127.0.0.1 1993` and `telnet ::1 1993` should both connect if your system supports this.

This works.  Odd that `netstat` doesn't show it, but that's clearly a `netstat` issue.

> As far as I know, it isn't possible to bind to `localhost` in a dual-stack manner (multiple sockets are needed instead). The reason for still sticking to this as a default is as you suggest – a self-signed certificate for `localhost` is more flexible (and I don't really want to change the core defaults between proxy versions).

Looks like the self-signed certificate for `localhost` still works if I bind in dual-stack mode or bind to `127.0.0.1`, so that's good, but binding to `localhost` does break my prior workflow due to the change since other tools are trying to use IPv4 but the proxy is binding to IPv6.  My prior workflow also doesn't break if I've disabled IPv6 (`echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6`), which arguably creates the incentive to "just disable IPv6 to fix networking".

If you'd like, I can amend my PR to try and clarify the issue in the documentation, though I'd recommend a change which doesn't in any way encourage users to disable IPv6.

**Comment by simonrob** [comment]
> I see, though I find it unintuitive to have this differ from the presumably distro-default stack (as evidenced by `ping`).

The `ping` command is IPv4 only. Use `ping6` to query IPv6 addresses.

> [...] binding to `localhost` does break my prior workflow due to the change since other tools are trying to use IPv4 but the proxy is binding to IPv6.

I'm not quite sure what the issue is here. Why isn't it acceptable to just bind to `0.0.0.0`/`127.0.0.1` to force IPv4, or `::` to support both protocols?

**Comment by wtcline-intc** [comment]
> The `ping` command is IPv4 only by default. Use `ping -6` to query IPv6 addresses.

I ran into the same issue with `git send-mail`.

> I'm not quite sure what the issue is here. Why isn't it acceptable to just bind to `0.0.0.0`/`127.0.0.1` to force IPv4, or `::` to support both protocols?

The solution works for me, so you have my blessing to close the issue but with the following reservation: I doubt most users running into this compatibility issue will find this GitHub issue; instead, they'll notice `netstat` output, try disabling IPv6, find it works, and consider things "fixed", thus continuing to hamper IPv6 adoption.  If I wasn't supporting other users, that's what I would have done.

**Comment by simonrob** [comment]
Ok - i'll expand the configuration file documentation to reflect this discussion. Thanks for helping improve the proxy.

**Comment by wtcline-intc** [comment]
Thanks for helping to resolve the issue!
