### ISSUE TITLE
multi-tenant application

### ISSUE THREAD

**Issue by abreuferr** [simonrob/email-oauth2-proxy#154]
I'm trying to configure email-oauth2-proxy software in Microsoft Office365 but I'm having problems, error message below.

"Authorisation result error for cferreira@segi9.onmicrosoft.com - aborting login. OAuth 2.0 authorisation error: invalid_request; AADSTS50194: Application '4545ef1b-9a5e-418e-88fb-f12528e1c8ac'(email-oauth2-proxy) is not configured as a multi-tenant application. Usage of the /common endpoint is not supported for such applications created after '10/15/2018'. Use a tenant-specific endpoint or configure the application to be multi-tenant."

$ cat /etc/email-auth2-proxy/config.cfg
[emailproxy]
delete_account_token_on_password_error = True
encrypt_client_secret_on_first_use = False
allow_catch_all_accounts = True
 
[IMAP-2993]
server_address = outlook.office365.com
server_port = 993

[POP-2995]
server_address = outlook.office365.com
server_port = 995

[SMTP-2465]
server_address = smtp.office365.com
server_port = 587
starttls = True

 [@]
redirect_uri = https://localhost
redirect_listen_address = http://127.0.0.1:8801/
token_url = https://login.microsoftonline.com/common/oauth2/v2.0/token
oauth2_scope = https://outlook.office365.com/IMAP.AccessAsUser.All https://outlook.office365.com/POP.AccessAsUser.All https://outlook.office365.com/SMTP.Send offline_access
client_id = *** client id ***
client_secret = *** client secret ***
permission_url = https://login.microsoftonline.com/common/oauth2/v2.0/authorize

Any idea what's wrong?

Best regards

**Comment by simonrob** [comment]
This is answered in both the error message you are receiving and in the [proxy's configuration documentation](https://github.com/simonrob/email-oauth2-proxy/blob/20d493fa7a8677628538c2cc1459f653b18a2bd0/emailproxy.config#L101). I'll see if I can make this clearer / more findable.

**Comment by abreuferr** [comment]
Dear Simon Robinson

Thanks for your help.

Best regards
