### ISSUE TITLE
Webrender Blank Page

### ISSUE THREAD

**Issue by dotmax** [simonrob/email-oauth2-proxy#158]
Hi, on windows 10 when i try to authorize a client i get a webrenderer blank window
and in che console i get
"[pywebview] MSHTML is deprecated. See https://pywebview.flowrl.com/guide/renderer.html#web-engine on details how to use Edge Chromium"

in the code i have tried (in function authorise_account ) to change the rendererer from mshtml to edgehtml or edgechromium
but i still get a blank page.

and if i try to use the external auth, i cannot paste the result url in the box....

can you help me?

**Comment by simonrob** [comment]
This is a [known issue](https://github.com/simonrob/email-oauth2-proxy#known-issues) in some Python configurations, and the proxy can't do much about it. Have you tried the suggestions listed in that section of the readme?

**Comment by dotmax** [comment]
Sorry i missed that, now it works!!

Some additional information:
The os is Windows Server, and by default the browser (internet explorer) is in "Enhanced Security mode"
After starting the proxy with the debug mode option, on the webrenderer  window suddently i notices some javascript errors.
So i disabled the "Enhanced Security mode" and now i can see the content of the windows and successfully complete the browser authentication phase.

Thank you
