### ISSUE TITLE
Unkown username authenticating office365 pop3

### ISSUE THREAD

**Issue by dmonza** [simonrob/email-oauth2-proxy#160]
I having this issue when I try to connect to outlook 365.

![image](https://user-images.githubusercontent.com/9719956/233171278-4f18b335-0eb1-47cd-b1fe-5b9e42d30aac.png)

Is correct to use USER/PASS with XOAUTH2?

Thank you,

**Comment by simonrob** [comment]
This error is from O365 rather than the proxy. (I'm assuming that between 18:38:34 and 18:38:38 you completed the OAuth authentication process and logged in.)

Is POP3 enabled for this account?

**Comment by simonrob** [comment]
That difference is because the proxy removes the XOAUTH2 capability from the POP3 response (as it doesn't support it; it provides it remotely on your behalf).

Could you share your configuration file?

Are you receiving and approving and authentication request from the proxy?

**Comment by simonrob** [comment]
Ah – setting up the client credentials flow correctly on the Azure AD side can be a lot harder than with the default interactive OAuth 2.0 flow. I'd recommend getting the basic version working first, and only then moving to more advanced configurations.

Does the default configuration work? I.e.:

```ini
[your.office365.address@example.com]
permission_url = https://login.microsoftonline.com/common/oauth2/v2.0/authorize
token_url = https://login.microsoftonline.com/common/oauth2/v2.0/token
oauth2_scope = https://outlook.office365.com/IMAP.AccessAsUser.All https://outlook.office365.com/POP.AccessAsUser.All https://outlook.office365.com/SMTP.Send offline_access
redirect_uri = http://localhost
client_id = *** your client id here ***
client_secret = *** your client secret here ***
```

**Comment by dmonza** [comment]
Well, is working! 

Thank you for your help, this app is very helpful with legacy apps.

We flow this guide to get working the client credentials flow. May be useful for anyone in this situation.
https://www.youtube.com/watch?v=bMYA-146dmM
