### ISSUE TITLE
Thunderbird, MS-Office 365 (Tenant account) and email-oauth2-proxy

### ISSUE THREAD

**Issue by abreuferr** [simonrob/email-oauth2-proxy#161]
I am having trouble setting up email-oauth2-proxy with Thunderbird on my Microsoft Office 365 tenant account (abreuferr@dreamcapy.com). 

The email-oauth2-proxy configuration file should look like this:

# cat settings.cfg
[emailproxy]
delete_account_token_on_password_error = True
encrypt_client_secret_on_first_use = False
allow_catch_all_accounts = True

[IMAP-2993]
server_address = outlook.office365.com
server_port = 993

[SMTP-2465]
server_address = smtp.office365.com
server_port = 587
starttls = True

[@]
token_url = https://login.microsoftonline.com/TENANT_ID/oauth2/v2.0/token
oauth2_scope = https://outlook.office365.com/.default
oauth2_flow = client_credentials
redirect_uri = localhost
redirect_listen_address = http://127.0.0.1:8801/
client_id = CLIENT_ID
client_secret = CLIENT_SECRET

After configuring Thunderbird to use email-oauth2-proxy, the configuration file should look something like this:

# cat settings.cfg
[emailproxy]
delete_account_token_on_password_error = True
encrypt_client_secret_on_first_use = False
allow_catch_all_accounts = True

[IMAP-2993]
server_address = outlook.office365.com
server_port = 993

[SMTP-2465]
server_address = smtp.office365.com
server_port = 587
starttls = True

[@]
token_url = https://login.microsoftonline.com/TENANT_ID/oauth2/v2.0/token
oauth2_scope = https://outlook.office365.com/.default
oauth2_flow = client_credentials
redirect_uri = localhost
redirect_listen_address = http://127.0.0.1:8801/
client_id = CLIENT_ID
client_secret = CLIENT_SECRET

[abreuferr@dreamcapy.com]
token_salt = <VALUE>
access_token = <VALUE>
access_token_expiry = <VALUE>

Based on my understanding, it seems that email-oauth2-proxy has been configured correctly. However, I am unable to access the IMAP box of the email account "abreuferr@dreamcapy.com", and are also unable to send emails using SMTP.

best regards,

caio abreu ferreira

**Comment by simonrob** [comment]
This is an issue with your Azure AD setup. I'd recommend starting with the basic OAuth flow first, and only then turning to the client credentials or resource owner password credentials options.

Please also note that as the readme explains, O365 does not support SMTP in these advanced configurations.

**Comment by simonrob** [comment]
I'm assuming that this has been resolved, so am closing this issue. Feel free to re-open that is not the case.

**Comment by abreuferr** [comment]
dear Simon Robinson

Unfortunately, I was unable to solve the problem.

According to the software log file, the following error message appeared:

May  4 17:58:14 ID-8988-senhasegura-3 email-oauth2-proxy - 95c4d905f1f1[18834]: IMAP (localhost:2993; 127.0.0.1:42400->outlook.office365.com:993; abreuferr@mydomain.com) <-- b'12 NO AUTHENTICATE failed.\r\n'

I checked the username and password, and they are correct.

However, in order to access the email account in Microsoft Outlook (web), it may be necessary to use Microsoft's authentication application.

best regards,

**Comment by simonrob** [comment]
Did you try the suggestions from my previous reply? I would strongly recommend the default configuration to get started, rather than the advanced one. I.e.:

```ini
[@]
permission_url = https://login.microsoftonline.com/common/oauth2/v2.0/authorize
token_url = https://login.microsoftonline.com/common/oauth2/v2.0/token
oauth2_scope = https://outlook.office365.com/IMAP.AccessAsUser.All https://outlook.office365.com/POP.AccessAsUser.All https://outlook.office365.com/SMTP.Send offline_access
redirect_uri = http://localhost
client_id = *** your client id here ***
client_secret = *** your client secret here ***
```

As noted previously, if you use the configuration you posted, **SMTP will not work** – it is not supported by Microsoft when using the client credentials flow.

Regarding the use of an authentication application: this may well be the case when you initially authorise the account, but once this is done, you will not need to do so until the next enforced token renewal (usually many months).

**Comment by simonrob** [comment]
I'm assuming again that this has been resolved, so am closing this issue. If you have tried the various solutions I've suggested and have more information about an issue with the proxy feel free to reopen; otherwise, the options already given are your best way forward.
