### ISSUE TITLE
Google "send mail as"

### ISSUE THREAD

**Issue by sbalbale** [simonrob/email-oauth2-proxy#163]
Is there a way to set up a o365 account with googles send mail as feature?

I true following the instructions but I couldn't seem to get it to work

**Comment by simonrob** [comment]
Gmail only allows unencrypted connections (the proxy's default) on port 25, so you'd need to switch to this (and run in sudo mode). If you provide your own local certificate (see the [configuration example](https://github.com/simonrob/email-oauth2-proxy/blob/6a29b1ffdd8fa9ffbcb4fd0d6614a2b4ba4f4d0f/emailproxy.config#L35)) then you can use port 465 or 587. If it helps, see the previous discussion of this in #9.

**Comment by simonrob** [comment]
I'm going to close this as it isn't an issue with the proxy, but am happy to take suggestions about how to improve the proxy's instructions to make this easier.
