### ISSUE TITLE
Blank Screen for Authentication prompt

### ISSUE THREAD

**Issue by articodes** [simonrob/email-oauth2-proxy#165]
Running on Windows Server 2019 and I am getting blank screen when I try to authorize the account. How do I make sure I can authenticate if nothing is rendering?

**Comment by articodes** [comment]
This is what the logs shows.
[pywebview] MSHTML is deprecated. See https://pywebview.flowrl.com/guide/renderer.html#web-engine on details how to use Edge Chromium

**Comment by simonrob** [comment]
> There are [some known situations](https://github.com/simonrob/email-oauth2-proxy#known-issues) in which the inbuilt webview does not work well, or has issues. Have you tried the proxy's `--external-auth` or `--local-server-auth` options?

Did you try this?

**Comment by articodes** [comment]
Seems to be related to Internet Explorer where some of the IE settings impacts the render issue. Review and fix IE security to resolve this issue.

**Comment by simonrob** [comment]
Thanks for following up. If you could provide any more detail about exactly what you needed to change I'm sure that'd be useful for anyone else encountering this issue.
