### ISSUE TITLE
Authorization fails using --no-gui and --external-auth with Office 365

### ISSUE THREAD

**Issue by diizzyy** [simonrob/email-oauth2-proxy#167]
I guess this is a configuration issue on my end but I'm not really sure what's causing it and therefore how to fix it. This is executed on a headless box which should work(?) as far as I can tell.

What I have in emailproxy's configuration file:

```
[SMTP-25]
local_address = 192.168.24.254
server_address = smtp.office365.com
server_port = 587
starttls = True

[mailout@foobar.org]
permission_url = https://login.microsoftonline.com/common/oauth2/v2.0/authorize
token_url = https://login.microsoftonline.com/common/oauth2/v2.0/token
oauth2_scope = https://outlook.office365.com/IMAP.AccessAsUser.All https://outlook.office365.com/POP.AccessAsUser.All https://outlook.office365.com/SMTP.Send offline_access
redirect_uri = http://localhost
client_id = XXX
client_secret = XXX

[emailproxy]
delete_account_token_on_password_error = True
encrypt_client_secret_on_first_use = False
allow_catch_all_accounts = False
```

Executed using: 
```/usr/local/bin/emailproxy --no-gui --external-auth --config-file /home/foobar/emailproxy.conf```

This results in the expected login URL however once you've entered your credentials you're greeted by:
```
AADSTS500113: No reply address is registered for the application.
```

I followed this guide to configure Office 365
https://intercom.help/security-studio/en/articles/5087114-setup-email-smtp-settings-with-office365-oauth2-authentication

**Comment by simonrob** [comment]
It sounds like you haven't set up a desktop app registration, and as a result are getting an error that there is no redirect URI registered.

Microsoft provide a guide (linked from the proxy's example file) to help you set up an app registration correctly: https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-register-app

**Comment by diizzyy** [comment]
Turned out to be a missing entry for reply address in Azure, everything worked great otherwise.
Sorry for the noise and thanks for a great application!
