### ISSUE TITLE
Is it possible to use without an app and for direct email tunneling?

### ISSUE THREAD

**Issue by mshlis** [simonrob/email-oauth2-proxy#168]
I am trying to send/recieve email from an outlook account via a gmail account. Can this be used here to get past the 2fa issue. I wanted to do what is described in the solution of [this forum question](https://webapps.stackexchange.com/questions/76562/use-gmail-to-send-and-receive-e-mail-from-an-outlook-com-account), but is no longer able to be done now that 2fa is required.

What I have done is:
- Configure config with outlook client id/secret (create app in azure active directory admin center to generate these)
- run server
- tried to add as alias from gmail

Issues I have come across:
- Wont allow localhost/127.0.0.1 as SMTP server
- Ports are drop down of values: 25; 465; 587 -- so i cant set to 1587

**Comment by simonrob** [comment]
Yes - there are several other issues discussing this setup. You'll need to run your own publicly accessible server to do this, however, as Gmail cannot connect to your local host unless it is publicly reachable.

**Comment by mshlis** [comment]
> Yes - there are several other issues discussing this setup. You'll need to run your own publicly accessible server to do this, however, as Gmail cannot connect to your local host unless it is publicly reachable.

If I setup a public server running the proxy, can i overwrite port 587 of the machine or will that cause issues?

**Comment by simonrob** [comment]
Yes - you can run the proxy on any port you like. The defaults are chosen simply to avoid having to use `sudo` in a normal environment.
