### ISSUE TITLE
Authorization token duration

### ISSUE THREAD

**Issue by ivanfdez** [simonrob/email-oauth2-proxy#17]
How long does the authorization token last?
In my case it is lost every week, having to re-authorize the account.

**Comment by ivanfdez** [comment]
[https://developers.google.com/identity/protocols/oauth2?hl=en#expiration]

A Google Cloud Platform project with an OAuth consent screen configured for an external user type and a publishing status of "Testing" is issued a refresh token expiring in 7 days.

**Comment by simonrob** [comment]
Yes – API clients that are in test mode (or are unpublished/unreviewed) often have quite short-lived tokens. They also typically have an additional warning step in the authorisation flow.

The solution is either to publish your project or use an ID/secret from an existing client.
