### ISSUE TITLE
Proxy crashes with OC_PythonException when clicking "Authorise Account" on macOS Ventura

### ISSUE THREAD

**Issue by Draykan** [simonrob/email-oauth2-proxy#170]
I use Email OAuth 2.0 Proxy to access Office 365 mailboxes with IMAP using Apple Mail on Mac.
Since I updated the Proxy to version 2023-05-18 and pywebview to v4.1, it crashes every time I try to open the window to authorise an e-mail account.

System information and software versions:
• MacBook Air (M1, 2020)
• macOS Ventura 13.5 (22G5038d) Beta 2
• Command Line Tools for Xcode 14.3 (installed for the first time on 04/04/2023, updated apparently to the same version on 06/06/2023 with Software Update)

`python3 --version`
```
Python 3.9.6
```

`python3 -m pip list`
```
Package                              Version
------------------------------------ -------
altgraph                             0.17.2
bottle                               0.12.23
cffi                                 1.15.1
cryptography                         39.0.0
future                               0.18.2
macholib                             1.15.2
Pillow                               9.4.0
pip                                  21.2.4
prompt-toolkit                       3.0.36
proxy-tools                          0.1.0
pycparser                            2.21
pyobjc-core                          9.0.1
pyobjc-framework-Cocoa               9.0.1
pyobjc-framework-Quartz              9.0.1
pyobjc-framework-SystemConfiguration 9.0.1
pyobjc-framework-WebKit              9.0.1
pyoslog                              1.1.0
pystray                              0.19.4
pywebview                            4.1
setuptools                           58.0.4
six                                  1.15.0
timeago                              1.0.16
wcwidth                              0.2.6
wheel                                0.37.0
WARNING: You are using pip version 21.2.4; however, version 23.1.2 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
```

Each time it crashes, this message is printed to the Console.app log stream:
```
*** Terminating app due to uncaught exception 'OC_PythonException', reason: '<class 'ModuleNotFoundError'>: No module named 'Security''
*** First throw call stack:
(
	0   CoreFoundation                      0x000000019a7af154 __exceptionPreprocess + 176
	1   libobjc.A.dylib                     0x000000019a2ce4d4 objc_exception_throw + 60
	2   _objc.cpython-39-darwin.so          0x0000000106386b14 PyObjCUtil_Strdup + 0
	3   _objc.cpython-39-darwin.so          0x0000000106367424 method_stub + 5960
	4   libffi.dylib                        0x00000001aaafaf44 ffi_closure_SYSV_inner + 816
	5   libffi.dylib                        0x00000001aaaf21e8 ffi_closure_SYSV + 56
	6   WebKit                              0x00000001bbd94738 _ZN6WebKit15NavigationState16NavigationClient33didReceiveAuthenticationChallengeERNS_12WebPageProxyERNS_28AuthenticationChallengeProxyE + 228
	7   WebKit                              0x00000001bbfe84a8 _ZN6WebKit19NetworkProcessProxy33didReceiveAuthenticationChallengeEN3PAL9SessionI<…>
```

This is an example of a Python crash log that is generated each time the Proxy crashes:
[Python-2023-06-09-160958.ips.zip](https://github.com/simonrob/email-oauth2-proxy/files/11707186/Python-2023-06-09-160958.ips.zip)

**Comment by simonrob** [comment]
Thanks for reporting this. It looks to be the same issue as #164, but unfortunately I don't currently have that particular macOS environment, and so cannot yet replicate it. However, I plan to try this out next week, and once it can be reproduced it can hopefully be worked around.

In the meantime I'd recommend trying the proxy's non-webview authentication options if they're possible in your setup.

**Comment by simonrob** [comment]
I've found the cause of this issue – a bug in pywebview 4.1 (see [#1154](https://github.com/r0x0r/pywebview/pull/1154) and [#1137](https://github.com/r0x0r/pywebview/issues/1137)). You can fix this in your own copy by downgrading to pywebview 4.0.2, but I'll keep this issue open here as a way to track when the next release is available to pin the fixed version.

**Comment by Draykan** [comment]
Thank you very much Simon for the quick response!
Since you found out that the cause of the issue is the missing `pyobjc-framework-Security` framework, I installed it with command `python3 -m pip install pyobjc-framework-Security` and now it works just fine, thank you!
