### ISSUE TITLE
Google Mail and POP3

### ISSUE THREAD

**Issue by abreuferr** [simonrob/email-oauth2-proxy#171]
Simon Robinson

I have managed to configure the 'email-oauth2-proxy' software to function with Google Mail and Microsoft Office 365, utilizing the IMAP protocol. I am currently experiencing trouble with Google's POP3 protocol.

$ cat /etc/email-oauth2-proxy/settings.cfg

[emailproxy]
delete_account_token_on_password_error = True
encrypt_client_secret_on_first_use = False
allow_catch_all_accounts = True

[IMAP-2993]
server_address = imap.gmail.com
server_port = 993

[POP-2995]
server_address = pop3.gmail.com
server_port = 995

[SMTP-2465]
server_address = smtp.gmail.com
server_port = 465

[@]
redirect_uri = https://localhost/email-oauth2-proxy-authorize/
redirect_listen_address = http://127.0.0.1:8801/
token_url = https://oauth2.googleapis.com/token
oauth2_scope = https://mail.google.com/
client_id = CLIENT_ID
client_secret = CLIENT_SECRET
permission_url = https://accounts.google.com/o/oauth2/auth

When I test with Thunderbird email software, I am getting the following error message below.

Jun 12 16:35:03 senhasegura email-oauth2-proxy - b7ce08ef9513[1375]: Caught asyncore info message in POP server at localhost:2995 (unsecured) proxying pop3.gmail.com:995 (SSL/TLS) - error : uncaptured python exception, closing channel <__main__.OAuth2Proxy listening localhost:2995 at 0x7f2eded0b810> (<class 'socket.gaierror'>:[Errno -2] Name does not resolve [/usr/local/lib/python3.11/asyncore.py|read|88] [/usr/local/lib/python3.11/asyncore.py|handle_read_event|419] [/email-oauth2-proxy/emailproxy.py|handle_accept|1651] [/email-oauth2-proxy/emailproxy.py|handle_accepted|1662] [/email-oauth2-proxy/emailproxy.py|__init__|1462] [/email-oauth2-proxy/emailproxy.py|__init__|1305] [/usr/local/lib/python3.11/asyncore.py|connect|336])

I've made a number of changes to the software's configuration file and unfortunately I'm still unsuccessful. Any idea what could be wrong in the config file?

best regards,

caio abreu ferreira

**Comment by simonrob** [comment]
What version of the proxy are you using? (`python emailproxy.py --version`)

The error is not one I've seen before, but I suspect this is something to do with IPv4 vs. IPv6 binding. It is worth trying specifying a `local_address` value (see the [documentation](https://github.com/simonrob/email-oauth2-proxy/blob/e945c0c341c9de7d27c89178ce93919f1fd9d39f/emailproxy.config#L28)) – for example, `127.0.0.1` or `::1`.

**Comment by simonrob** [comment]
Please could you post the full proxy log that includes this error message? (in `--debug` mode)

**Comment by abreuferr** [comment]
Simon Robinson

I found the error. I was using 'pop3.gmail.com' instead of 'pop.gmail.com'. 

Now, I have another problem with the pop3, message attachment file.
[error.txt](https://github.com/simonrob/email-oauth2-proxy/files/11750525/error.txt)

best regards,

**Comment by simonrob** [comment]
Please upgrade to the latest version of the proxy and try again?

**Comment by simonrob** [comment]
I'm going to assume that this is now resolved, but please feel free to re-open if that is not the case.
