### ISSUE TITLE
No error in terminal but SMTP does not connect

### ISSUE THREAD

**Issue by mareekkk** [simonrob/email-oauth2-proxy#178]
![Screenshot_20230626_190156](https://github.com/simonrob/email-oauth2-proxy/assets/11805713/3977a6f0-c94c-4857-9520-2fac870e2d7c)

I have successfully connected IMAP but not SMTP. I tried 127.0.0.1 instead of localhost too but same problem. Tried Mailspring client and Kmail.

Is this a bug?

I am using Kubuntu with the latest Surface Kernel if this helps.

**Comment by simonrob** [comment]
It's unlikely that this is a bug given how common it is to use the proxy with O365. As [explained in the readme](https://github.com/simonrob/email-oauth2-proxy#troubleshooting), it is always worth trying to connect via a terminal first. You mention trying the IPv4 address directly; have you tried the IPv6 version?

If this still doesn't help, please post the proxy log in `--debug` mode, the log that your client is offering (in the screenshot) and your configuration file.

**Comment by mareekkk** [comment]
> It's unlikely that this is a bug given how common it is to use the proxy with O365. As [explained in the readme](https://github.com/simonrob/email-oauth2-proxy#troubleshooting), it is always worth trying to connect via a terminal first. You mention trying the IPv4 address directly; have you tried the IPv6 version?
> 
> If this still doesn't help, please post the proxy log in `--debug` mode, the log that your client is offering (in the screenshot) and your configuration file.

Thank you! It works now by using IPv6. 

Solution: Use ::1 in SMTP server instead of localhost or 127.0.0.1

**Comment by simonrob** [comment]
Thanks for following up – I'm glad you were able to resolve this.
