### ISSUE TITLE
Can this be used as public SMTP proxy?

### ISSUE THREAD

**Issue by fan-wen** [simonrob/email-oauth2-proxy#180]
This is great as a local proxy.

However, if I want to use this as a public SMTP proxy (to add Office365 account to my Gmail as a "send-as" account), I cannot connect to the proxy through xx.xx.xx.xx:587 (xx.xx.xx.xx is the IP of the machine where I set up this proxy).

Any help would be highly highly appreciated!

**Comment by simonrob** [comment]
Yes - there are several other issues discussing this setup (#9, for example). You'll need to run your own publicly accessible server to do this, however, as Gmail cannot connect to your local host unless it is publicly reachable.
