### ISSUE TITLE
 issue : Listening for authentication requests

### ISSUE THREAD

**Issue by RandalfLegris** [simonrob/email-oauth2-proxy#184]
Hi 
i did the no-gui install of this email-oauth2- proxy and when i execute it for the first time i got this : 
![image](https://github.com/simonrob/email-oauth2-proxy/assets/137157628/b7146a3d-e6b2-445d-a589-e995166d3882)
but i don't understand how to connect my email client. i have seen this github thanks to him https://movementarian.org/blog/posts/a-headless-office-365-proxy/   .
And i try to do the same but i did'nt detect fetchmail like him.
i will share you my emailproxy config file : 
![image](https://github.com/simonrob/email-oauth2-proxy/assets/137157628/73636634-eb5f-4545-bd82-674251619c3b)
Please help me i will check this post often to looking for answers.

**Comment by simonrob** [comment]
There is no issue here – all you need to do is actually connect your client to the proxy rather than the main O365 servers. Please read the [getting started guide](https://github.com/simonrob/email-oauth2-proxy#getting-started) (you've completed the first two paragraphs already).
