### ISSUE TITLE
Systray icon has insufficient contrast in Windows light themes

### ISSUE THREAD

**Issue by bwbug** [simonrob/email-oauth2-proxy#187]
I've just installed the proxy on a new Windows 11 laptop, which came configured with a Windows "Light" theme that uses light background colors in the taskbar and elsewhere.  The "OA" systray icon is designed to be white with a transparent background, and as a result, it is practically impossible to identify the icon unless I customize the Windows operating system to a darker theme:

![oa-icon](https://github.com/simonrob/email-oauth2-proxy/assets/109386143/26385550-6339-4151-a344-177918847437)

I would suggest modifying the icon to give it sufficient contrast to work in both dark or light modes.  One possibility is to add internal and external borders in a dark color, as illustrated in this mock-up:

![oa-icon-mockup](https://github.com/simonrob/email-oauth2-proxy/assets/109386143/668bf3f5-bccf-4e7a-b521-fa4cca0f553e)

Alternatively, change the icon color to something other than white. 

Thanks!

**Comment by simonrob** [comment]
This is a trade-off between having sufficient cross-platform compatibility and the need to do lots of per-platform customisation.

I use macOS, so have focused on that platform. With macOS it is possible to set menu bar (i.e., system tray) icons to be seen as "templates", which makes the OS treat them as a mask that is automatically modified in light/dark mode, rather than using the icon directly. I'm not sure if this is possible on Windows, but I'm happy to accommodate it if something like that exists.

If not, you can change the colour of the icon [here](https://github.com/simonrob/email-oauth2-proxy/blob/f7b165e8b0c51fb1cd59c402550f9cf4c991af3e/emailproxy.py#L2302).

**Comment by simonrob** [comment]
To follow up, this small edit should make the icon colour react to the theme type (at startup only; not if you change theme while running the proxy). Could you add it [here](https://github.com/simonrob/email-oauth2-proxy/blob/f7b165e8b0c51fb1cd59c402550f9cf4c991af3e/emailproxy.py#L2307) and let me know whether this works for you?

```diff
         icon_background_height = 44
         icon_width = 40  # to allow for padding between icon and background image size
 
+        if sys.platform == 'win32':
+            import winreg
+            try:
+                key = winreg.OpenKey(winreg.HKEY_CURRENT_USER,
+                                     r'Software\Microsoft\Windows\CurrentVersion\Themes\Personalize')
+                icon_colour = 'white' if winreg.QueryValueEx(key, 'AppsUseLightTheme')[0] == 0 else 'black'
+            except FileNotFoundError:
+                pass
+
         # find the largest font size that will let us draw the icon within the available width
         minimum_font_size = 1
         maximum_font_size = 255
```

**Comment by simonrob** [comment]
To make things easier, this change is now in the [icon-colour branch](https://github.com/simonrob/email-oauth2-proxy/tree/icon-colour). Let me know how you get on?

**Comment by simonrob** [comment]
Here's a [preview build](https://github.com/simonrob/email-oauth2-proxy/files/12469019/emailproxy-2023-08-28_pyinstaller-Windows.zip) of this branch – could you let me know whether this works?

**Comment by simonrob** [comment]
Thanks for the pointer. Does [this new version](https://github.com/simonrob/email-oauth2-proxy/files/12504629/emailproxy-2023-08-28_pyinstaller-Windows.zip) with that change work as expected for both theme types?

**Comment by simonrob** [comment]
Great – third time lucky, then: how about [this version](https://github.com/simonrob/email-oauth2-proxy/files/12507358/emailproxy-2023-08-28_pyinstaller-Windows.zip)?

**Comment by simonrob** [comment]
Excellent! Thanks for reporting this and for testing the various attempts to solve it. I'll merge this branch and it'll be in the next release.
