### ISSUE TITLE
SmtpClientAuthentication is disabled for the Tenant

### ISSUE THREAD

**Issue by bemoody** [simonrob/email-oauth2-proxy#193]
When trying to send mail to smtp.office365.com, I get the error message:

```
535 5.7.139 Authentication unsuccessful, SmtpClientAuthentication is disabled for the Tenant. Visit https://aka.ms/smtp_auth_disabled for more information. [MN2PR05CA0004.namprd05.prod.outlook.com 2023-09-12T20:59:57.214Z 08DBB276B7E699C4]
```

Said page claims: "Virtually all modern email clients that connect to Exchange Online mailboxes in Office 365 or Microsoft 365 (for example, Outlook, Outlook on the web, iOS Mail, Outlook for iOS and Android, etc.) don't use SMTP AUTH to send email messages."

Does anybody have a clue what "virtually all modern email clients" do instead, if they don't use SMTP?

**Comment by simonrob** [comment]
Microsoft tries to disguise the fact that SMTP is supported through opaque error messages and pages like that. See: https://learn.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/authenticated-client-smtp-submission
