### ISSUE TITLE
Running GUI as Windows Service

### ISSUE THREAD

**Issue by GGSMK** [simonrob/email-oauth2-proxy#202]
thanks for this awesome app!

We need to use the GUI version because we use SMTP. But the authentication shouldn´t come up again if my understanding is correct.
So would it be safe to run the no-gui version as a service?

**Comment by simonrob** [comment]
I'm not sure why SMTP in particular requires the GUI in your case (and why the [no-GUI auth options](https://github.com/simonrob/email-oauth2-proxy#optional-arguments-and-configuration) aren't suitable), but either way, it is not needed again until your provider requires re-authentication. Whether (and when) this happens is down to the service you are using – for example, with O365 there are [all sorts of options](https://learn.microsoft.com/en-us/entra/identity/conditional-access/howto-conditional-access-session-lifetime) for admins to configure this. I'd go ahead and try running it as a service – it is typical on the order of months before re-authentication is needed.

**Comment by D4rki91** [comment]
Hey, can someone explain me how I can register the proxy as a service at Windows?
Do I have to convert my proxy autostart bat to exe and register it with sc.exe?

**Comment by GGSMK** [comment]
i ended up using either  [winsw](https://github.com/winsw/winsw) or [NSSM](https://nssm.cc/).

**Comment by D4rki91** [comment]
Im also trying to get it running with NSSM right now but the service is always unexpected closing. Can you provide me an example of your solution please?

**Comment by D4rki91** [comment]
This is my attempt thats not working.

nssm install YourServiceName C:\Path\to\python.exe
nssm set YourServiceName AppDirectory "C:\email-oauth2-proxy-main"
nssm set YourServiceName AppParameters "C:\email-oauth2-proxy-main\emailproxy.py --local-server-auth --debug"
nssm start YourServiceName

**Comment by GGSMK** [comment]
Sorry i do not have access to my solution anymore. From what i can remember i enabled logging in nssm and figured it out based on the logs. Hope it helps!
