### ISSUE TITLE
Suggestion: Rename emailproxy.config in repository

### ISSUE THREAD

**Issue by andyboeh** [simonrob/email-oauth2-proxy#210]
When updating via `git pull`, it errors out with "Your local changes to the following files would be overwritten by merge: emailproxy.config". Of course I can stash or simply copy my config file to a backup, but:

Would it be a viable option to rename emailproxy.config in the repository to emailproxy.config.example and have users rename / copy the file on first use? Or are there other suggestions?

Thanks

**Comment by simonrob** [comment]
Thanks for the suggestion. It's an option, but it would make setup harder, so instead, if you're actively tracking the gut repository I'd recommend using the `--config-file` option and keeping your personal config file elsewhere.

**Comment by andyboeh** [comment]
I overlooked this option, thanks for the suggestion!
