### ISSUE TITLE
Version String in Release 2023-12-19

### ISSUE THREAD

**Issue by w5pny** [simonrob/email-oauth2-proxy#216]
Release 2023-12-19 has:

__version__ = '2023-11-19'  # ISO 8601 (YYYY-MM-DD)

Should that have been:

__version__ = '2023-12-19'  # ISO 8601 (YYYY-MM-DD)

Does it matter?

**Comment by simonrob** [comment]
Thanks for pointing this out. It's not a problem (except in that it could cause confusion), but it's easy enough to overlook, so I made a [pre-commit hook](https://github.com/simonrob/check-iso8601-version-string/) to prevent it in future.
