### ISSUE TITLE
Please document how to specify --config path in the plist file

### ISSUE THREAD

**Issue by geeohgeegeeoh** [simonrob/email-oauth2-proxy#225]
I'd like to move the emailproxy.config to a ~/.config/email-oauth2-proxy/emailproxy.config location. Can you please document what flags and arguments can be put in the plist file?

**Comment by simonrob** [comment]
The `.plist` file just contains the commands to run the proxy, so the documentation is the same as that already given in the readme.

If you deselect them re-select the `Start at login` option when running with the preferred config file path, the `.plist` file should be updated automatically for you.

If you meant documentation about the format of the file itself, see [Apple's articles](https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPSystemStartup/Chapters/CreatingLaunchdJobs.html), or try a tool like [Launch Control](https://www.soma-zone.com/LaunchControl/).

**Comment by geeohgeegeeoh** [comment]
So basically, whatever command line arguments you specify to run the
command will be written into the plist file?

Easy! Thanks. Close the issue, nothing to see here.

G

**Comment by geeohgeegeeoh** [comment]
```
<key>ProgramArguments</key>
	<array>
		<string>/opt/homebrew/opt/python@3.11/bin/python3.11</string>
		<string>/Users/<someusername>/Source/email-oauth2-proxy/emailproxy.py</string>
		<string>--config-file</string>
		<string>/Users/<someusername>/.config/email-oauth2-proxy/emailproxy.config</string>
	</array>
```

(for completeness, what the configuration looks like in the .plist once you add commandline arguments.)
