### ISSUE TITLE
Issue with external auth mode - copy / paste of code

### ISSUE THREAD

**Issue by pmatz506** [simonrob/email-oauth2-proxy#245]
Hello, I have a problem with copy and paste of code in "Authorize your account" windows.
Paste doesn't work. (windows 2022 standard server - 2024-03-15 version emailproxy).
Can you help me please

**Comment by simonrob** [comment]
Please see the [known issues](https://github.com/simonrob/email-oauth2-proxy?tab=readme-ov-file#known-issues) section of the readme.
