### ISSUE TITLE
Python version support - question

### ISSUE THREAD

**Issue by proxyheavennhell** [simonrob/email-oauth2-proxy#249]
Hi again.

Very quick question - does the IMAP proxy have a minimum version of Python that it needs to work? Thinking about Python 2 here...

Thanks!

**Comment by simonrob** [comment]
Both of these answers are already listed at the end of [this section](https://github.com/simonrob/email-oauth2-proxy?tab=readme-ov-file#advanced-configuration) in the readme. This is perhaps not the best place for that information, but lots of things got moved in the reconfiguration around adding to PyPI. I may tidy this up a bit at some point.
