### ISSUE TITLE
Question: Anyone tried to recieve "Authorisation requests" into a monitoring tool?

### ISSUE THREAD

**Issue by strikegun79** [simonrob/email-oauth2-proxy#250]
Hello,
we are using zabbix as monitoring tool and would like to monitor the email proxy authorisation requests.
The log file are full of success messages and we don't see any log level switch for linux systems.

Or is it possible to write a plugin to send an echo to a logfile, if a request is prompted?

Thanks for any ideas.

**Comment by simonrob** [comment]
Could you clarify what sort of output you are hoping to see in the log files? E.g., failed as well as successful authentication requests?

The only current log level switch is to enable full log output (via `--debug`), which causes the log to contain all communication between the client, proxy and server (as well as the proxy's own relatively minimal messages).

**Comment by simonrob** [comment]
At the moment there are three types of log messages used: DEBUG (toggled by `--debug` at startup or while running by sending `SIGUSR1`), INFO and ERROR. If debug mode is not enabled the log output level is set to INFO, but your log parser can of course choose to ignore these and just receive ERROR-level messages.

The original reason for not using WARNING-level messages was the proxy's support for multiple platforms. For macOS in particular, there are [limitations around log levels](https://github.com/simonrob/email-oauth2-proxy/blob/c7094a56114ac7ca77acc68ec27b18f1dd1e24c2/emailproxy.py#L297) when using syslog. Login prompts could potentially be sent as WARNING-level messages to differentiate them from other outputs, I suppose. I'm not sure whether this would make much difference, though – there really aren't many INFO message types at the moment, and if you filtered out `Accepting new connection from [...]` and `Successfully authenticated [...]` you'd be left with little else except login prompts.

To be honest, I'm not quite sure why this is an issue. I'd expect login prompts to happen very infrequently – something approaching an annual basis or even less often is pretty typical. If you're using a setup where high uptime is a necessity and even this is not acceptable, it's better to use one of the non-interactive authentication methods such as [O365 CCG/ROPCG](https://github.com/simonrob/email-oauth2-proxy/blob/c7094a56114ac7ca77acc68ec27b18f1dd1e24c2/emailproxy.config#L126) or a [Gmail Service Account](https://github.com/simonrob/email-oauth2-proxy/blob/c7094a56114ac7ca77acc68ec27b18f1dd1e24c2/emailproxy.config#L144) to avoid the need for any manual intervention.

Re: saving tokens in the configuration file, see the [`--cache-store`](https://github.com/simonrob/email-oauth2-proxy?tab=readme-ov-file#optional-arguments-and-configuration) option. To reload the configuration while running, [send `SIGHUP`](https://github.com/simonrob/email-oauth2-proxy/blob/c7094a56114ac7ca77acc68ec27b18f1dd1e24c2/emailproxy.config#L6).

**Comment by simonrob** [comment]
I'm going to assume that you used one of the suggested alternatives to answer this question, so am closing this issue. Feel free to reopen if needed.
