### ISSUE TITLE
Eudora 7 Unable to Authorize gmail Acct

### ISSUE THREAD

**Issue by freddy3333** [simonrob/email-oauth2-proxy#252]
After modifying the emailproxy.config file with my gmail acct and server info, replacing the default ports with the ones I've been using in Eudora for the past few years, when I attempt to download mail from gmail, instead of an Authorization pop-up, Eudora outputs one of these errors:

_SSL Negotiation Failed: Unknown Error
The connection with the server has been lost._

_Logging into POP Server, PASS
There has been an error transferring your mail. I said: PASS and then the POP server said: ERR [AUTH] Application-specific password required: https://support.google.com/accounts/answer/185833_

Since the email proxy never pops-up an Authorization prompt and the Activity Data indicates "never" next to my email address, I suspect something is still misconfigured.

Two specific things that may be relevant:
1) I'm a bit confused about how to generate or acquire the "client_id" and "client_secret"?
I did follow these instructions (https://developers.google.com/identity/protocols/oauth2/native-app) to create the two client values, then I added them to the config file. But I got kind of lost on google's client generator tool, so I may've done something wrong. Still, I do have both values saved in a text file.

2) I'm also confused about which ports to use for gmail?
In addition to the ports I've been using, I also tried the default gmail ports (2993, 2995 & 2465) indicated in the sample emailproxy.config as well as many others above ports 1023 and below 65536....none of which seemed to make a difference.

Screenshots of the port settings and my Eudora settings:
![ports2](https://github.com/simonrob/email-oauth2-proxy/assets/96801973/2e5cf282-a23c-4e16-aa38-0f9d30a6a8bb)

![ports](https://github.com/simonrob/email-oauth2-proxy/assets/96801973/464cb868-fe2b-4d7a-8c7c-9e394e8ee925)
![settings](https://github.com/simonrob/email-oauth2-proxy/assets/96801973/9e6e3d90-5f72-4cd9-9e44-a30298554618)
![settings2](https://github.com/simonrob/email-oauth2-proxy/assets/96801973/09299ef1-88cd-4c8d-aa81-1dc0313b26e9)

**Comment by simonrob** [comment]
Your POP and SMTP servers are configured to be the default Gmail ones. This needs to be changed to `localhost` so that your email client connects to the proxy, rather than direct to Gmail. Related to this, one thing you haven't posted is the log file showing the proxy's output. This is a key element in troubleshooting – see the [proxy's readme](https://github.com/simonrob/email-oauth2-proxy#troubleshooting) for more details and tips.

Since you mentioned changing various settings in frustration and may just have forgotten to revert these, it's worth mentioning that I remember a [previous Eudora issue](https://github.com/simonrob/email-oauth2-proxy/issues/34) that turned out to be it [not respecting the ports configured in its settings screens](https://github.com/simonrob/email-oauth2-proxy/issues/34#issuecomment-1179711487). If you still have problems after changing the server settings it's probably worth reading through that entire issue to see whether there are any similarities. Regardless, the settings screenshot you've posted shows the standard Gmail ports, which is not what the proxy uses by default.

You also posted a screenshot of the proxy's dropdown menu, showing that you've configured new ports below 1,024. This is supported, but you need to make sure this doesn't require extra administrative permissions. It's possible for the proxy to be told by the Operating System that it has succeed in opening a port in this range when in reality it has failed due to the lack of permissions. So, it's safest to use ports above 1,024.

**Comment by freddy3333** [comment]
Thanks Simon.
The only things I've changed are the ports and my account settings, all of which I took screenshots of BEFORE making any changes, so I was easily able to backtrack my work.

I just changed the ports to 2993, 2995 & 2587 and tried again, but still no go. However, when checking the SSL certificates, I see that the server setting is still pop.gmail.com & the port setting is still 995! I restarted Eudora and checked the port and server settings in Eudora's Settings and they're set correctly. So I don't know why they're still showing the old settings in the SSL section??

Attached is a zipped copy of the log.
Thanks again, Simon!

[emailproxy.zip](https://github.com/simonrob/email-oauth2-proxy/files/15475554/emailproxy.zip)
![settings2](https://github.com/simonrob/email-oauth2-proxy/assets/96801973/32955294-6ad3-4e22-8f9a-bfe438df9ae9)
![settings](https://github.com/simonrob/email-oauth2-proxy/assets/96801973/7bd1efab-fbae-49aa-bfe5-78cc01fca2f4)
![portsnew](https://github.com/simonrob/email-oauth2-proxy/assets/96801973/eede6103-681c-442e-8dc3-55337a806538)
![dominant error](https://github.com/simonrob/email-oauth2-proxy/assets/96801973/35010a70-b16b-48e6-8d64-bd99bdab0244)
![ssl 995](https://github.com/simonrob/email-oauth2-proxy/assets/96801973/56f7ddbc-4c69-4f1b-b436-3397f8e1fbac)

**Comment by simonrob** [comment]
See [this comment in the other issue I referenced previously](https://github.com/simonrob/email-oauth2-proxy/issues/34#issuecomment-1179711487) – it talks about oddities in settings and workarounds for them.

The zip file you posted is empty/invalid...

**Comment by freddy3333** [comment]
Not sure why the zip failed, but here's another that I just tested OK.
[emailproxy.zip](https://github.com/simonrob/email-oauth2-proxy/files/15482452/emailproxy.zip)

**Comment by freddy3333** [comment]
> See [this comment in the other issue I referenced previously](https://github.com/simonrob/email-oauth2-proxy/issues/34#issuecomment-1179711487) – it talks about oddities in settings and workarounds for them.

I'm not sure I understand how chupocro's post relates to solving my issue?? Is my problem related to IMAP (which I don't use)?

**Comment by simonrob** [comment]
Thanks for the fixed log file. This shows some strange connection behaviour – lots of failures that are ignored by the proxy due to one of the errors caught in [this method](https://github.com/simonrob/pyasyncore/blob/9b5e373f43761b0d9c4c9995597aab99a6507f93/asyncore/__init__.py#L342). If you're happy modifying the code, it would be worth making that method raise the exceptions instead of handling them just so you can see a bit more about what is actually happening. (Since it is in the `asyncore` package, you may need to override it in the proxy instead).

Re: the older issue – I know very little about Eudora, but wondered whether the same settings idiosyncrasies applied to POP/SMTP. The other thing is that (as discussed in that issue) Eudora is very old software, and could simply not be compatible – this may be the reason for the connection failures. But there are various workarounds discussed there that may well be useful.

**Comment by freddy3333** [comment]
Simon, I'm sorry, but I've no idea what asyncore is (I'm not a developer), but I'd give it a go if there are specific instructions (for non-developers) somewhere.

Older issue? The only issue I have is getting Eudora to work with gmail's OAuth2.

**Comment by GAllen27** [comment]
Eudora works fine with this proxy.  I've been using the Windows compiled version with O365 email OAuth2 requirement for almost a year now.  A *huge* thank-you to Simon!!!

**Comment by freddy3333** [comment]
> Eudora works fine with this proxy. I've been using the Windows compiled version with O365 email OAuth2 requirement for almost a year now. A _huge_ thank-you to Simon!!!

Thanks for your input!
Based on what I've read, it seems you're not alone in getting it to work with Eudora. Any tips on how you got it to work? Or, did it work out-of-the-box after configuring your O365 login credentials?

**Comment by GAllen27** [comment]
It's all in the config, for both OAuth2Proxy and Eudora.  There is a Eudora OAuth2 Proxy howto writeup for O365 that is long; I posted it here: 
https://drive.google.com/file/d/1mrZIyz34WD3UmyvnrOvXovt0blXlzSTa/view?usp=sharing
GMail would be a bit different, but I can't help you there.

**Comment by freddy3333** [comment]
Many thanks for this! While the puzzle's not been solved yet, I feel like we're nailing down some of the variables I've been concerned/confused about..

> It's all in the config, for both OAuth2Proxy and Eudora. There is a Eudora OAuth2 Proxy howto writeup for O365 that is long; I posted it here: https://drive.google.com/file/d/1mrZIyz34WD3UmyvnrOvXovt0blXlzSTa/view?usp=sharing GMail would be a bit different, but I can't help you there.

I see you used the same ports I'd originally used—995 and 587 (and deleted the IMAP section, which I've never used, so I deleted it as well), but set the bracketed numbers as [POP-1995] and [SMTP-1587]. So I reset both Eudora and my emailproxy.config to match your ports (which were the ones I started with and've been using to access gmail for years).

I already had set SSL "Secure Sockets = never", so I'm good there. Otherwise, other than those settings that're particular to O365 vs gmail and my unique "client" codes (which I'm still a bit confused about....so that may be an issue by itself??), I think my Eudora and emailproxy.config settings now match yours. But I'm still NOT getting the authorization prompt and continue to get these bloody connection errors when attempting to login/download email from gmail. Because the error cites "localhost" (with similar results when I change that to "128.0.0.1"), I'm guessing the bottleneck is occurring between Eudora and Simon's proxy???
![995 connection refused 2](https://github.com/simonrob/email-oauth2-proxy/assets/96801973/50411bc5-bc91-4631-bd52-0c7a4265dace)



![995 connection refused](https://github.com/simonrob/email-oauth2-proxy/assets/96801973/6be9d66e-833b-4cf4-bc4e-328cb0dd10bd)

**Comment by freddy3333** [comment]
> It's all in the config, for both OAuth2Proxy and Eudora. There is a Eudora OAuth2 Proxy howto writeup for O365 that is long; I posted it here: https://drive.google.com/file/d/1mrZIyz34WD3UmyvnrOvXovt0blXlzSTa/view?usp=sharing GMail would be a bit different, but I can't help you there.

I just noticed that, rather than "localhost" as the Eudora POP server setting, you used the outlook.office365.com POP server, which is what I'd originally used (tho', in my case, it was pop.gmail.com). So I tried resetting that back as well...

Unfortunately, it still fails, but Eudora's yin/yang activity icon spun for much longer before popping-up a new/different error:
![connection timed out](https://github.com/simonrob/email-oauth2-proxy/assets/96801973/09746f20-3c34-412a-8077-cc699a0c9eb7)

**Comment by freddy3333** [comment]
Still not prompted to Authorize or able to access gmail, but I clicked 'Yes' to the SSL Certificate and got another new error that contains "PASS". Headway??
![pass error](https://github.com/simonrob/email-oauth2-proxy/assets/96801973/b71bb1f1-d6cf-4f7b-a422-461635452a54)

![Server SSL Certificate Reject](https://github.com/simonrob/email-oauth2-proxy/assets/96801973/7c4affea-1dba-479b-9513-be474dce1ac6)

**Comment by freddy3333** [comment]
Here's a new log file (checked/working)..
[emailproxy.zip](https://github.com/simonrob/email-oauth2-proxy/files/15492981/emailproxy.zip)

**Comment by freddy3333** [comment]
I apologize for being that guy who keeps posting, but since the author of the article GAllen27 got Eudora working, I started over and followed the entire procedure in the section "HOW TO CONFIGURE EMAIL-OAUTH2-PROXY AND EUDORA" from the "Eudora OAuth2 Proxy howto writeup for O365" that GAllen27 posted above.

After following those steps, here's what I did:
1) Configured the emailproxy.config as per the defaults for gmail—SMTP 465, POP 995
2) Configured Eudora as per the section "HOW TO CONFIGURE EMAIL-OAUTH2-PROXY AND EUDORA", with the same port assignments
3) I configured my local Windows firewall to TRUST and permit unfettered network access for "emailproxy.exe"
4) I renamed the original emailproxy.log (so the next run will create a new/shorter log reflecting my result following GAllen27's posted guide)
5) I ran emailproxy.exe as Adminstrator (to eliminate any Windows user permission issue) and enabled **Debug mode**
6) I opened Eudora and attempted to Check for mail...."localhost" connection refused.
6a) On a hunch, I closed both emailproxy and Eudora....then, I opened ONLY Eudora and attempted to Check for mail—same error I got with the proxy running: "localhost" connection refused.

Here's the contents of the new emailproxy.log:
2024-05-30 00:50:58,734: Running in a packaged/frozen environment - imported SSL certificates from `certifi`
2024-05-30 00:50:58,844: Initialising Email OAuth 2.0 Proxy (version 2024-05-25) from config file C:\Users\dt\Desktop\emailproxy-2024-05-25_pyinstaller-Windows\emailproxy.config
2024-05-30 00:50:58,844: Starting POP server at 127.0.0.1:2995 (unsecured) proxying pop.gmail.com:995 (SSL/TLS)
2024-05-30 00:50:58,859: Starting SMTP server at 127.0.0.1:2465 (unsecured) proxying smtp.gmail.com:465 (SSL/TLS)
2024-05-30 00:50:58,859: Initialised Email OAuth 2.0 Proxy - listening for authentication requests. Connect your email client to begin
2024-05-30 00:51:03,907: Setting debug mode: True
2024-05-30 00:51:43,849: Stopping Email OAuth 2.0 Proxy
2024-05-30 00:51:43,958: Stopping POP server at 127.0.0.1:2995 (unsecured) proxying pop.gmail.com:995 (SSL/TLS)
2024-05-30 00:51:43,958: Stopping SMTP server at 127.0.0.1:2465 (unsecured) proxying smtp.gmail.com:465 (SSL/TLS)


So, since Eudora's "localhost" connection is refused regardless of whether the emailproxy is running or not, my gut says the problem is that Eudora's NOT communicating either with "localhost" or the emailproxy. Does that spark any thoughts???

![1](https://github.com/simonrob/email-oauth2-proxy/assets/96801973/4e34eb91-0096-4496-8c34-a6ed7e6a49fd)
![1a](https://github.com/simonrob/email-oauth2-proxy/assets/96801973/1342cc60-924d-4ff9-816c-0201c98f7eeb)
![1b](https://github.com/simonrob/email-oauth2-proxy/assets/96801973/dccacfd3-a09c-422a-9859-d117d11ef0a4)
![1c](https://github.com/simonrob/email-oauth2-proxy/assets/96801973/dbac60ca-39e5-4ff6-81af-80c062f4f721)

**Comment by freddy3333** [comment]
Late Update for tonight..(promise!)
1) I changed the ports in both Eudora and the emailproxy.config to 1995 & 1465 and closed both Eudora and the emailproxy.
2) Then, I ran the emailproxy and enabled the Debug log
3) Opened Eudora and attempted to Check for mail...
![2](https://github.com/simonrob/email-oauth2-proxy/assets/96801973/43bbc081-10ac-4fd7-9f49-7700816f6e6e)

Here's the debug log:
2024-05-30 01:10:35,750: Running in a packaged/frozen environment - imported SSL certificates from `certifi`
2024-05-30 01:10:35,859: Initialising Email OAuth 2.0 Proxy (version 2024-05-25) from config file C:\Users\dt\Desktop\emailproxy-2024-05-25_pyinstaller-Windows\emailproxy.config
2024-05-30 01:10:35,861: Starting POP server at 127.0.0.1:2995 (unsecured) proxying pop.gmail.com:2995 (SSL/TLS)
2024-05-30 01:10:35,869: Starting SMTP server at 127.0.0.1:2465 (unsecured) proxying smtp.gmail.com:2465 (SSL/TLS)
2024-05-30 01:10:35,875: Initialised Email OAuth 2.0 Proxy - listening for authentication requests. Connect your email client to begin
2024-05-30 01:10:39,552: Setting debug mode: True
2024-05-30 01:10:54,261: New incoming connection to POP server at 127.0.0.1:2995 (unsecured) proxying pop.gmail.com:2995 (SSL/TLS)
2024-05-30 01:10:54,261: Accepting new connection from 127.0.0.1:57280 to POP server at 127.0.0.1:2995 (unsecured) proxying pop.gmail.com:2995 (SSL/TLS)
2024-05-30 01:11:15,299: POP (127.0.0.1:57280-{127.0.0.1:2995}-pop.gmail.com:2995) <-- [ Server disconnected ]
2024-05-30 01:11:15,300: POP (127.0.0.1:57280-{127.0.0.1:2995}-pop.gmail.com:2995) --> [ Client disconnected ]

If I'm reading the debug log correctly, it looks like all goes well until the emailproxy attempts to connect to gmail, at which point it  (and Eudora) gets "disconnected". Does that point to the source of the problem....or the fix?

Sorry for mucking about so much...and thanks for your input!

**Comment by freddy3333** [comment]
**Update:** Good & Not so good news.

**The Good:** Receiving **fixed** by setting BOTH POP ports in the emailproxy.config and the ports in Eudora to **995**.

**For others having the same issue:** The problem is that, in the instructions, the ports in brackets in emailproxy.config are 4-digit (e.g., 2995), whilst the ports in the body of the config are 3-digit (e.g., 995). The key is that all of the ports MUST be _exactly_ the same:
[POP-**995**]
server_address = pop.gmail.com
server_port = **995**
local_address = 127.0.0.1

[SMTP-**465**]
server_address = smtp.gmail.com
server_port = **465**
local_address = 127.0.0.1

Once matched, when I attempted to **Check for email**, the Authorization screen popped-up instantly, I entered my login password and code (texted to me as per gmail's 2-part authentication) and my email downloaded just like normal!
**Receiving problem solved!**


**The Not so good:** Unfortunately, although I did the same for BOTH SMTP ports (tried 465, 587, 1465, 1587, 2465 & 2587), sending returns a new error (tho' the proxy status screen now indicates my successful account authentication a few minutes ago!):
![ports](https://github.com/simonrob/email-oauth2-proxy/assets/96801973/f4fb7d12-19ce-4566-ba8c-d1baaf6fe21f)

In tandem with this error, The **Send** button in Eudora has been replaced with a **Queue for delivery** button and clicking the button just adds another copy of the same [unsent] message to the queue:
![Queue for delivery](https://github.com/simonrob/email-oauth2-proxy/assets/96801973/a01d69f9-5626-46fe-bbcc-3bd45f0dd778)

Here's a new (zipped and checked OK) debug log..
[emailproxy.zip](https://github.com/user-attachments/files/15506777/emailproxy.zip)

**Comment by simonrob** [comment]
Thanks for following up, and for the kind words. Once you have things working, they will continue to work unless something in your configuration changes. But either way it sounds like you now know how to set this up. It's also useful to have this here for others, so thanks for documenting so thoroughly the various things you tried.

Just to follow up on your point above about the proxy's configuration instructions: the sample file is indeed correct in stating `1995` rather than `995` for the local port, for all of the reasons [explained in its documentation](https://github.com/simonrob/email-oauth2-proxy/blob/d7f259bb3a536daa83209c5b89dd5e42a6127e4b/emailproxy.config#L12). But it does sound like this is something Eudora can't cope with, so I'll point back to this issue in future if other people mention issues with that client.

I'll close this issue for now because it sounds like everything has been resolved, but feel free to reopen if things change.

**Comment by freddy3333** [comment]
Simon, since installing the proxy, my Windows User temp folder's filling with a growing number of _MEIXXXXX (X=numbers) folders containing more folders/files that appear to be Microsoft Runtime and/or python-related. I was unable to delete them, so I engaged an Unlocker utility that identified the files/folders with emailproxy before deleting them.....which appeared to cause the proxy to close (i.e., the icon vanished from the Windows taskbar!).

Two questions:
1) What're the _MEI folders for?
2) Is there a way to run the emailproxy without creating all of these _MEI folders?

Here's a screenshot of the _MEI folders:
![_MEI 1](https://github.com/simonrob/email-oauth2-proxy/assets/96801973/56ff5912-b235-4195-b55a-c8fdda81fef1)

Here's the contents of one _MEI folder:
![_MEI 2](https://github.com/simonrob/email-oauth2-proxy/assets/96801973/7fb950a8-a22f-4a31-b8a9-defc7b92953f)

Here's some of the many files in on _MEI folder:
![_MEI 3](https://github.com/simonrob/email-oauth2-proxy/assets/96801973/38cba00d-9358-427f-8575-c97f72725333)

Here's the Unlocker utility identifying the _MEI folders with the emailproxy. As soon as I had it delete the folders, the proxy icon in the Windows taskbar vanished:
![_MEI 4](https://github.com/simonrob/email-oauth2-proxy/assets/96801973/968528f5-d3f5-430b-bf80-54ab7c2e5890)

**Comment by simonrob** [comment]
These folders are not created by the proxy itself, but are related to PyInstaller, which is used to bundle the proxy script into an executable app for people who can't/won't run it directly with Python. If you use the bundled Windows (or macOS) app, it is not possible to prevent these files/folders being created.

I'm not sure why you're concerned about this – after all, they're in a temporary folder that the Operating System manages. But if it's an issue (for example, they're not being cleaned up), you can raise it on the [PyInstaller project](https://github.com/pyinstaller/pyinstaller).

**Comment by GAllen27** [comment]
Simon wrote:
<<Just to follow up on your point above about the proxy's configuration instructions: the sample file is indeed correct in stating `1995` rather than `995` for the local port, for all of the reasons [explained in its documentation]. But it does sound like this is something Eudora can't cope with, so I'll point back to this issue in future if other people mention issues with that client.>>

Eudora has no problem with port 1995 and the OAuth2 proxy.  Here is my Eudora.ini port setup for O365 email with the proxy [I use the compiled Windows version, no Python installation):

[Settings]
;For sending outlook mail:
SmtpAuthAllowed=1
SMTPServer=localhost
SMTPPort=1587
SSLSendUse=0

;For receiving outlook mail using POP:
UsesPOP=1
PopServer=localhost
POPPort=1995
SSLReceiveUse=0
AuthenticatePassword=1

UseSubmissionPort=0
_________________________________
So as freddy3333 said, it is pilot error, not problems with the proxy.  Setup can be complicated however ... the nature of the beast.

**Comment by freddy3333** [comment]
> Simon wrote: <<Just to follow up on your point above about the proxy's configuration instructions: the sample file is indeed correct in stating `1995` rather than `995` for the local port, for all of the reasons [explained in its documentation]. But it does sound like this is something Eudora can't cope with, so I'll point back to this issue in future if other people mention issues with that client.>>
> 
> Eudora has no problem with port 1995 and the OAuth2 proxy. Here is my Eudora.ini port setup for O365 email with the proxy [I use the compiled Windows version, no Python installation):
> 
> [Settings] ;For sending outlook mail: SmtpAuthAllowed=1 SMTPServer=localhost SMTPPort=1587 SSLSendUse=0
> 
> ;For receiving outlook mail using POP: UsesPOP=1 PopServer=localhost POPPort=1995 SSLReceiveUse=0 AuthenticatePassword=1
> 
> UseSubmissionPort=0
> 
> So as freddy3333 said, it is pilot error, not problems with the proxy. Setup can be complicated however ... the nature of the beast.

The pilot error was related to the two Eudora settings in my previous post, not the overall problems I've had getting the proxy to work. The port issue, at least in my (gmail?) case was due to having a four-digit port assignment in the [] section and a three-digit port assignment below that. Since the proxy's working with all three-digit port assignments, I've no reason to experiment further with all four-digit ports, but I reckon they'd work as long as both the [] port and the one below that are exactly the same—both either three- or four-digit.
But, again, I appreciate your input!

**Comment by freddy3333** [comment]
> These folders are not created by the proxy itself, but are related to PyInstaller, which is used to bundle the proxy script into an executable app for people who can't/won't run it directly with Python. If you use the bundled Windows (or macOS) app, it is not possible to prevent these files/folders being created.
> 
> I'm not sure why you're concerned about this – after all, they're in a temporary folder that the Operating System manages. But if it's an issue (for example, they're not being cleaned up), you can raise it on the [PyInstaller project](https://github.com/pyinstaller/pyinstaller).

For security (and space) reasons, I've always had Windows clear its temp files/folders when rebooting/shutting down. Prior to installing the emailproxy, that process never took more than a handful of seconds to complete. Now, it takes several minutes....and it was in the process of diagnosing the unusually slow shutdowns that I discovered those folders, It may not technically be a problem, per se, but I don't think I've ever seen another Windows process that regularly generates that much temp data.

**Re the PyInstaller project:** A current thread, [**Regression with delete _MEI in 6.7.0 (working 5.3)**](https://github.com/pyinstaller/pyinstaller/issues/8571), looks to be addressing this very issue. However, it looks like they're all developers and I don't really follow what they're doing?
