### ISSUE TITLE
Support for Synology Nas or Docker?

### ISSUE THREAD

**Issue by shinomen** [simonrob/email-oauth2-proxy#253]
I love this utility.  It's very simple and fills a huge need of being able to accept email from our different types of printers and relaying it over oauth.  What I would like to see is if you all could come up with a way for this utility to run under a Synology NAS as an App/Package or maybe under a docker container so that it can run from the Synology NAS.

**Comment by simonrob** [comment]
Thanks for the suggestions (and the kind words). I can't help with Synology Nas, but there is a [Docker example here](https://github.com/blacktirion/email-oauth2-proxy-docker) that is kindly maintained by an external contributor. This and more are linked [at the end of the proxy's readme](https://github.com/simonrob/email-oauth2-proxy#related-projects-and-alternatives).
