### ISSUE TITLE
Trying on Ubuntu - No Menu Response

### ISSUE THREAD

**Issue by whitedavidp** [simonrob/email-oauth2-proxy#260]
I decided to try running the proxy on an Ubuntu server I have running in a virtualbox. I had it running and reading the config file. I can connect to it and can see on the console that I should use the menu to authorize. I see the menu but I cannot seem to open it or get it to respond in any way - to any kind of click. Rats!

**Comment by simonrob** [comment]
The GUI can be [a little more tricky to set up](https://github.com/simonrob/email-oauth2-proxy?tab=readme-ov-file#dependencies-and-setup) on Linux systems. I'd recommend trying the `--no-gui` option first.

**Comment by whitedavidp** [comment]
I cannot thank you enough for this project and for all of your help in getting me up and going. This is just fantastic!
