### ISSUE TITLE
Change to Sample Config Possibly Needed

### ISSUE THREAD

**Issue by whitedavidp** [simonrob/email-oauth2-proxy#261]
I just found myself having troubles with my 1st SMTP send to outlook. I looked in my config file - copied and edited from the sample. It shows the following hostname: outlook.office365.com. This does not match what is shown [here](https://support.microsoft.com/en-us/office/pop-imap-and-smtp-settings-for-outlook-com-d088b986-291d-42b8-9564-9c414e2aa040) (and what I have set up in my email client): smtp-mail.outlook.com. I do not know if this applies to everyone. Mine is a normal, personal-use Outlook account (previously Hotmail).

Best

**Comment by simonrob** [comment]
The sample file actually gives [`smtp.office365.com`](https://github.com/simonrob/email-oauth2-proxy/blob/48773b086b5b9df70439ba251946dfa0a86ce5c4/emailproxy.config#L62C1-L62C36) as the SMTP server. Perhaps you mistakenly copied from the IMAP or POP entries?

This server definitely does work, but you're correct that Microsoft have updated their guidance. I suspect this is fairly recent – Thunderbird [still uses the old server](https://github.com/mozilla/releases-comm-central/blob/812b7c9068ca5cac0580b0ddbea8e34c141cd441/mailnews/base/src/OAuth2Providers.jsm#L57), for instance.

23d3b4a updates this and also adds another account example specifically for Outlook accounts given your experience with scope values. Thanks for the pointers here.
