### ISSUE TITLE
Can I PayPal a Donation?

### ISSUE THREAD

**Issue by whitedavidp** [simonrob/email-oauth2-proxy#262]
The proxy is killer good and your support worthy of praise. I'd rather not give my personal data and donate via GitHub. Is there a way I can donate by sending money via PayPal? Thanks

**Comment by simonrob** [comment]
Thanks for the kind words and offer - I typically use the sponsors feature here for ease, but you can also use my GitHub username @gmail.com for PayPal.

**Comment by whitedavidp** [comment]
Thanks. Just sent...

**Comment by simonrob** [comment]
Thank you – always great to hear this tool is useful for others.
