### ISSUE TITLE
How do I get my client ID / secret for a regular Outlook (Hotmail) account?

### ISSUE THREAD

**Issue by bkimmett** [simonrob/email-oauth2-proxy#263]
I am trying to set up your proxy for regular Outlook (_not_ Outlook 365), so I can continue using my old Hotmail account with POP in Apple Mail. I am ready to run the proxy, but need to give it my client ID and client secret. How can I acquire these (preferably without installing Thunderbird, etc?)

I am not a business user and do not have access to Azure.

**Comment by bkimmett** [comment]
I apologize, but there is no documentation for regular Outlook accounts in the subsection on "If you do not have access to credentials for an existing client you will need to register your own." The instructions for Outlook 365 do not work as I cannot register a new identity application without an Azure account, which I do not have since I am not a business user.

Additionally, if possible, I do not want to have to install an additional email program.

Additionally, I have examined the sample configuration file and have come upon that example (and used it in my own config file) - I am only missing the client_id and client_secret.

**Comment by simonrob** [comment]
The section before that beginning "If this is not possible, you can also reuse the client ID and secret from any email client" has links to several examples.

**Comment by bkimmett** [comment]
Ah. So there's no way for me to get my client ID and secret directly from Microsoft? I see, thank you.
