### ISSUE TITLE
Proxy listening on another localhost address

### ISSUE THREAD

**Issue by Mijzelf** [simonrob/email-oauth2-proxy#269]
Is is possible to let the proxy listen on 127.0.0.2 instead of 127.0.0.1? When I specify that in emailproxy.config and start emailproxy, it just listens on 127.0.0.1 and changes the specification in the config file.

To test if somehow 127.0.0.2 is invalid, I tried with netcat (using the same credentials as emailproxy):
`netcat -l 127.0.0.2 1024`
and that worked. Using telnet I can connect to 127.0.0.2:1024, but not to 127.0.0.1:1024

Reading through emailproxy.py I cannot find where 127.0.0.1 is enforced.

**Comment by simonrob** [comment]
Did you read [the configuration documentation](https://github.com/simonrob/email-oauth2-proxy/blob/32865aefb2cf9be2d8e28171d8f89c016592958f/emailproxy.config#L32)?

Set `local_address = 127.0.0.2` and the proxy will listen on the IP address you are wanting.
