### ISSUE TITLE
Crashes on Linux in Log class

### ISSUE THREAD

**Issue by andyboeh** [simonrob/email-oauth2-proxy#27]
It crashes for me on my headless Linux server because the Log class tries to access `pyoslog.is_supported()` while the corresponding import is only called on `darwin`. This was introduced by line 130 in [a9d8923533f0c119eeb0b00a7875aed862d72736](https://github.com/simonrob/email-oauth2-proxy/commit/a9d8923533f0c119eeb0b00a7875aed862d72736).

I also suggest adding a try - except block around the pystray import, as I'm on a system where the `dummy` backend is broken.

Edit: This doesn't work. RetinaIcon requires pystray to be loaded, so I'll have to fix my system.

**Comment by cacoch** [comment]
I got the same error in my box. 
` _MACOS_USE_SYSLOG = False` temporal workaround.

**Comment by simonrob** [comment]
Oops - this is a clear regression related to the recent macOS-specific improvements.

**Comment by simonrob** [comment]
Just to follow up on the comment about pystray - you could move the platform conditional that is currently [inside this class](https://github.com/simonrob/email-oauth2-proxy/blob/93e0d9b7eacaf6b0c8e9e23bbd06229cf56a0d3c/emailproxy.py#L1220) to outside, covering the whole class. With the import edit you have also made, does this let you successfully load the proxy?

**Comment by andyboeh** [comment]
The problem is that pystray.Icon is passed to the class. Python seems to parse this before actually starting the script and this is why it fails.
It was very straightforward to set up a virtualenv with pystray == 0.18.0 and this works as expected.

**Comment by simonrob** [comment]
Making the entire class conditional on pystray loading successfully would fix that, but given that you've been able to use a compatible version of pystray I think this can be left as-is for now. Glad you were able to get things working.

**Comment by simonrob** [comment]
Just to follow up - #b69c23b makes these entire classes conditional on macOS, so you should now be able to skip that import with no other issues. (Though still better I think to just install the package so no script edits are required)
