### ISSUE TITLE
PHP Fatal error:  Uncaught ErrorException: Notice: Unknown: SECURITY PROBLEM: insecure server advertised AUTH=PLAIN (errflg=1) in Unknown:0

### ISSUE THREAD

**Issue by kingofcold** [simonrob/email-oauth2-proxy#272]
Hi,

Thanks for this project.

I am trying to set up the proxy to work with uvdesk IMAP on office365 email.

However uvdesk showing,
PHP Fatal error:  Uncaught ErrorException: Notice: Unknown: SECURITY PROBLEM: insecure server advertised AUTH=PLAIN (errflg=1) in Unknown:0

As far as i understand the connection between the proxy and local host isn't encrypted, i think that's what uvdesk or PHP is complaining about.

Is there any workaround for this issue or any suggestions i can try?

**Comment by simonrob** [comment]
Please see the [Getting started section of the readme](https://github.com/simonrob/email-oauth2-proxy?tab=readme-ov-file#getting-started) and the [sample configuration file](https://github.com/simonrob/email-oauth2-proxy/blob/52e729913a53dd05257ee6056670a9aa20906edf/emailproxy.config#L45) where this is explained.
