### ISSUE TITLE
Help setting up a personal Microsoft live.com account

### ISSUE THREAD

**Issue by Rick-G1** [simonrob/email-oauth2-proxy#274]
Hi: 

Please forgive me as this web interface and OAuth2 stuff is very new to me.  I finally got to configure and run the precompiled Windows version of emailproxy.  Since Microsoft is removing non OAUTH2 log ins as of Sept 15, it would sure be nice to get this working, but I'm having problems getting it to work with my live.com (Microsoft) account.  I have no business account and don't want to pay for Azure products.

So far I've logged into Azure and created a ClientID and ClientSecret, put them into the emailproxy.config file, along with modifying the config file in the [account setup] section for [your.office365.address@example.com] (now [xxxxme.live.com]) 
I've also modified Outlook 2007 to using my live.com email address and the proxy server settings (127.0.0.1) as the "incoming" and "outgoing" server with the new port numbers (1995 and 1587).  When I do a "Send/Receive" in Outlook, I get a message that authorisation is needed, so I goto "Authorise account and the Live account that appears there and enter name/password. The next thing that happens is I get a window that says "Were unable to complete your request" and a mention that the redirect_uri is not valid (see Azure0.jpg)

So then after going to Azure and selecting View "Entra ID", I get 5 pop ups that say it couldn't get access tokens (Azure1.jpg), so I click "ignore" for each one. Then I click "add" and "App Registration" and fill out the info and get an ID (Azure2.jpg, Azure3.jpg).   I then fill out or review "Authentications" and "API permissions" (Azure4.jpg, Azure5.jpg) and all looks ok except I don't know what to fill in for redirect_uri.  This was setup during creating the ID with "WEB" and checking the box  
"Accounts in any organizational directory (Any Microsoft Entra ID tenant - Multitenant) and personal Microsoft accounts"
(Note: I followed "https://support.heateor.com/how-to-get-windows-live-client-id-and-client-secret-key/" to generate the ClientID and ClientSecret and then copied them into the emailproxy.config file. 

When I run it with debug on and ask to get mail, the emailproxy log file reveals that it looks like it's starting to negotiate a connection, but fails.   Log live.log attached. 

If you or one of the other owners of this repository can help, I'd sure appreciate it.  As I said last time, I'm retired so once I figure this out I could take time to document the proper setup for this very basic use of your program so that hopefully others don't have to bother you with this.  

I also have a couple of gmail accounts, but they use app passwords for now, and that works fine for the time being. Eventually I'll change these over too, but there isn't the rush there is for this Microsoft account that needs to be done by Sept 15th. 

Thank you, 
Rick Groome
![Azure0](https://github.com/user-attachments/assets/ba4673c0-8ab1-4031-8bd4-f30b2fc0f7c4)
![Azure1](https://github.com/user-attachments/assets/2badda13-71b0-44c7-9152-374773a002aa)
![Azure2](https://github.com/user-attachments/assets/41aa547e-b0a3-4e95-8404-5de56ee1e9f2)
![Azure3](https://github.com/user-attachments/assets/707c97a6-9a06-4f8b-9401-7a933d3ad460)
![Azure4](https://github.com/user-attachments/assets/68ec6980-4df9-4c95-8601-40b107e91647)
![Azure5](https://github.com/user-attachments/assets/6473aabf-c203-433a-a66e-33a448aed6bd)
[Live.log](https://github.com/user-attachments/files/16741933/Live.log)

**Comment by simonrob** [comment]
It's unlikely you'll be able to get this working with a free account and an Entra ID configuration you've created yourself. I'd recommend using [this](https://github.com/simonrob/email-oauth2-proxy/blob/4e1dfd80fbf92bd48ff804bac163efa4b8af9d74/emailproxy.config#L202) configuration and reading through other issues where people have got this working (#259, for example)
