### ISSUE TITLE
local_port in config file

### ISSUE THREAD

**Issue by TurtleWilly** [simonrob/email-oauth2-proxy#280]
Please add a config option to specify a non-standard "local_port" in case something else is already occupying the respective port. I know it can be specified via the section heading, but this is a really confusing method to set this config option. I would prefer a clear option. The heading title should be purely informal.

**Comment by simonrob** [comment]
Ports are specified via section headings. This is not going to change, as it also ensures section names are unique, which is a requirement of the configuration file format. Since the configuration file so rarely needs to be edited, this is an acceptable trade-off.
