### ISSUE TITLE
Delete emails via IMAP

### ISSUE THREAD

**Issue by sniper9191** [simonrob/email-oauth2-proxy#282]
Thank you for this wonderful OAuth proxy.
I am using it as an OAuth proxy for IMAP to read emails from an Exchange Online mailbox.

I want to integrate this with a service desk application which reads emails from a mailbox and creates tickets based on those emails.
Once it has created the ticket, the application deletes the emails to prevent endlessly re-creating the same ticket.

May I ask if it is possible for IMAP, when used with the OAuth proxy, to delete emails in Exchange Online?
If it matters, I am using the [Client Credentials Grant](https://learn.microsoft.com/en-us/entra/identity-platform/v2-oauth2-client-creds-grant-flow) flow (to avoid any kind of interactive authorization) with the following API permissions in Entra ID - "IMAP.AccessAsApp" under the "Office 365 Exchange Online" cateorgy (this is a different category from Graph API).

**Comment by simonrob** [comment]
Thanks for the kind words. Yes – the proxy has no effect on any other IMAP features; everything that is supported by your service provider will work as normal.
