### ISSUE TITLE
Can't work out config for individual outlook account

### ISSUE THREAD

**Issue by waterwheels** [simonrob/email-oauth2-proxy#283]
I was delighted to find this project, since I have been trying to work out a way to use a dated version of apple mail that doesn't support oauth2 (though I have been testing using thunderbird as mail is not terribly configurable). I've gotten most of the way through the setup process, but when launching the microsoft authorising web view, it won't accept my email account, as it's an individual account rather than an org one. I suspect that an individual account would need different urls for `permission_url` and `token_url` (and possibly differently named scopes as well?) but I'm unfamiliar with this area and I've been having trouble working out where to dig these up.
I've tried the examples supplied:
```
[example@outlook.com]
permission_url = https://login.microsoftonline.com/common/oauth2/v2.0/authorize
token_url = https://login.microsoftonline.com/common/oauth2/v2.0/token
oauth2_scope = https://outlook.office.com/IMAP.AccessAsUser.All https://outlook.office.com/POP.AccessAsUser.All https://outlook.office.com/SMTP.Send offline_access
redirect_uri = http://localhost
client_id = <from mailnews>
client_secret = <from mailnews>
```
Which give me the above issue that I need to use an org account, not individual.

I found a [discussion of a related issue](https://stackoverflow.com/questions/43473858/connect-to-outlook-office-365-imap-using-oauth2) where they used 
```
permission_url = https://login.live.com/oauth20_authorize.srf
token_url = https://login.live.com/oauth20_token.srf
```
Using these gives the error:
```
unauthorized_client: The client does not exist or is not enabled for consumers. If you are the developer, configure a new application [thru the Azure Portal]
```
(transcribed as I can't copy paste the text)
I guess I am seeking any suggestions as to where to look for which endpoints I need to set to use individual outlook accounts. Thanks for developing this very cool tool

**Comment by simonrob** [comment]
Free Outlook/Hotmail accounts are more restricted, so you'll probably need to use an OAuth ID from an existing client. See #281 which recently discussed this, and contains example configurations that should work for you.

**Comment by simonrob** [comment]
I'll close this as I'm assuming it has been resolved.

**Comment by henriklb** [comment]
I'm in a very similar boat with trying to configure SMTP proxy for an old hotmail account. 

If feasible, consider adding hotmail(individual account, not org) to the example config. As you detailed here in https://github.com/simonrob/email-oauth2-proxy/issues/281. Perhaps it is already there but I missed it? Similarly with how to grab oauth creds from thunderbird etc. 

Either way. Thank you very much for this software

**Comment by simonrob** [comment]
Thanks for the suggestion. I won't be adding full example configurations to the configuration file because using other applications' secrets is a bit of a grey area, permission-wise. Still, the readme does link directly to a wide range of different client ID sources (with the most popular being Thunderbird), and the issue you linked to provides a sample configuration that matches the one in the proxy's example configuration file with the exception of the `https://` URI that is required for the client ID in question.
