### ISSUE TITLE
GUI not launchine

### ISSUE THREAD

**Issue by skihogo** [simonrob/email-oauth2-proxy#289]
I am still trying to launch the gui for the first time but the task/menu bar icon doesn't appear (running on MacOS 12.7.6). I have followed the dependencies and setup guide to resolve this issue but with now luck. 

when i launch emailproxy it shows that its running for a few seconds and the quits (i have monitored this in activity monitor).

Any help will be much appreciated.

**Comment by simonrob** [comment]
I'm assuming this was resolved, so will close this issue.
