### ISSUE TITLE
Viability of using on a server

### ISSUE THREAD

**Issue by bwragg** [simonrob/email-oauth2-proxy#29]
Hi,

I know this isn't an issue but wasn't sure where to post it. I just wanted to get your thoughts on the viability of using this to handle 30 x staff email accounts. 

The current setup is we use a server side web mail client (Nextcloud) that connects to 365 email accounts via IMAP. With the changes coming to 365 and Basic Auth it is all going to stop working so we are looking for ways to connect to 365 using OAuth2.

So the flow would be:

Clients Browser->Nextcloud Server(PHP Web server)->email-oauth2-proxy->365

Nextcloud Server & email-oauth2-proxy would both be running on the same Ubuntu server.

Any observations on if this is viable before I do a deep dive into this project?

Thanks,

Benjamin

**Comment by simonrob** [comment]
I'm assuming that this has now been resolved or abandoned, so am going to close this issue (but see #33 for a related discusion).

**Comment by MrNeuman** [comment]
I am actively using the proxy with roughly 12 accounts.

It works well but initial authentication to obtain tokens was not fun even with our use-case where all mailboxes are strictly for automation.

Would definitely suggest a delegation approach if feasible – in fact may revisit that myself.

**Comment by simonrob** [comment]
If this is an O365 configuration, you could use the [client credentials grant flow approach](https://learn.microsoft.com/en-us/exchange/client-developer/legacy-protocols/how-to-authenticate-an-imap-pop-smtp-application-by-using-oauth#use-client-credentials-grant-flow-to-authenticate-imap-and-pop-connections), which removes any need for interactive authorisation via the proxy. The only caveat is that SMTP is not supported by O365 in this configuration.

If that option isn't suitable then I think the discussion in #33 still applies – there are lots of potential issues to consider here, and given that the authorisation step is in most cases a one-time (or very rare) task, I think it's bearable for now.
