### ISSUE TITLE
Trouble setting up proxy with offlineimap3 client

### ISSUE THREAD

**Issue by filipe3x** [simonrob/email-oauth2-proxy#290]
Hello, I am trying to set up offlineimap3 to work with the oauth2 proxy, but I get this error.
```
$ offlineimap
OfflineIMAP 8.0.0
  Licensed under the GNU GPL v2 or any later version (with an OpenSSL exception)
imaplib2 v3.06, Python v3.8.0, OpenSSL 1.1.1  11 Sep 2018
Account sync Outlook365:
 *** Processing account Outlook365
 Establishing connection to 127.0.0.1:1993 (Outlook365-Remote)
 PLAIN authentication failed: b'AUTHENTICATE failed.'
 ERROR: All authentication types failed:
	PLAIN: b'AUTHENTICATE failed.'
 *** Finished account 'Outlook365' in 0:05
ERROR: Exceptions occurred during the run!
ERROR: offlineimap.error.OfflineImapError: All authentication types failed:
	PLAIN: b'AUTHENTICATE failed.'


Traceback:
  File "/usr/local/lib/python3.8/dist-packages/offlineimap-8.0.0-py3.8.egg/offlineimap/accounts.py", line 298, in syncrunner
    self.__sync()
  File "/usr/local/lib/python3.8/dist-packages/offlineimap-8.0.0-py3.8.egg/offlineimap/accounts.py", line 375, in __sync
    remoterepos.getfolders()
  File "/usr/local/lib/python3.8/dist-packages/offlineimap-8.0.0-py3.8.egg/offlineimap/repository/IMAP.py", line 698, in getfolders
    imapobj = self.imapserver.acquireconnection()
  File "/usr/local/lib/python3.8/dist-packages/offlineimap-8.0.0-py3.8.egg/offlineimap/imapserver.py", line 597, in acquireconnection
    self.__authn_helper(imapobj)
  File "/usr/local/lib/python3.8/dist-packages/offlineimap-8.0.0-py3.8.egg/offlineimap/imapserver.py", line 457, in __authn_helper
    raise OfflineImapError("All authentication types "
```
In [email-oauth2-proxy](https://github.com/simonrob/email-oauth2-proxy) everything seems ok:

`2024-09-30 12:18:59: Accepting new connection from 127.0.0.1:45572 to IMAP server at 127.0.0.1:1993 (unsecured) proxying outlook.office365.com:993 (SSL/TLS)`

offlineimap configuration:

```
[Repository Outlook365-Remote]
type = IMAP
remotehost = 127.0.0.1
remoteport = 1993
remoteuser = filipe.it@outlook.pt
ssl = no
folderfilter = lambda foldername: foldername in ['Receipts']
auth_mechanisms = PLAIN
remotepass = mypass
sslcacertfile = /etc/ssl/certs/ca-certificates.crt
oauth2 = true
realdelete = no
```
Should I change `auth_mechanisms` to 'OAUTH2' instead of 'PLAIN'?
Thanks in advance.

**Comment by simonrob** [comment]
Please also post the proxy configuration file you are using.

**Comment by filipe3x** [comment]
Added the important bits of the proxy configuration file above.

**Comment by simonrob** [comment]
You've changed the scope value from the example to a Graph one - I suspect this is the issue. I'd change this back to the one shown in the example configuration file (making sure your Azure / Entra client is granted permission for it).

**Comment by filipe3x** [comment]
Changed scope values to default and still the same problem. Debug errors from proxy still show the same `b'FEBF3 NO AUTHENTICATE failed.\r\n'`

Here are the list of privileges in my azure app. Let me know if I am missing something.
![Captura de ecrã 2024-10-01, às 16 31 40](https://github.com/user-attachments/assets/9e0182c6-0262-4f7f-90db-e8934116ad37)

**Comment by simonrob** [comment]
I don't have capacity to troubleshoot Azure / Entra setups, but there are plenty of guides around – [this one](https://www.emailarchitect.net/eaoauth/kb/azure_application_pop_imap_grant.aspx) was the first search result for me, and seems like a comprehensive step-by-step explanation of the process. I'd recommend following this or a similar tutorial as the setup/approval steps are especially complex and it's easy to make a simple mistake that prevents things from working.

**Comment by simonrob** [comment]
I'm assuming this was resolved, so will close this issue.
