### ISSUE TITLE
Can not authenticate after enter the full post-authentication URL

### ISSUE THREAD

**Issue by dremba** [simonrob/email-oauth2-proxy#291]
Hello,

I'm experiencing an issue with the OAuth2 proxy configuration while trying to authenticate an account. After following the authentication process and entering the full post-authentication URL, I do not receive any response, and the authentication cannot be completed. With the GUI I only get a white screen and with local server auth it doesn't work either.

2024-10-02 17:05:17: Please visit the following URL to authenticate account test@mail.test.info: https://login.microsoftonline.com/<tenant_id>/oauth2/v2.0/authorize?client_id=<client_id>&redirect_uri=http%3A%2F%2Flocalhost&scope=https%3A%2F%2Foutlook.office.com%2FIMAP.AccessAsUser.All%20https%3A%2F%2Foutlook.office.com%2FSMTP.Send%20offline_access&response_type=code&access_type=offline&login_hint=test%40mail.test.info
Copy+paste or press [↵ Return] to visit the following URL and authenticate account test@mail.test.info: https://login.microsoftonline.com/86916bbe-4baf-467c-91cd-d41df7a338bd/oauth2/v2.0/authorize?client_id=6d755298-012c-4fd0-97d2-a17234a56089&redirect_uri=http%3A%2F%2Flocalhost&scope=https%3A%2F%2Foutlook.office.com%2FIMAP.AccessAsUser.All%20https%3A%2F%2Foutlook.office.com%2FSMTP.Send%20offline_access&response_type=code&access_type=offline&login_hint=test%40m
ail.test.info then paste here the full post-authentication URL from the browser's address bar (it should start with http://localhost): http://localhost/?code={thecode...}
2024-10-02 17:06:05: No-GUI external auth mode: returning response http://localhost/?code={thecode...}

Config:

[IMAP-143]
server_address = outlook.office365.com
server_port = 993
local_address = 127.0.0.1

[SMTP-1587]
server_address = smtp-mail.outlook.com
server_port = 587
server_starttls = True
local_address = 127.0.0.1

[test@mail.test.info]
permission_url = https://login.microsoftonline.com/<tenant_id>/oauth2/v2.0/authorize
token_url = https://login.microsoftonline.com/<tenant_id>/oauth2/v2.0/token
oauth2_scope = https://outlook.office.com/IMAP.AccessAsUser.All https://outlook.office.com/SMTP.Send offline_access
redirect_uri = http://localhost
client_id = <client_id>
client_secret = <client_secret>

[emailproxy]
delete_account_token_on_password_error = True
encrypt_client_secret_on_first_use = False
use_login_password_as_client_credentials_secret = False
allow_catch_all_accounts = False

Unfortunately, I don't currently understand what the problem could be. I have already created and tested a new client ID and client secret.

Thanks for any help.

**Comment by simonrob** [comment]
Please post the proxy's log in [debug mode](https://github.com/simonrob/email-oauth2-proxy?tab=readme-ov-file#troubleshooting)

**Comment by dremba** [comment]
Sorry for some reason it has now worked 2 days later. Maybe it was solved by a restart, although I think I have tested this. And I had opened the link under my local computer and not on the proxy, but I'm not sure if that makes sense. Btw. what I posted was already in debug mode.

**Comment by simonrob** [comment]
It might have been in debug mode, but you cut out the vast majority of the log! Either way, I'm glad it now works. Re: local vs. proxy computer – this is fine as long as you paste the code into the proxy afterwards.

**Comment by dmitriy1980** [comment]
I have exactly the same config and I get an error stating: "The server has rejected your login. Please  verify your username and password." They are both correct.
