### ISSUE TITLE
No menu bar or popup appearing

### ISSUE THREAD

**Issue by alexbraccia** [simonrob/email-oauth2-proxy#292]
Hi, I'm trying to use your proxy to connect to Outlook 365 from an old app not supporting OAUTH2. The proxy has been installed on Red Hat, we correctly see the request to authorize the first email address but there is no bar icon or no popup. With our colleagues we have already checked all dependancies, without solving the problem. I wonder whether Red Hat is supported? In case it is, what could we do? Thanks a lot for your help!
Alex

**Comment by simonrob** [comment]
This part of the GUI is provided by [pystray](https://github.com/moses-palmer/pystray), so depends on one of its [supported backends](https://pystray.readthedocs.io/en/latest/usage.html#supported-backends) being present. If you don't see any messages in the proxy's log about GUI issues, it's worth trying a [basic pystray example](https://pystray.readthedocs.io/en/latest/usage.html#creating-a-system-tray-icon) to see whether your system is supported.

**Comment by alexbraccia** [comment]
Hi Simon,

 

I see in the docs  importing a pre-authorised proxy configuration file from elsewhere

 

Not to become mad chasing after the missing dependancies, as we only need a single email address to be authorized, can you explain how we could create and import this pre-authorized configuration?

 

Thanks again

 

Alex

 

 

 

Da: Simon Robinson ***@***.***> 
Inviato: venerdì 4 ottobre 2024 15:30
A: simonrob/email-oauth2-proxy ***@***.***>
Cc: alexbraccia ***@***.***>; Author ***@***.***>
Oggetto: Re: [simonrob/email-oauth2-proxy] No menu bar or popup appearing (Issue #292)

 

This part of the GUI is provided by pystray <https://github.com/moses-palmer/pystray> , so depends on one of its supported backends <https://pystray.readthedocs.io/en/latest/usage.html#supported-backends>  being present. If you don't see any messages in the proxy's log about GUI issues, it's worth trying a basic pystray example <https://pystray.readthedocs.io/en/latest/usage.html#creating-a-system-tray-icon>  to see whether your system is supported.

**Comment by simonrob** [comment]
You just copy the configuration file over from another system after authorising your amount. To be clear - you still need the core dependencies, though the GUI itself is optional - look at the no-GUI configuration option in the readme.

**Comment by simonrob** [comment]
I'm assuming this was resolved, so will close this issue.

**Comment by alexbraccia** [comment]
OK thanks for your help

 

Da: Simon Robinson ***@***.***> 
Inviato: lunedì 7 ottobre 2024 19:25
A: simonrob/email-oauth2-proxy ***@***.***>
Cc: alexbraccia ***@***.***>; Author ***@***.***>
Oggetto: Re: [simonrob/email-oauth2-proxy] No menu bar or popup appearing (Issue #292)

 

I'm assuming this was resolved, so will close this issue.
