### ISSUE TITLE
won't start

### ISSUE THREAD

**Issue by DBDigital** [simonrob/email-oauth2-proxy#293]
When I try to start the windows package I get:
the program can't start because api-sm-wind-core-path-1-1-0.dll is missing from your computer.  Try reinstalling the program to fix this problem.

and
failed to load python dll

I installed Python 3.8 as I thought perhaps I needed Python, but no change.

**Comment by simonrob** [comment]
The pre-built versions of the proxy are only provided as a convenience, and their compatibility may be narrower than the proxy itself. In your case it seems like you'll need to [use a newer version of Windows](https://superuser.com/a/1660401). If that's not possible, you can try one of the other options for obtaining the proxy - see the start of the readme.
