### ISSUE TITLE
Stuck in starting emailproxy with --no-gui

### ISSUE THREAD

**Issue by gipsy58** [simonrob/email-oauth2-proxy#298]
Hi Simon
having the standard mail problem with my cameras I tried to get your emailproxy running but go stuck:

Environment: 

Raspberry (old)
OS: Bookworm 
All updates made 

python -m pip install -r requirements-core.txt

Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Ignoring pyasyncore: markers 'python_version >= "3.12"' don't match your environment
Ignoring pyoslog: markers 'sys_platform == "darwin"' don't match your environment
Requirement already satisfied: cryptography>=2.2 in /home/gipsy58/.local/lib/python3.11/site-packages (from -r requirements-core.txt (line 6)) (43.0.1)
Requirement already satisfied: prompt_toolkit in /home/gipsy58/.local/lib/python3.11/site-packages (from -r requirements-core.txt (line 15)) (3.0.48)
Requirement already satisfied: pyjwt>=2.4 in /home/gipsy58/.local/lib/python3.11/site-packages (from -r requirements-core.txt (line 18)) (2.9.0)
Requirement already satisfied: cffi>=1.12 in /home/gipsy58/.local/lib/python3.11/site-packages (from cryptography>=2.2->-r requirements-core.txt (line 6)) (1.17.1)
Requirement already satisfied: wcwidth in /home/gipsy58/.local/lib/python3.11/site-packages (from prompt_toolkit->-r requirements-core.txt (line 15)) (0.2.13)
Requirement already satisfied: pycparser in /home/gipsy58/.local/lib/python3.11/site-packages (from cffi>=1.12->cryptography>=2.2->-r requirements-core.txt (line 6)) (2.22)

looks good to me.... but

python emailproxy.py --no-gui

Traceback (most recent call last):
File "/home/gipsy58/emailproxy/emailproxy.py", line 55, in <module>
    from cryptography.fernet import Fernet, MultiFernet, InvalidToken
File "/home/gipsy58/.local/lib/python3.11/site-packages/cryptography/fernet.py", line 14, in <module>
    from cryptography.exceptions import InvalidSignature
File "/home/gipsy58/.local/lib/python3.11/site-packages/cryptography/exceptions.py", line 9, in <module>
    from cryptography.hazmat.bindings._rust import exceptions as rust_exceptions
ImportError: libssl.so.1.1: cannot open shared object file: No such file or directory

Any help?
Thanks

**Comment by simonrob** [comment]
This is an issue importing the Cryptography package, which is required by the proxy. It looks like your environment has a problem with LibSSL. This is something you'll need to resolve before the proxy will work, but is not anything caused by the proxy itself.
