### ISSUE TITLE
Releases / version numbers?

### ISSUE THREAD

**Issue by michaelstepner** [simonrob/email-oauth2-proxy#30]
First off, thanks for producing this excellent tool! I'm really grateful for your work.

I'm writing code that uses `email-oauth2-proxy` to automatically launch a server on AWS which handles OAuth2/SMTP for my email client. It would be helpful for me to specify a specific version of `email-oauth2-proxy` to use, but I noticed you don't have tagged releases on your main branch.

Would you consider doing tagged releases? (For the time being, the best solution for my use case is to pin to a specific commit hash.)

**Comment by michaelstepner** [comment]
Thanks @simonrob, I don't see any reason why dates as version numbers would be a problem. If it works for Canonical with Ubuntu, it could certainly work here 😄 

Also, totally understand a sparsity of updates going forward—I'm also an academic who dabbles in open source code, and I often create things that I don't have bandwidth to continue developing or maintaining beyond my own use case. I'm glad you'll be maintaining it as a part of your own day-to-day email usage, though, because it's become an essential part of my day-to-day email usage too!

**Comment by simonrob** [comment]
Great - I've tagged the current latest commit as [2022-06-01](https://github.com/simonrob/email-oauth2-proxy/releases/tag/2022-06-01), and will continue to do so going forward.

It's nice to meet others with a similar outlook – and to be clear, I'm certainly open to further development that goes beyond basic fixes, but I just don't really have any needs that I haven't already resolved 😄

It's excellent to hear the proxy is helpful for others too!
