### ISSUE TITLE
Pre Build Windows Version is detected as trojan by several scanners

### ISSUE THREAD

**Issue by Insonic** [simonrob/email-oauth2-proxy#306]
The newest prebuild windows version is detected as trojan by several antivirus scanners.

22/71 on virustotal.com

**Comment by simonrob** [comment]
This is a common issue for packaged Python executables I'm afraid, and there is very little that can be done about it from the proxy's side. The executable is built automatically from source, so there's no possibility for malicious tampering, and it is safe to ignore the warning. If it helps you are welcome to report this false positive to the various virus scanners (e.g., see [this previous discussion](https://github.com/simonrob/email-oauth2-proxy/issues/265).
