### ISSUE TITLE
Windows Server 2016 white Screen

### ISSUE THREAD

**Issue by Pati1887** [simonrob/email-oauth2-proxy#307]
Is there a requirement problem with server os because with client os like windows10/11 anythink works fine. But when i authenicate with server os i get an white screen

Thanks

**Comment by simonrob** [comment]
The proxy uses `pywebview` to provide the popup browser window. It's worth looking in that repository for similar issues and potential solutions. For example (not in any way an exhaustive search):

- https://github.com/r0x0r/pywebview/issues/682
- https://github.com/r0x0r/pywebview/issues/803

It's worth noting that support from Microsoft for Windows Server 2016 has ended, so there may not be an easy resolution here. Either way, it's not something the proxy is in control of I'm afraid.

**Comment by simonrob** [comment]
I'm assuming this has now been resolved, but feel free to reopen this issue if that's not the case.
