### ISSUE TITLE
Minimal valid config file

### ISSUE THREAD

**Issue by michaelstepner** [simonrob/email-oauth2-proxy#31]
I'm working on an infrastructure-as-code project which will automatically configure `email-oauth2-proxy` on an AWS server. I'm planning to programmatically write a config file, and I'm therefore wondering what a minimal valid config file would look like.

I'm a bit uncertain about the minimal valid config because some of the documentation that I would ordinarily expect to appear in comments is instead defined as values with the key 'documentation' under specific headers. So I'm not sure if those sections are optional, or expected when the config file is parsed.

My current config file, with simplified/anonymized values, looks like:

```
[Email OAuth 2.0 Proxy configuration file]
documentation = multi
	line
	string.

[Server setup]
documentation = multi
	line
	string.

[IMAP-1993]
local_address = localhost
server_address = outlook.office365.com
server_port = 993

[SMTP-1587]
local_address = localhost
server_address = smtp.office365.com
server_port = 587
starttls = True

[Account setup]
documentation = multi
	line
	string.

[your.office365.address@example.com]
permission_url = https://login.microsoftonline.com/common/oauth2/v2.0/authorize
token_url = https://login.microsoftonline.com/common/oauth2/v2.0/token
oauth2_scope = https://outlook.office365.com/IMAP.AccessAsUser.All https://outlook.office365.com/SMTP.Send offline_access
redirect_uri = http://localhost
client_id = *** your client id here ***
client_secret = *** your client secret here ***
last_activity = *** unix epoch timestamp ***
token_salt = *** auto-created salt ***
access_token = *** auto-created token ***
access_token_expiry = *** unix epoch timestamp ***
refresh_token = *** auto-created token ***
```

Would this be a corresponding minimal config file?

```
[IMAP-1993]
local_address = localhost
server_address = outlook.office365.com
server_port = 993

[SMTP-1587]
local_address = localhost
server_address = smtp.office365.com
server_port = 587
starttls = True

[your.office365.address@example.com]
permission_url = https://login.microsoftonline.com/common/oauth2/v2.0/authorize
token_url = https://login.microsoftonline.com/common/oauth2/v2.0/token
oauth2_scope = https://outlook.office365.com/IMAP.AccessAsUser.All https://outlook.office365.com/SMTP.Send offline_access
redirect_uri = http://localhost
client_id = *** your client id here ***
client_secret = *** your client secret here ***
last_activity = *** unix epoch timestamp ***
token_salt = *** auto-created salt ***
access_token = *** auto-created token ***
access_token_expiry = *** unix epoch timestamp ***
refresh_token = *** auto-created token ***
```

**Comment by simonrob** [comment]
I agree the current configuration file documentation format is not ideal, but the reason is that [configparser](https://docs.python.org/3/library/configparser.html) does not preserve comments when writing back to the file, which the proxy needs to do when it adds the OAuth 2.0 token details. I'm keen to keep documentation close to where it is actually used, however, so used this approach as a workaround instead.

You can safely remove all of the documentation strings (and their headers), so your minimal example is mostly fine, except that unless you're importing token details you've obtained somewhere else, you shouldn't normally put these in manually (as the proxy will try to use whatever it finds, including these dummy values).

So, a full minimal example for Office 365 would be:
```ini
[IMAP-1993]
local_address = localhost
server_address = outlook.office365.com
server_port = 993

[SMTP-1587]
local_address = localhost
server_address = smtp.office365.com
server_port = 587
starttls = True

[your.office365.address@example.com]
permission_url = https://login.microsoftonline.com/common/oauth2/v2.0/authorize
token_url = https://login.microsoftonline.com/common/oauth2/v2.0/token
oauth2_scope = https://outlook.office365.com/IMAP.AccessAsUser.All https://outlook.office365.com/SMTP.Send offline_access
redirect_uri = http://localhost
client_id = *** your client id here ***
client_secret = *** your client secret here ***
```

**Comment by michaelstepner** [comment]
Thanks @simonrob, that's a sensible rationale for the current way you've stored documentation.

Point taken regarding storing the token details. I'm still figuring out how I will automatically configure the token on server launch, but you're quite right that including those variables is not minimal!

Closing this issue, as the question is fully answered.
