### ISSUE TITLE
cant connect smtp proxy from another machine

### ISSUE THREAD

**Issue by fraubi89** [simonrob/email-oauth2-proxy#36]
First, thank you for creating this awesome proxy!!!! 
I have installed it on a ubuntu machine, and all tests via telnet and smtp works great on this local host.
But I tried from a second machine, which is in the same network and so on, ufw disabled, but no connection.
Is this by design of the running python script that it is only available on the same host, or am I just too stupid?

Thank you so much!!!!

**Comment by fraubi89** [comment]
Ahhhhhhhh :-)

Ok thats not mentioned in the example config file, but i just added the line local_address in the config file, and now the connection works from another machine! Now I have check successfull authentication, but that should work now. 

Thank you so much!!
One last question, do you thought about making an docker container with variables for this awesome project? 
with an docker container it would be super flexible for different machines and environments!

**Comment by simonrob** [comment]
Great - I'm glad this now works for you. The `local_address` parameter [is mentioned in the documentation](https://github.com/simonrob/email-oauth2-proxy/blob/a66db08210286c0ae3138093a7dea5dcf03118d0/emailproxy.config#L24), but I could add this to one of the example servers to help avoid overlooking it in future.

I haven't considered a docker container, and wouldn't have time to maintain this myself, but as shown with the AWS example it shouldn't be too difficult to set up. I'm happy to link to other people's versions for different environments of course.

**Comment by fraubi89** [comment]
Thanks! :-)
