### ISSUE TITLE
Cannot set insecure imap authentication in Mail app

### ISSUE THREAD

**Issue by pethr** [simonrob/email-oauth2-proxy#40]
This is a genius solution to Apple woes! 

However, on my Mac OS 10.13.6 I cannot set insecure imap connection to localhost:xxxx in Mail app (11.5) as the setting to allow insecure authentication in GUI cannot be saved and does nothing per https://discussions.apple.com/thread/8087473 Because of this Mail app fails to even save the config as the account cannot be verified ("Unable to verify account name or password").

How do you still make it work?

SMTP can be set up correctly but IMAP and POP cannot.

**Comment by simonrob** [comment]
I don't use the macOS Mail app myself, so haven't encountered this issue. However, you should be able to use the proxy's [secure local connection option](https://github.com/simonrob/email-oauth2-proxy/blob/cebffff9db4903615328522ecd33c4a74225568f/emailproxy.config#L27) to work around this.

**Comment by simonrob** [comment]
I'm going to close this issue as I'm assuming the proxy's local certificates option has fixed the problem you were encountering. Feel free to reopen if not.
