### ISSUE TITLE
Client secret not required for Public client apps

### ISSUE THREAD

**Issue by reevesjeremy** [simonrob/email-oauth2-proxy#43]
RE: Office365

AzureAD App client secrets are usually used in a Confidential client configuration where an application is running as a service/daemon of some kind.  Since I just want the proxy to work to authenticate a user, I would instead use an Azure AD app configured as a Public client.  In this situation, a client secret would not necessarily be required since the user will be authenticating as itself.

In my testing I set the client_secret blank in my config file and made the following modification in the code
https://github.com/simonrob/email-oauth2-proxy/blob/89f2f7c1ac81fb862ceb6e437f1148c58e190b66/emailproxy.py#L280

To:
```
        if not (permission_url and token_url and oauth2_scope and redirect_uri and client_id):
```

This works perfectly and still allows for a client_secret to be used if it were going to be used a different way.

What were your thoughts when making client_secret a required field, and would you consider republishing as optional?

**Comment by simonrob** [comment]
Thanks for raising this – it has been on my todo list for a while to check this particular configuration for O365, so it's great that you've confirmed it works.

dc8b717 updates the proxy to account for this, making sure not to send `client_secret=None`, and instead omitting the value entirely if it is not present. Please could you check that accounts with no `client_secret` value present work properly with this update and a client configured in this way?

**Comment by reevesjeremy** [comment]
> making sure not to send `client_secret=None`, and instead omitting the value entirely

Yep, I tried that as part of my original test, and found that if an invalid secret value is included, it will return 401 Unauthorized

I was also thinking of this in the debug log. client_secret is no longer required.
https://github.com/simonrob/email-oauth2-proxy/blob/dc8b7177b483e60df498e58223e824f74bbac3a9/emailproxy.py#L285

> Please could you check that accounts with no `client_secret` value present work properly with this update and a client configured in this way?

Works!

**Comment by simonrob** [comment]
Thanks for testing this. Yes - the messages can probably be improved, though I'd like to keep things as simple as possible for the normal use-case. It might be worth throwing errors if the default values are found, though, as you suggest.

Re: config file examples, this is a trade-off with the `configparser` module. The proxy needs to write back to the configuration file, but that module doesn't really support comments. Given that the proxy's main usage is designed to be entirely local I think this isn't a major issue, but I'm open to suggestions for improvement
