### ISSUE TITLE
External auth not working

### ISSUE THREAD

**Issue by D4rki91** [simonrob/email-oauth2-proxy#47]
Hello,

We have the problem that the external authoristation method isn't working.

First we got a bit trouble to make the webview work on Windows cause we weren't able to copy paste there, but after editing "forced_gui = 'mshtml'" to "forced_gui = 'CEF'" the webview is working fine.

But the authorisation itself is not working. 
The Login authorisation link is working, we log in with our user account and after that we get the timeout from the redirect uri.

Now we paste the uri with the authorisation code into the input field and press submit but nothing happens. The webview window just shows the same "localhost refused to connect" site and thats all, no authentication of the user.

Thanks for your help!

**Comment by chupocro** [comment]
It may be one of the folowing:

1. Are you sure you are pasting the correct URL? The URL that has to be pasted contains `localhost`. The only way I can paste the correct URL is to open **Developer Tools** > **Network** just before clicking **Continue** button (after which there is timeout) and to copy the URL from the GET request shown in the Developer Tools.

2. A few times I had to wait for a few minutes after pasting the URL.

**Comment by D4rki91** [comment]
Hi, thanks for your help.

Unfortunately it's still not working. I have copied the URL from the Developer Tools > Network Tab.

`http://localhost/?code=0.AR**C8pu_CzxY0CqvDrprmhSHMs6Ko9qZ_xJq95q2bdtOswfAAA.AgABAAIAAAD--DLA3VO7QrddgJg7WevrAgDs_wQA9P8pIwIBD*********MF_yCR5dIoWncb5dkhskkBSE8SRyLIJCBw3qHpFOOKk7aE6ZKg-yzE3X21GbbYX2m9****O9EJubmp2QByI_IntoC9tlO7reEJi-wcMDTBwy33mDYnoIx_JYHJau-0S-xnYBcV1MpOOg0HxwVg8NIZdw7FdoOFEKbgfbjmdpHncyYiZ06gDL8HfhQPuazo5acoWR6ECfqEMh-nRZJ1xf47OKP2****BcbfsRJBYDYL4bLWwp************cMQ5qBYmUX5_8D7c0US3869H_NtiVSt4dCGwDyYIzGRjn1yIb_PXLsYCxE4xI8DQf5eZj75_VNs4tdF-O4Vv_lvY4o_YU5w2xY9COFYUGejeh5N6iJATEoO9bnuMUBA2YqNhyhTBY5rWU3a6LdhBAoFOK-XyHXz7Gq3mEFaGU1yEng2GV4Fj3*******************u6lvK2ZL9tiQQdOl5QxL-DahpHjHJjruNK0Ap3isDSlI7Hia-mHTLiyOMxEbm6gvxkeH5-AgeT89Rv57Sjsf6mqjPP_4kl6A&session_state=a1******-7773-4c24-b1a6-6d25053a3823`

and after I submitted it I waited a few minutes but nothing happened. The proxy configuration file also hasn't added anything.

Changing the gui from `"forced_gui = 'mshtml'" to "forced_gui = 'CEF'"` can't be the source of the problem I guess?

**Comment by D4rki91** [comment]
Hi, thanks for your help.

Unfortunately it's still not working. I have copied the URL from the Developer Tools > Network Tab.

http://localhost/?code=0.AR**C8pu_CzxY0CqvDrprmhSHMs6Ko9qZ_xJq95q2bdtOswfAAA.AgABAAIAAAD--DLA3VO7QrddgJg7WevrAgDs_wQA9P8pIwIBD*********MF_yCR5dIoWncb5dkhskkBSE8SRyLIJCBw3qHpFOOKk7aE6ZKg-yzE3X21GbbYX2m9****O9EJubmp2QByI_IntoC9tlO7reEJi-wcMDTBwy33mDYnoIx_JYHJau-0S-xnYBcV1MpOOg0HxwVg8NIZdw7FdoOFEKbgfbjmdpHncyYiZ06gDL8HfhQPuazo5acoWR6ECfqEMh-nRZJ1xf47OKP2****BcbfsRJBYDYL4bLWwp************cMQ5qBYmUX5_8D7c0US3869H_NtiVSt4dCGwDyYIzGRjn1yIb_PXLsYCxE4xI8DQf5eZj75_VNs4tdF-O4Vv_lvY4o_YU5w2xY9COFYUGejeh5N6iJATEoO9bnuMUBA2YqNhyhTBY5rWU3a6LdhBAoFOK-XyHXz7Gq3mEFaGU1yEng2GV4Fj3*******************u6lvK2ZL9tiQQdOl5QxL-DahpHjHJjruNK0Ap3isDSlI7Hia-mHTLiyOMxEbm6gvxkeH5-AgeT89Rv57Sjsf6mqjPP_4kl6A&session_state=a1******-7773-4c24-b1a6-6d25053a3823

and after I submitted it I waited a few minutes but nothing happened. The proxy configuration file also hasn't added anything.

Changing the gui from "forced_gui = 'mshtml'" to "forced_gui = 'CEF'" can't be the source of the problem I guess?

**Comment by simonrob** [comment]
Thanks for the update. That does look like a valid URL, but as the [comment about the `forced_gui` value](https://github.com/simonrob/email-oauth2-proxy/blob/c1945ca7804419924bd2828889973018f842e229/emailproxy.py#L1761) notes, it is indeed required because of the way the URL needs to be retrieved.

Are you perhaps running in a python =virtual environment? I can't find the issue right now, but pywebview has a known problem with keyboard entry in a virtual environment on some platforms.

**Comment by D4rki91** [comment]
Hey,

Im running python on a Windows Server 2019 VM under VMware ESXi.
Any clue how to fix the copy paste issue with "mshtml" gui ? 
The URI is just a bit to long to type them into the submit field by myself. :)

Thanks!

**Comment by simonrob** [comment]
You could try turning on debug mode for pywebview, and then copy/paste via the right-click context menu?

Edit [this line](https://github.com/simonrob/email-oauth2-proxy/blob/c1945ca7804419924bd2828889973018f842e229/emailproxy.py#L1764) to `webview.start(gui=forced_gui, debug=Log.get_level() == logging.DEBUG)`, and then run the proxy in debug mode (`--debug`).

**Comment by D4rki91** [comment]
Thanks a lot, thats working and the user gets successfully authenticated. :)

Unfortunately the "copy" button for the URL in the window form is still not working and you cant mark it to right click copy it cause you will just move the windows. But fine, I can click the link and copy it from the browser.

Am I right that I dont need specific localhost redirect ports in my config for multiple user accounts with the --external-auth method?

**Comment by simonrob** [comment]
Great – glad this workaround resolved this. I've added and documented this in 99e25ec.

Re: `redirect_uri` yes, specifying a unique port per account is only needed when using the `--local-server-auth` option.
