### ISSUE TITLE
gnubiff

### ISSUE THREAD

**Issue by JPEckmann** [simonrob/email-oauth2-proxy#49]
I would like to "upgrade" gnubiff to oauth2 using this tool (on ubuntu)
but first it has problems installing webview.

and can someone tell me how to configure this for gnubiff?

(gnubiff checks for new mail evety x minutes, and has a jumping linux if mail arrives..

Thanks!

**Comment by simonrob** [comment]
I can't help with specific gnubiff configuration, but you should be able to configure it to use the proxy in the same way as any other email server.

Given that the GUI-related requirements are at the root of many similar questions, I've added a [requirements-no-gui branch](https://github.com/simonrob/email-oauth2-proxy/tree/requirements-no-gui) – you should be able to install and set the proxy up using this version with no dependency issues, then switch to the GUI later if needed

**Comment by JPEckmann** [comment]
On Fri, 19 Aug 2022, Simon Robinson wrote:
Thanks a lot, but somehow the instructions confuse me...

So in gnubiff I say that that the address is localhost:1993

when I turn on emailproxy.py I see that its listening for authentication 
request.

( I put my email in the config file.) Then I see in debug mode that 
gnubiff tries to connect (every 5 seconds for test) 

I get every 5 seconds

2022-08-19 14:51:14: IMAP (localhost:1993; 
127.0.0.1:57624->outlook.office365.com:993) <-- b'* OK The Microsoft 
Exchange IMAP4 service is ready. 
[WgBSADAAUAAyADcAOABDAEEAMAAxADAAOAAuAEMASABFAFAAMgA3ADgALgBQAFIATwBEAC4ATwBVAFQATABPAE8ASwAuAEMATwBNAA==]\r\n'
-------------------------

How do I proceed? Do I need to give my credit card to azure?

Thanks for help
JP







->I can't help with specific gnubiff configuration, but you should be able to configure it to use the proxy in the same way as any other email server.
->
->
->
->Given that the GUI-related requirements are at the root of many similar questions, I've added a [requirements-no-gui branch](https://github.com/simonrob/email-oauth2-proxy/tree/requirements-no-gui) – you should be able to install and set the proxy up using this version with no dependency issues, then switch to the GUI later if needed
->
->
->
->-- 
->
->Reply to this email directly or view it on GitHub:
->
->https://github.com/simonrob/email-oauth2-proxy/issues/49#issuecomment-1220394488
->
->You are receiving this because you authored the thread.
->
->
->
->Message ID: ***@***.***>

**Comment by simonrob** [comment]
If you haven't already done so you'll need to add values for `client_id` and `client_secret` in your account's configuration file entry – see the [proxy's readme](https://github.com/simonrob/email-oauth2-proxy/issues/49) for more information about how to do this.

The log message you posted is a normal greeting from the Outlook IMAP server, but you should also see a login attempt in the log from your client application once you've set it up to use the proxy.

**Comment by simonrob** [comment]
I'm assuming this is now resolved so I'm going to close this issue.
