### ISSUE TITLE
Refresh Token not renewed

### ISSUE THREAD

**Issue by hipslu** [simonrob/email-oauth2-proxy#50]
First of all, thanks for this project!

Currently, the refresh token is used to obtain new access tokens, but the refresh token itself is never updated - which leads to the problem having the initial refresh token not beeing valid anymore, forcing the user to reauthenticate.

so i think simply storing the new refresh token as well when getting the new access token would fix that, so adding the following two lines should do the trick:

refresh_token  = response['refresh_token']
config.set(username, 'refresh_token', OAuth2Helper.encrypt(cryptographer, refresh_token))

what do you think?

**Comment by D4rki91** [comment]
Hey,

Do you use the Local Server Auth or External Server Auth?

Kind regards

**Comment by hipslu** [comment]
local server auth

**Comment by simonrob** [comment]
Thanks very much for raising this – it is a clear oversight (but unrelated to the authentication mode - it applies in all cases)
