### ISSUE TITLE
CPU leak when fetch mails

### ISSUE THREAD

**Issue by Reymouth** [simonrob/email-oauth2-proxy#52]
Hello,

After the launch of the script, at the first fetch of mails. I see a CPU leak.
The traces indicate the presence of a loop in the code.

Trace : https://paste.pichax.fr/vujonumula.lua

Thank's

**Comment by simonrob** [comment]
As in #44 replication is an issue, but could you try the [issue_52](https://github.com/simonrob/email-oauth2-proxy/tree/issue_52) branch?

**Comment by Reymouth** [comment]
It's ok ! The CPU leak no longer seems to be detected.

Another malfunction, an application of my applications does not connect in SMTP (TLS 1.2).

The error without debug:
> 2022-08-23 14:24:40: SMTP (0.0.0.0:1587) Caught asyncore info message (server) - error : uncaptured python exception, closing channel <__main__.SMTPOAuth2ServerConnection connected smtp.office365.com:587 at 0x7f9d267abdf0> (<class 'ssl.SSLWantReadError'>:The operation did not complete (read) (_ssl.c:2472) [/usr/lib/python3.9/asyncore.py|read|83] [/usr/lib/python3.9/asyncore.py|handle_read_event|420] [/opt/email-oauth2-proxy/emailproxy.py|handle_read|1029] [/opt/email-oauth2-proxy/emailproxy.py|process_data|1278] [/opt/email-oauth2-proxy/emailproxy.py|process_data|1033] [/opt/email-oauth2-proxy/emailproxy.py|send|697] [/usr/lib/python3.9/asyncore.py|send|527] [/usr/lib/python3.9/asyncore.py|initiate_send|514] [/usr/lib/python3.9/asyncore.py|send|358] [/usr/lib/python3.9/ssl.py|send|1173])

Traces : https://paste.pichax.fr/gesemiwasa.lua

**Comment by simonrob** [comment]
Good news: I finally managed to replicate this issue (and #44) by switching to a different setup, and I've been able to test secure local connections in various configurations. As far as I can tell, 4198eaf now resolves both issues properly.

This commit also enforces verification of the local TLS connection by default, but adds a new optional `verify_local_certificate` configuration parameter that can be used if disabling this is necessary (e.g., for a self-signed certificate).

**Comment by Reymouth** [comment]
I'm glad you were able to reproduce the behavior. I still encounter a malfunction with the SMTP connection with one of my tools. I share it with you in the link below.

Tools : https://plik.root.gg/file/oOLvAMqSCkikNAmI/6jgApnHRSiLosa0X/ctotestmail.exe

Thank's

**Comment by simonrob** [comment]
That's strange. I haven't yet tried your tool, but is it throwing exactly the same error as before? Does it still happen if you set `verify_local_certificate = False` in the server configuration?

What operating system is this happening on (both client and proxy host), and what python version are you using to run the proxy?

**Comment by Reymouth** [comment]
I have implemented verify_local_certificate=False option for POP and SMTP. The POP works correctly, on the other hand I cannot make my tools work with the SMTP, a blockage seems to persist to end the connection and have the result "connection successful". In debug mode, I have no particular error, see below.

Proxy host :
Debian 11
Kernel 5.10.127-1 (2022-06-30)
Python 3.9.2

Client host :
Windows 10 with my tools

Debug :
> 2022-08-25 07:36:45: SMTP (0.0.0.0:1587; 100.66.6.161:53977->smtp.office365.com:587) --> [ Client connected ]
2022-08-25 07:36:45: SMTP (0.0.0.0:1587; 100.66.6.161:53977->smtp.office365.com:587) <-- [ Starting TLS handshake ]
2022-08-25 07:36:45: SMTP (0.0.0.0:1587; 100.66.6.161:53977->smtp.office365.com:587)     <-- b'220 PR3P191CA0023.outlook.office365.com Microsoft ESMTP MAIL Service ready at Thu, 25 Aug 2022 05:36:45 +0000\r\n'
2022-08-25 07:36:45: SMTP (0.0.0.0:1587; 100.66.6.161:53977->smtp.office365.com:587) <-- b'220 PR3P191CA0023.outlook.office365.com Microsoft ESMTP MAIL Service ready at Thu, 25 Aug 2022 05:36:45 +0000\r\n'

**Comment by simonrob** [comment]
Thanks for the extra detail. I suspect that this is now an issue with the client you are using (though I still haven't had chance to try it, so am happy to be shown otherwise).

The reason for thinking this is that the log is identical to what happens if you try to connect using an unsecured client (e.g., `telnet localhost 1587`). Probably, if you try, e.g., `openssl s_client -crlf -connect localhost:1587` the connection will succeed.

afa05ae makes this more explicit, and you should get this error when the connection times out: ```Caught connection error in POP (localhost:1587) - you have set `local_certificate_path` and `local_key_path`; is your client using a secure connection? Error type <class 'ssl.SSLError'> with message: ac.robinson.email-oauth2-proxy```.

I should have mentioned before – a Let's Encrypt certificate should work without the need for `verify_local_certificate`; this is intended only for self-signed local certificates. If needed, you can test both variants by supplying certificate details when connecting using, e.g., `openssl s_client -cert [certificate path] -key [key path] -crlf -connect localhost:1587`.

**Comment by Reymouth** [comment]
Without the verify_local_certificate option, i have an error :
> Aug 25 09:42:44 oauth2-mailproxy Email OAuth 2.0 Proxy: SMTP (0.0.0.0:1587) Caught asyncore info message (client) - error : uncaptured python exception, closing channel <__main__.SMTPOAuth2ClientConnection connected 127.0.0.1:48488 at 0x7f28b6762dc0> (<class 'ssl.SSLCertVerificationError'>:[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get issuer certificate (_ssl.c:1123) [/usr/lib/python3.9/asyncore.py|read|83] [/opt/email-oauth2-proxy/emailproxy.py|handle_read_event|637] [/opt/email-oauth2-proxy/emailproxy.py|ssl_handshake|625] [/usr/lib/python3.9/ssl.py|do_handshake|1309])

140404120442176:error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca:../ssl/record/rec_layer_s3.c:1543:SSL alert number 48

the command returns :
https://paste.pichax.fr/pajulenuyu.yaml

The TLS 1.3 version may be too recent? My tools use TLS 1.2 or less

**Comment by D4rki91** [comment]
Im not sure if this matches your problem but I had also trouble to get the secure connection work. But the background here is the client application I use does not support "POP3 Secure" anyway.

So what I did was to edit the existing STunnel SSL Wrapper config on the client to something like:

```
[POP3 Incoming OAuth]
client = yes
accept = 1234 (random port)
connect = oauthproxy.de:1995
CAfile = ca-certs.pem
cert = stunnel.pem
```
Now the client connects to localhost "1234" and the stunnel uses a secure connection to the proxy application on behalf where I also use Let's Encrypt pem certificates.

Maybe you can also get it work this way?

**Comment by simonrob** [comment]
@D4rki91 thanks for this suggestion – @Reymouth I think it is worth trying this. I just tried your client with a self-signed local certificate and it refused to connect in any of its TLS mode options. A connection set up by openssl works fine, though, including when forcing particular TLS versions (e.g., the `-tls1_2` etc options for openssl's `s_client`)

86a59c8 is a minor update to improve error handling (such as the one mentioned above that your client causes) – feel free to test this, but I don't think it will change the behaviour. I think the best option (unless you are able to give me access to the server) is to try editing [the script's `SSLContext` object](https://github.com/simonrob/email-oauth2-proxy/blob/86a59c8ae762557a9db2dc5ceafc130af3a5db29/emailproxy.py#L1431) to match your setup – for example, `ssl_context.options |= ssl.OP_NO_TLSv1_3` may help. There are [lots of options](https://docs.python.org/3/library/ssl.html#ssl.SSLContext) here...

**Comment by Reymouth** [comment]
@D4rki91, i am unable to use stunnel with SMTP protocol.
After installation, I test with the command: `echo "Q" | openssl s_client -connect localhost:1995 -brief`

@simonrob, i tried the different ssl_context.options parameters, but the malfunction persists.
The error returned in debug is always the one below:
> 2022-08-26 11:15:54: New incoming connection to SMTP server at 0.0.0.0:1587 (TLS) proxying smtp.office365.com:587 (STARTTLS)
2022-08-26 11:15:54: Accepting new connection to SMTP server at 0.0.0.0:1587 (TLS) proxying smtp.office365.com:587 (STARTTLS) via ('100.66.6.161', 53898)
2022-08-26 11:15:54: SMTP (0.0.0.0:1587; 100.66.6.161:53898->smtp.office365.com:587) --> [ Client connected ]
2022-08-26 11:15:54: SMTP (0.0.0.0:1587; 100.66.6.161:53898->smtp.office365.com:587) <-- [ Starting TLS handshake ]
2022-08-26 11:15:55: SMTP (0.0.0.0:1587; 100.66.6.161:53898->smtp.office365.com:587)     <-- b'220 PR0P264CA0234.outlook.office365.com Microsoft ESMTP MAIL Service ready at Fri, 26 Aug 2022 09:15:54 +0000\r\n'
2022-08-26 11:15:55: SMTP (0.0.0.0:1587; 100.66.6.161:53898->smtp.office365.com:587) <-- b'220 PR0P264CA0234.outlook.office365.com Microsoft ESMTP MAIL Service ready at Fri, 26 Aug 2022 09:15:54 +0000\r\n'
2022-08-26 11:15:55: Caught connection error in SMTP (0.0.0.0:1587; 100.66.6.161:53898->smtp.office365.com:587) - you have set `local_certificate_path` and `local_key_path`; is your client using a secure connection? Error type <class 'ssl.SSLError'> with message: ac.robinson.email-oauth2-proxy
2022-08-26 11:15:55: SMTP (0.0.0.0:1587; 100.66.6.161:53898->smtp.office365.com:587) --> [ Client disconnected ]

**Comment by simonrob** [comment]
Out of interest I tried your tool to connect directly to `outlook.office365.com:995` and `smtp.office365.com:587`, and it failed here as well. I think the problem is probably with the tool rather than the proxy.

**Comment by Reymouth** [comment]
Hello, i managed to connect by modifying the openssl configuration, so that it allows TLS 1.1 and lower.

**Comment by simonrob** [comment]
Excellent! Just to be clear, does the proxy now work fully in your setup with local certificates?

**Comment by Reymouth** [comment]
The tool works in TLS 1.0 and TLS 1.1. But not with TLS 1.2. But it's already very good. Thanks
