### ISSUE TITLE
NoneType error with no client secret

### ISSUE THREAD

**Issue by athoms** [simonrob/email-oauth2-proxy#53]
Hi, thanks for this helpful project!

If the client secret is not specified in the configuration, the line
https://github.com/simonrob/email-oauth2-proxy/blob/f892aa1003890db9da3529689cbff49583d28214/emailproxy.py#L301
produces the error `argument of type 'NoneType' is not iterable`.

A simple fix would be
`example_client_status = [example_client_value in i for i in [client_id, client_secret] if i is not None]`  
or just
`example_client_status = [example_client_value in i for i in [client_id, client_secret] if i]`  
if empty strings can be ignored.

**Comment by simonrob** [comment]
Thanks for reporting this!
