### ISSUE TITLE
Is it possible to set it up as a multi user proxy?

### ISSUE THREAD

**Issue by MarekMB** [simonrob/email-oauth2-proxy#57]
Hi 

Thank you very much for making the email-oauth2-proxy project!

Looking into documentation, it seems it is a single account-focused solution. Am I correct? It is not quite clear to me from the description.
Is it possible to run it as a proxy for multiple accounts/users at once? 

If not, do you know about any other solution which can proxy POP/IMAP to OAUTH2 for multiple users?

Thank you in advance,
Best regards

**Comment by simonrob** [comment]
Yes, the proxy supports multiple accounts. Full documentation is in the sample configuration file - just add an account section for each one you want to use. Multiple accounts can share the same OAuth 2.0 client ID and secret.
