### ISSUE TITLE
Disable SSL

### ISSUE THREAD

**Issue by ebraspen** [simonrob/email-oauth2-proxy#64]
Hi there,
This is not an issue but rather a question.
Is it possible to disable the implicit SSL connection between the IMAP (mail server) and the email proxy?
There is an option to disable STARTTLS, but apparently not for SSL itself.
Thank you for your feedback!
Eddy

**Comment by simonrob** [comment]
This is a straightforward capability to add, but I'm curious as to why it might be needed. As far as I know, providers that require OAuth 2.0 also require a secure connection, either from the outset or via STARTTLS. Are you using the proxy with another provider, or in some other configuration I haven't considered?

**Comment by simonrob** [comment]
I'm going to close this as I'm assuming it has now been resolved, but feel free to reopen if needed.
