### ISSUE TITLE
Feature request: Indicate which account is authenticating in logs/console

### ISSUE THREAD

**Issue by Steltek** [simonrob/email-oauth2-proxy#67]
Currently, whenever an account successfully authenticates, the following message is output to the console/log:

`2022-09-28 14:53:15: IMAP (hostname:993) [ Successfully authenticated IMAP connection - removing proxy ]`

It would be helpful in troubleshooting if this message could include the account that is authenticating so that, on a system with mutiple accounts, one can identify which one did the authentication correctly.

An example would be: 

`2022-09-28 14:53:15: IMAP (hostname:993) [ Successfully authenticated IMAP connection for localpart@domain.tld - removing proxy ]`

**Comment by simonrob** [comment]
This is already the case if you enable debug mode, but I can see why it might be useful to have it as standard.
