### ISSUE TITLE
encrypt_client_secret_on_first_use: Encode error with no client_secret

### ISSUE THREAD

**Issue by athoms** [simonrob/email-oauth2-proxy#73]
Hi,

when `encrypt_client_secret_on_first_use` is set to `True` and one or more account sections have no `client_secret` entry, this
https://github.com/simonrob/email-oauth2-proxy/blob/d1a7421e36918ac8afb5bcfed2254faffe1c4464/emailproxy.py#L424-L425
throws `AttributeError("'NoneType' object has no attribute 'encode'")` after getting the access token.

A simple fix would be:
```python
if client_secret and AppConfig.globals().getboolean('encrypt_client_secret_on_first_use', fallback=False):
```

**Comment by simonrob** [comment]
Thanks for reporting this.
