### ISSUE TITLE
Authentication Unsuccessful - IMAP with Office365

### ISSUE THREAD

**Issue by TexasGitHubber** [simonrob/email-oauth2-proxy#74]
Dear simonrob,

I hope you or someone in this realm can help tell me what I'm doing wrong.

I feel like OAUTH is working, since I can see that the program updated the emailproxy.config file with token_salt, access_token, and access_token_expiry values.

However, when I test my email connection to the IMAP server, I get the following in the log file (using --debug switch):

```
 --> [ Client connected ]
 <-> [ Starting TLS handshake ]
 <-> [ TLS handshake complete ]
     <-- b'* OK The Microsoft Exchange IMAP4 service is ready. [XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX]\r\n'
 <-- b'* OK The Microsoft Exchange IMAP4 service is ready. [XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX]\r\n'
 --> b'00000000 CAPABILITY\r\n'
     --> b'00000000 CAPABILITY\r\n'
     <-- b'* CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS ID UNSELECT CHILDREN IDLE NAMESPACE LITERAL+\r\n'
 <-- b'* CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN SASL-IR UIDPLUS ID UNSELECT CHILDREN IDLE NAMESPACE LITERAL+\r\n'
     <-- b'00000000 OK CAPABILITY completed.\r\n'
 <-- b'00000000 OK CAPABILITY completed.\r\n'
 --> b'00000001 AUTHENTICATE PLAIN\r\n'
 <-- b'+ \r\n'
 --> b'[[ Credentials removed from proxy log ]]'
     --> b'00000001 AUTHENTICATE XOAUTH2 '
     --> b'[[ Credentials removed from proxy log ]]'
     --> b'\r\n'
    <-- b'00000001 NO AUTHENTICATE failed.\r\n'
<-- b'00000001 NO AUTHENTICATE failed.\r\n'
--> b'00000002 AUTHENTICATE PLAIN\r\n'
<-- b'+ \r\n'
--> b'[[ Credentials removed from proxy log ]]'
    --> b'00000002 AUTHENTICATE XOAUTH2 '
    --> b'[[ Credentials removed from proxy log ]]'
    --> b'\r\n'
    <-- b'00000002 NO AUTHENTICATE failed.\r\n'
<-- b'00000002 NO AUTHENTICATE failed.\r\n'
--> b'00000003 AUTHENTICATE PLAIN\r\n'
<-- b'+ \r\n'
--> b'[[ Credentials removed from proxy log ]]'
    --> b'00000003 AUTHENTICATE XOAUTH2 '
    --> b'[[ Credentials removed from proxy log ]]'
    --> b'\r\n'
    <-- b'00000003 NO AUTHENTICATE failed.\r\n'
<-- b'00000003 NO AUTHENTICATE failed.\r\n'
--> b'00000004 LOGOUT\r\n'
    --> b'00000004 LOGOUT\r\n'
    <-- b'* BYE Microsoft Exchange Server IMAP4 server signing off.\r\n'
<-- b'* BYE Microsoft Exchange Server IMAP4 server signing off.\r\n'
    <-- b'00000004 OK LOGOUT completed.\r\n'
<-- b'00000004 OK LOGOUT completed.\r\n'
<-- [ Server disconnected ]
```

Here is a snip from my emailproxy.config:

```
[IMAP-1993]
local_address = localhost
server_address = outlook.office365.com
server_port = 993

...

[xxxxxxxxxxx@xxxxxx.com]
token_url = https://login.microsoftonline.com/1464XXXXXXXXXXXXXXXXXXXXXXX82/oauth2/v2.0/token
oauth2_scope = https://outlook.office365.com/.default offline_access
redirect_uri = http://localhost
client_id = feXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXe5
client_secret = XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

...

[emailproxy]
delete_account_token_on_password_error = False
encrypt_client_secret_on_first_use = False

```

On my mail client, I changed the host to localhost, port to 1993, and the protocol to just IMAP.  The username/password has been left as it was before.

On the Microsoft side, I've created the API endpoint, setup Exchange service principals, given IMPA permissions, etc. 

It seems that you have built a really nice utility here that I hope to be able to use.

Thanks!

**Comment by lakelse** [comment]
Hi @TexasGitHubber,

Looks like you're close.  I trust you're setting up the client_credential flow and unlike other examples I've seen here where people seem to have gotten it working, you have the tenant id in the token url (which is what I did as well).  Anyway, try adding:
```python
params['resource'] = 'https://outlook.office365.com'
```
after this line:
https://github.com/simonrob/email-oauth2-proxy/blob/991237f70f6ccea622879ca1312ef2a4ffe8ce26/emailproxy.py#L611

It's a bit of a shot in the dark but good luck!

**Comment by simonrob** [comment]
You shouldn't need to edit the script itself to use the client credentials grant flow. The only thing I notice from your example configuration file is that you have kept `offline_access` - it isn't needed in this mode.

Have you tried the setup script that is linked from the configuration file documentation?

**Comment by TexasGitHubber** [comment]
@simonrob and @lakelse  -  I tried both suggestions and still had no success.

It turns out that I made a mistake with setting up the service principal.  Long story short, I used the wrong "OBJECT_ID'.  "The OBJECT_ID is the Object ID from the Overview page of the Enterprise Application node (Azure Portal) for the application registration. It is not the Object ID from the Overview of the App Registrations node. Using the incorrect Object ID will cause an authentication failure."

@simonrob I took your advice and used your setup script at [Issue61](https://github.com/simonrob/email-oauth2-proxy/issues/61#issuecomment-1259110336.)  It worked with the undecrypted values.  I tried both ways and it works, but better to be safer!

@lakelse I tried adding the line you suggested, it works the same for me both with and without that line, FYI.

Thank you all for your help!

**Comment by TexasGitHubber** [comment]
Update...

I got past authentication successfully, but now am getting some other errors:
```

    <-- b'00000001 OK AUTHENTICATE completed.\r\n'
[ Successfully authenticated IMAP connection - removing proxy ]
<-- b'00000001 OK AUTHENTICATE completed.\r\n'
--> b'00000002 CAPABILITY\r\n'
<-- b'* CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS MOVE ID UNSELECT CLIENTACCESSRULES CLIENTNETWORKPRESENCELOCATION BACKENDAUTHENTICATE CHILDREN IDLE NAMESPACE LITERAL+\r\n00000002 OK CAPABILITY completed.\r\n'
--> b'00000003 SELECT INBOX\r\n'
<-- b'00000003 BAD User is authenticated but not connected.\r\n'
--> b'00000004 EXPUNGE\r\n'
<-- b'00000004 BAD User is authenticated but not connected.\r\n* BYE Connection closed. 14\r\n'
```

Any ideas on how to get past this one?

Thanks.

**Comment by TexasGitHubber** [comment]
Please disregard the last comment.  I had an incorrect password in my email client!

**Comment by simonrob** [comment]
Great - glad you were able to get this working.

Re: `User is authenticated but not connected` – there seem to be several possible causes for this rather cryptic error message, but I think the most common is that the user (or service principal in this case) is valid but doesn't have the right scopes.

The password shouldn't make a difference (the proxy should catch this because decryption will fail).

O365 may also use this message when rate-limiting if your client is trying download a large mailbox in full, but that is only temporary.
