### ISSUE TITLE
Need help setting up email-oauth2-proxy properly

### ISSUE THREAD

**Issue by sflamm** [simonrob/email-oauth2-proxy#78]
Would appreciate some help getting this up and running (newbie)

My environment:

 Dynamics 2016 CRM supporting POP/SMTP
 Windows Server 2019

I have registered an Application with Azure AD and obtained a client ID and client secret (value)...  And of course I have the tenantID for my O365.

Can  you please guide me on the following items:

1.  I need to run the proxy on a port other than 80 (occupied).   I have set the redirect URL as follows - is this correct?:

redirect_uri = http://localhost:10001

Is it possible to use the DNS name for an interface that resolves on the local machine like this:

redirect_uri = http://FQDN:PORT  or  an IP   https://IP:PORT

Do I also need to configure the same redirect_url setting under my registered Azure AD application?  Or just in the email-oauth2-proxy config file?  The documentation here indicates one can be added --> see section "Add a Redirect URI"

https://learn.microsoft.com/en-us/azure/active-directory/develop/quickstart-register-app

2.  It looks like i need a config block [person@mydomain.com] for each account/user that is to be proxied.  Do I have that correct?

Mine looks like this:

[person@mydomain.com]
permission_url = https://login.microsoftonline.com/TENANTID/oauth2/v2.0/authorize
token_url = https://login.microsoftonline.com/TENANTID/oauth2/v2.0/token
oauth2_scope = https://outlook.office365.com/IMAP.AccessAsUser.All https://outlook.office365.com/POP.AccessAsUser.All https://outlook.office365.com/SMTP.Send offline_access
redirect_uri = http://localhost:10001
client_id =CLIENT ID
client_secret = CLIENT SECRET VALUE

Is there any way of avoiding putting in entries for each of the email accounts who will be proxied?  Is there a syntax where I can just use [@mydomain.com] --> implying use the same values for all of the email account.   Or a command-line flag?   Otherwise it would be complex to maintain requiring stop/edit/start the proxy for any new CRM user...

3.  I would like to run the proxy as a Windows Service by using NSSM  (https://nssm.cc/).    If I use the command line flags when nssm invokes "python emailproxy.py --no-gui and --local-server-auth"  will the whole process be transparent (require no human interaction)... if not what more do I need to do?

I am unclear how the underlying oauth2 process works... there are references in the documentation to pop-up web windows that require clicking... with the flags above I assume that is done transparently if need?

I am guessing/assuming the client authenticates using the ClientID/ClientSecret on behalf of the email account that is being proxied... unclear why you need to know the name of the email account if all the settings are the same... my CRM will have the email account/email password saved for each account that will send email...  any insight into how the process is working would be greatly appreciated

4.  Since I never intend to directly interact with the proxy is there are reason not to use the "requirements-no-gui" for the install?

Thanks in advance for your patience, insights, and answers

**Comment by sflamm** [comment]
`and it was only later on that the --no-gui and related options were added to support headless operation`

I assume by using --local-server-auth with --no-gui  what it is doing is essentially screen scraping (into the log file) from the html response  the URL that the user would normally click on manually and instead sending the http request (click) to that URL programmatically... which means that in this mode there should never be any need for user interaction.  Do I have that correct?

`for this reason that the proxy requires a separate configuration file entry for each account`

Probably I am not understanding OAuth well enough (new to me)...  my understanding is the  proxy application is being given the token on behalf of the end-user (receceived/held/used in the proxy).  Isnt the request for the token made off of the POP3 request to the proxy and therefore the proxy already knows which email account?  And the corresponding password for the user email account is being passed in the clear to the proxy... so on each request the proxy knows both email address and corresponding password - which it can use to obtain the token.   If all the other configuration properties are not unique to a given user (all from the same domain) - then why can you not wildcard the settings part for the domain and user the email/password being set to implicitly set up the user within the domain? 

Wouldn't this allow us to reach the goal of the 'headless' operation of the --no-gui and --local-server-auth and to automatically setup individual authorization on behalf of the user  only knowing the domain in advance and not any given individual email in the domain?

` However, it is important to note that this would either mean a) essentially zero security for account access; or, b) accounts would need to all use the same IMAP/POP password. `
yes this could be a concern - if that is a concern then you also need to use the certs to protect the traffic from the end-user to the proxy.   If you forgo one then you might as well forgo the other as the same weakness/vulnerability exists... correct?
My biggest concern for us - being able to continue to use applications that are critical to our business and cannot be easily upgraded to modern auth...

`  I'm happy to help with setup on a [consultancy basis](https://github.com/sponsors/simonrob?frequency=one-time&sponsor=simonrob)`

Definitely interested.   What is the best way to set this up?

**Comment by simonrob** [comment]
> I assume by using --local-server-auth with --no-gui what it is doing is essentially screen scraping and submitting the html response URL that the user would normally click on manually and instead sending the http request (click) to that URL programmatically... which means that in this mode there should never be any need for user interaction. Do I have that correct?

No: there is no screen-scraping involved here. With the `--local-server-auth` option the proxy acts as the recipient of the `redirect_uri` instruction. The actual OAuth consent process must involve the user granting this themselves, except in the client credentials grant flow.

> Probably I am not understanding OAuth well enough (new to me)... my understanding is the proxy application is being given the token on behalf of the end-user (receceived/held/used in the proxy). Isnt the request for the token made off of the POP3 request to the proxy and therefore the proxy already knows which email account? And the corresponding password for the user email account is being passed in the clear to the proxy... so on each request the proxy knows both email address and corresponding password - which it can use to obtain the token. If all the other configuration properties are not unique to a given user (all from the same domain) - then why can you not wildcard the settings part for the domain and use the email/password being sent to the proxy to implicitly set up/obtain the token for the user within the domain?

The proxy does indeed know the username and password – these allow it to look up configuration details. But the token is not the same for every account, so it needs to store these separately. It would certainly be possible to wildcard the shared details and then just store the token separately, but there hasn't until now been a demand for this feature.

> Wouldn't this allow us to reach the goal of 'headless' operation (using the --no-gui and --local-server-auth flags) and to automatically setup individual authorization on behalf of the user knowing only the the domain in advance (shared configuration for clientid/secret) without having to explicitly put entries for any given individual email in the domain into the config?

Yes – you can already achieve this with the proxy if you make it available publicly and set up the OAuth client accordingly; there's no requirement for it to be local-only. But you would need to carefully manage access.

**Comment by sflamm** [comment]
`No: there is no screen-scraping involved here. With the --local-server-auth option the proxy acts as the recipient of the redirect_uri instruction. The actual OAuth consent process must involve the user granting this themselves, except in the client credentials grant flow.`

How does the proxy work when the --no-gui flag is present ... it is not gathering consent from the user through the web form... where does the proxy get the consent from?   It sounds like to bootstrap the process we need to get consent ...

NOTE:  for my requirements - the end users are accounts in a Microsoft Dynamics CRM on-prem in which each user has their own email profile setup.  The email profile is what contains the users' email address/password and the protocol settings for POP/SMTP.   

When the CRM sends an email for them there cannot be any interaction between them and the proxy...  so how can we bootstrap the OAuth consent?    My goal would be to make this transparent - is that possible to achieve?  Or is the only way to achieve this to put it in Flow mode so that only the application authorization is needed and no consent from the user is needed...?    Other than the application sending the email for the end user (using the registered app permissions) - is there any downside to flow mode?

` It would certainly be possible to wildcard the shared details and then just store the token separately, but there hasn't until now been a demand for this feature.`

Understood.  However, in my scenario, user accounts are added to or removed from the CRM through its web interface.   The CRM and the OAuth proxy are remote.   Every time a user is added/removed from the CRM it is not feasible to remotely access the OAuth proxy, update the configuration file to add a new user record or remove a user record, and restart the OAuth proxy.   By having a syntax that just wildcards the domain - the OAuth proxy can create/manage its own user entry which stores/caches each user's own OAuth token without any outside configuration management.  Can you please add this capability?

`Yes – you can already achieve this with the proxy if you make it available publicly and set up the OAuth client accordingly; there's no requirement for it to be local-only. But you would need to carefully manage access.`

I am not understanding how to configure the OAuth proxy today without manually putting in a record for each user whose email is going to be proxied... looking at the code... you look up the user in the config file and if it is not found it is an error correct (this is not affected by flow mode which only affect permission)?  that implies the OAuth proxy is not automatically creating the individual user storage for the email/password/token unless there is a config entry... why does it need an explicit config entry to do so...  it knows the user wants the email to be proxied when it see the traffic... 

I hope I am providing better insight into what I am trying to achieve and why...  is there a way currently to configure the OAuth proxy to do so?  If not is it possible to make changes to allow this?
