### ISSUE TITLE
Authentication request failed or expired for account <email address> - aborting login

### ISSUE THREAD

**Issue by eljefe80** [simonrob/email-oauth2-proxy#79]
Hi, I have a pretty esoteric setup, so bear with me. My email provider has recently moved to using oauth2 only and my webmail pop3 client (zimbra) does not appear to support it. So, it looks like this project is a perfect fit. I want to deploy email-oauth2-proxy as a long-lived k8s pod, so I wrote up a quick deployment+ingress+service+configmap helm chart that forwards 1195,1193 to the pod directly and 80 and 443 via nginx-ingress+letsencrypt. This all works smooth as silk. I can telnet to 1195 and 1193 from outside of the cluster and can access 80 and 443 whenever the oauth2 triggers. I have registered an app with Azure and acquired a client_id and a 24month client_secret. My tenant is a large public academic institution and I'm not terribly familiar with Azure as a SaaS provider, so I'm sure that's where the breakdown is.

I have successfully gotten both IMAP and POP3 to trigger an oauth2 request and followed the authentication URL to validate, but that's where it fails. See the following log and configuration for details:

```
Initialising Email OAuth 2.0 Proxy from config file /opt/emailproxy.config
Starting IMAP server at 0.0.0.0:1993 (unsecured) proxying outlook.office365.com:993 (SSL/TLS)
Starting POP server at 0.0.0.0:1995 (unsecured) proxying outlook.office365.com:995 (SSL/TLS)
Starting SMTP server at 0.0.0.0:1587 (unsecured) proxying smtp.office365.com:587 (STARTTLS)
Initialised Email OAuth 2.0 Proxy - listening for authentication requests
New incoming connection to POP server at 0.0.0.0:1995 (unsecured) proxying outlook.office365.com:995 (SSL/TLS)
Accepting new connection to POP server at 0.0.0.0:1995 (unsecured) proxying outlook.office365.com:995 (SSL/TLS) via ('10.42.1.0', 21970)
POP (0.0.0.0:1995; 10.42.1.0:21970->outlook.office365.com:995) --> [ Client connected ]
POP (0.0.0.0:1995; 10.42.1.0:21970->outlook.office365.com:995) <-> [ Starting TLS handshake ]
POP (0.0.0.0:1995; 10.42.1.0:21970->outlook.office365.com:995) <-> [ TLS handshake complete ]
POP (0.0.0.0:1995; 10.42.1.0:21970->outlook.office365.com:995)     <-- b'+OK The Microsoft Exchange POP3 service is ready. [TQBXADMAUABSADAANgBDAEEAMAAwADAAOAAuAG4AYQBtAHAAcgBkADAANgAuAHAAcgBvAGQALgBvAHUAdABsAG8AbwBrAC4AYwBvAG0A]\r\n'
POP (0.0.0.0:1995; 10.42.1.0:21970->outlook.office365.com:995) <-- b'+OK The Microsoft Exchange POP3 service is ready. [TQBXADMAUABSADAANgBDAEEAMAAwADAAOAAuAG4AYQBtAHAAcgBkADAANgAuAHAAcgBvAGQALgBvAHUAdABsAG8AbwBrAC4AYwBvAG0A]\r\n'
POP (0.0.0.0:1995; 10.42.1.0:21970->outlook.office365.com:995) --> b'a1 login [[ Credentials removed from proxy log ]]\r\n'
POP (0.0.0.0:1995; 10.42.1.0:21970->outlook.office365.com:995)     --> b'a1 login <email address> <password>!\r\n'
POP (0.0.0.0:1995; 10.42.1.0:21970->outlook.office365.com:995)     <-- b'-ERR Protocol error. 19\r\n'
POP (0.0.0.0:1995; 10.42.1.0:21970->outlook.office365.com:995) <-- b'-ERR Protocol error. 19\r\n'
`POP (0.0.0.0:1995; 10.42.1.0:21970->outlook.office365.com:995) --> b'USER <email address>\r\n'
POP (0.0.0.0:1995; 10.42.1.0:21970->outlook.office365.com:995) <-- b'+OK\r\n'
POP (0.0.0.0:1995; 10.42.1.0:21970->outlook.office365.com:995)     <-- b'-ERR Connection is closed. 12\r\n'
POP (0.0.0.0:1995; 10.42.1.0:21970->outlook.office365.com:995) <-- b'-ERR Connection is closed. 12\r\n'
POP (0.0.0.0:1995; 10.42.1.0:21970->outlook.office365.com:995) <-- [ Server disconnected ]
New incoming connection to POP server at 0.0.0.0:1995 (unsecured) proxying outlook.office365.com:995 (SSL/TLS)
Accepting new connection to POP server at 0.0.0.0:1995 (unsecured) proxying outlook.office365.com:995 (SSL/TLS) via ('10.42.1.0', 40250)
POP (0.0.0.0:1995; 10.42.1.0:40250->outlook.office365.com:995) --> [ Client connected ]
POP (0.0.0.0:1995; 10.42.1.0:40250->outlook.office365.com:995) <-> [ Starting TLS handshake ]
POP (0.0.0.0:1995; 10.42.1.0:40250->outlook.office365.com:995) <-> [ TLS handshake complete ]
POP (0.0.0.0:1995; 10.42.1.0:40250->outlook.office365.com:995)     <-- b'+OK The Microsoft Exchange POP3 service is ready. [TQBXADQAUAAyADIAMABDAEEAMAAwADAANgAuAE4AQQBNAFAAMgAyADAALgBQAFIATwBEAC4ATwBVAFQATABPAE8ASwAuAEMATwBNAA==]\r\n'
POP (0.0.0.0:1995; 10.42.1.0:40250->outlook.office365.com:995) <-- b'+OK The Microsoft Exchange POP3 service is ready. [TQBXADQAUAAyADIAMABDAEEAMAAwADAANgAuAE4AQQBNAFAAMgAyADAALgBQAFIATwBEAC4ATwBVAFQATABPAE8ASwAuAEMATwBNAA==]\r\n'
POP (0.0.0.0:1995; 10.42.1.0:40250->outlook.office365.com:995) --> b'USER <email address>\r\n'
POP (0.0.0.0:1995; 10.42.1.0:40250->outlook.office365.com:995) <-- b'+OK\r\n'
POP (0.0.0.0:1995; 10.42.1.0:40250->outlook.office365.com:995) --> b'PASS [[ Credentials removed from proxy log ]]\r\n'
POP (0.0.0.0:1995; 10.42.1.0:40250->outlook.office365.com:995)     --> b'AUTH XOAUTH2\r\n'
POP (0.0.0.0:1995; 10.42.1.0:40250->outlook.office365.com:995)     <-- b'+ \r\n'
Authorisation request received for <email address> (local server auth mode)
Email OAuth 2.0 Proxy Local server auth mode: please authorise a request for account <email address>
Local server auth mode (0.0.0.0:80): starting server to listen for authentication response
Please visit the following URL to authenticate account <email address>: https://login.microsoftonline.com/<tenant_id>/oauth2/v2.0/authorize?client_id=REDACTED
Local server auth mode (0.0.0.0:80): received authentication response GET /?code=REDACTED HTTP/1.1 200 393
Local server auth mode (0.0.0.0:80): closing local server and returning response http://<MY PUBLIC DOMAIN>/?code=REDACTED
Authentication request failed or expired for account <- aborting login
POP (0.0.0.0:1995; 10.42.1.0:40250->outlook.office365.com:995) <-- b'-ERR Authentication failed. Email OAuth 2.0 Proxy: Login failed - the authentication request expired or was cancelled for account <email address>\r\n'
```

```ini
[IMAP-1993]
local_address = 0.0.0.0
server_address = outlook.office365.com
server_port = 993

[POP-1995]
local_address = 0.0.0.0
server_address = outlook.office365.com
server_port = 995

[SMTP-1587]
local_address = 0.0.0.0
server_address = smtp.office365.com
server_port = 587
starttls = True

[jeffrey.williams@alumni.ou.edu]
permission_url = https://login.microsoftonline.com/<tenant_id>/oauth2/v2.0/authorize
token_url = https://login.microsoftonline.com/<tenant_id>/oauth2/v2.0/token
oauth2_scope = https://outlook.office365.com/.default
redirect_uri = https://<MY PUBLIC DOMAIN>
redirect_listen_address = https://0.0.0.0:80
client_id = <client_id>
client_secret = <client_secret>
```

I've redacted tenant_ids, secrets, long urls, 

The one thing that I can't seem to figure out is why the returning response is via http:// instead of https://, but other than that it looks like it should be working?

Thanks!
Jeff

**Comment by simonrob** [comment]
The first error in the log is caused because you are connecting to a POP server with an IMAP client.

In the second part of the log it seems like you are successfully authenticating and authorising access, but the response is failing [at this point](https://github.com/simonrob/email-oauth2-proxy/blob/d2a9a0d9de659a0053554465e5666e45a07ec62a/emailproxy.py#L587) because you are using `https://`. The `--local-server-auth` mode is only meant for internal local connections, so only supports `http://`, which doesn't match your `redirect_uri` value. Issue #42 has more discussion of what sounds like a similar setup to yours – it's probably worth looking through the discussion there.

P.s: I took the liberty of formatting your comment a little so that the log and configuration file were more readable. Also - it's fine to delete the documentation from the configuration file as you have done, but it is unlikely to make any difference in terms of performance, and also contains useful explanations for things like the `http://` vs. `https://` aspect. If you do have a need to keep the file minimal you can remove everything except the actual server and account headings; the rest is for documentation and/or loaded from the default values at startup.

**Comment by eljefe80** [comment]
Hi!

Thank you! You pointed me in the right direction, turns out that if you do not have HTTPS='1' (or 'on', or 'yes') then https://github.com/simonrob/email-oauth2-proxy/blob/d2a9a0d9de659a0053554465e5666e45a07ec62a/emailproxy.py#L502 will return the request_uri with `http://` prepended instead of `https://`. Once I ran the script with HTTPS='1' in my environment, my configuration as set above worked.

Thanks,
Jeff

**Comment by Profex** [comment]
@eljefe80 I am facing a similar issue like you and would like to test if your solution helps for me as well. But not sure how you did resolve. How did you "run the script with HTTPS='1'", where did you set this?
