### ISSUE TITLE
Resource Owner Password Flow

### ISSUE THREAD

**Issue by sflamm** [simonrob/email-oauth2-proxy#81]
@simonrob @jryans 

Can the proxy implement the ROPC flow?

For a class of legacy applications (like CRMs) that already store user profiles (email address/password) and send email for their users  using basic auth SMTP/POP/IMAP the Resource Owner Password Flow is ideal.  There would very little to configure... 

The POP/IMAP requests contain the user email/password...  wouldn't this be a straightforward way to use OAuth POP/IMAP/SMTP?

![v2-oauth-ropc](https://user-images.githubusercontent.com/11237913/197361078-99262856-f459-48c0-934d-de185bfe8866.svg)

![AD ROPC](https://user-images.githubusercontent.com/11237913/197361196-276462f4-6924-4f31-9daa-bf38df6e88c9.jpg)

details here:

https://learn.microsoft.com/en-us/azure/active-directory/develop/v2-oauth-ropc

Please let me know if you can implement this in the proxy.

**Comment by sflamm** [comment]
https://learn.microsoft.com/en-us/azure/active-directory-b2c/add-ropc-policy?tabs=app-reg-ga&pivots=b2c-user-flow

**Comment by sflamm** [comment]
There is a sample python application using the MSAL library to obtain a token

https://github.com/Azure-Samples/ms-identity-python-desktop

**Comment by sflamm** [comment]
MSAL for Python supports ROPC flow:

https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/ffc659091de0192754bd05d379acb8d1b4056eb8/sample/username_password_sample.py

**Comment by sflamm** [comment]
https://msal-python.readthedocs.io/en/latest/

**Comment by sflamm** [comment]
There is apparently already a method in the Imap lib to take a token and only need to add such a method for POP support

![missing pop method](https://user-images.githubusercontent.com/11237913/197362443-fe13e487-298c-4838-a334-891007697951.jpg)

**Comment by simonrob** [comment]
I'm reluctant to add any additional dependencies to the proxy, particularly on libraries such as MSAL that only apply to O365. MSAL is not a requirement for this particular OAuth flow, however.

Regarding ROPC itself, it does seem like it could address the common desire for no user interaction at the same time as SMTP support. Please note, however, Microsoft has [clearly stated that they have no intention to remove basic auth for SMTP](https://learn.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/deprecation-of-basic-authentication-exchange-online#pop-imap-and-smtp-auth), so using the O365 server directly for SMTP and the client credentials grant flow for IMAP/POP seems to me to achieve the same outcome here?

**Comment by sflamm** [comment]
Understand the desire not to add a dependency on MSAL.  Your code already obtains the Token without it so it is not needed ...
The reason I mentioned it - it demonstrates MSFT is supporting the Resource Owner Password Flow (works)

With the functionality you already have - it would seem straight forward to implement the Resource Owner Password Flow and it would be extremely helpful to everyone (as you mention this common goal of many).   

Even thought MSFT claims it will not turn off basic auth on SMTP...  **it would be future proof us against any change of direction from them...  and it is a simpler setup to just configure our end applications (like CRMs) to just use an Email profile that sends all traffic through the proxy.**   It is also a very simple setup on the AD Application registration side...

Can you please add this?

**Comment by simonrob** [comment]
Ok – I can see why this might be useful. Adding the ROPC flow is not as straightforward as it first appears because it will require a new way to specify the flow type in an account configuration entry, which until now has not been required (and is not needed for any other provider). I want to be careful not to over-complicate the proxy, and am pretty over-committed right now, but will think about this in the longer term.

**Comment by sflamm** [comment]
understood.   Can I suggest you add a "proxy-mode" to the [Server setup]?   With the use of an  explicit mode fields use will be very easy to understand...   (even for the current flow support it would make things much clearer and avoid mistakes)

**Comment by sflamm** [comment]
> Even though MSFT claims it will not turn off basic auth on SMTP... **it would future proof us against any change of direction from them... and it is a simpler setup to just configure our end applications (like CRMs) to just use an Email profile that sends all traffic through the proxy.** It is also a very simple setup on the AD Application registration side...
> 
> Can you please add this?

This also eliminates the need to have a principal with permissions on any end user mailboxes... as the end-user is authenticating themselves
