### ISSUE TITLE
Case sensitive accountnames?

### ISSUE THREAD

**Issue by cobwash** [simonrob/email-oauth2-proxy#83]
Hi @simonrob 

Can the profiles please be non-case sensitive?

2022-10-25 00:28:44,411: IMAP (localhost:1993; 127.0.0.1:50929->outlook.office365.com:993) <-- b'DJV1 NO AUTHENTICATE Email OAuth 2.0 Proxy: No config file entry found for account nextavailabledcc@[domain removed] - please add a new section with values for permission_url, token_url, oauth2_scope, redirect_uri, client_id and client_secret\r\n'

Line 19436: 2022-10-25 00:29:17,837: IMAP (localhost:1993; 127.0.0.1:51164->outlook.office365.com:993; NextAvailableDCC@[domain removed])     <-- b'a1 OK AUTHENTICATE completed.\r\n'

??

**Comment by simonrob** [comment]
I considered this when first implementing the proxy, but decided against it. Domain names are [not case-sensitive](https://betterfc.org/rfc1035.html#_name_space_definitions), but the actual username [could potentially be case-sensitive](https://www.rfc-editor.org/rfc/rfc5321#section-2.3.11). I'm not aware of any OAuth 2.0 capable email provider that does actually have case-sensitive usernames, but thought it wasn't worth the risk.

Is there a particular use-case or need for this that means you can't use the same case in both the configuration file and client setup?

**Comment by cobwash** [comment]
It was more a case of someone when creating an account name put capitals but when it was loaded into the program we have that uses IMAP it was set up without. I grabbed the account info from LDAP when creating the script and ended up with a few accounts that didn't work due to prob's with case sensitivity. 

Like you say, I'm also not aware of any providers that are case sensitive that support OAuth but not basic auth so wondered if it might have just been oversight. Since its by design rather than bug I wont push you to change it (and feel free to close this case if after seeing my reasoning you still don't want to change case sensitivity).

while I'm here is there any log rotation options? I ended up with a 160mb log file overnight (the app we use is really really chatty for some reason) while I had debug logging enabled to make sure everything was working.  much more manageable with it turned off, but while we wait for the dev's of said software to introduce a proper fix for OAuth I'll need to keep your wonderful little program running and I don't really want to have to manually shut it down every week if I can avoid it.

Thanks for your understanding, I was just curious. If I knew python at all I'd do it myself and create a pull request but I can read code, just not create it myself.

**Comment by simonrob** [comment]
Thanks for posting the other issue. I'll close this one, but feel free to reopen with any updates about the need for case-insensitive usernames in future.

**Comment by ahochsteger** [comment]
@simonrob we have the same issue, that account names seem to have been handled case-insensitive in the past where we run into issues when using this proxy.
It would be really great if you could add an option to enable the case-insensitive behavior.

**Comment by simonrob** [comment]
The proxy has never supported case-insensitive account names. By "in the past" do you mean something in your own setup? For now you could update the proxy's configuration file to match what is used in your client(s) if that is easier.

Adding support for this is not quite as simple as it might first appear, and definitely not just a quick edit to scatter `lower()` everywhere because of the various proxy features that build on basic accounts (such as catch-all matching) and the need for backwards compatibility. In the short term you could of course fork the project to add support tailored to your situation, however.

I'm happy to look at adding this feature to the proxy on a [consultancy basis](https://github.com/sponsors/simonrob?frequency=one-time) if it needs prioritising.
