### ISSUE TITLE
Task bar icon is missing, also no menu

### ISSUE THREAD

**Issue by adamestein** [simonrob/email-oauth2-proxy#86]
Using:
  o email-oauth2-proxy-2022-10-24
  o Fedora 34
  o Python 3.9.13
  o KDE 5.24.4

Created a virtual env and installed all required packages (pip install -r requirements.txt). When I run the script, the task bar icon doesn't show. If I put my mouse over the blank spot, the string "Email OAuth 2.0 Proxy" will popup. Clicking left or right mouse button doesn't bring up a menu or display anything else.

Set up fetchmail to call email-oauth2-proxy at which point I see the log message "Please authorise your account ... from the menu". No icon, no menu, no way to get a menu from the blank icon.

If there is anything you would like to try or information needed, let me know. Was hoping to be able to fetch my MS Outlook email again since MS has now turned of Basic Auth and fetchmail 6.x doesn't work with oauth2 yet.

**Comment by adamestein** [comment]
In case anybody else is having this problem, I did figure it out. Turns out, you need to install pygobject (pip install pygobject) and the icon and menu are now visible. Not sure if other platforms need this, so not sure the proper way to include this in requirements.txt.

**Comment by simonrob** [comment]
Thanks for following up with the solution you found.

The [pystray FAQ](https://pystray.readthedocs.io/en/latest/faq.html) covers this situation – when using that module in a virtualenv on Linux there are additional dependencies. I'll add a link to this in the proxy's readme.
