### ISSUE TITLE
SMTP Protocol Error

### ISSUE THREAD

**Issue by andre13794** [simonrob/email-oauth2-proxy#90]
Hello guys,

we are using the proxy for IMAP to get messages from the mailbox, which is working fine.
Now we are trying to send mails using smtp und we get a smtp protocal error.

Nov  2 10:51:32 shdeaahrocop01 Email OAuth 2.0 Proxy: New incoming connection to SMTP server at 192.168.16.8:1587 (unsecured) proxying smtp.office365.com:587 (SSL/TLS)
Nov  2 10:51:32 shdeaahrocop01 Email OAuth 2.0 Proxy: Accepting new connection to SMTP server at 192.168.16.8:1587 (unsecured) proxying smtp.office365.com:587 (SSL/TLS) via ('192.168.14.75', 41770)
Nov  2 10:51:32 shdeaahrocop01 Email OAuth 2.0 Proxy: SMTP (192.168.16.8:1587; 192.168.14.75:41770->smtp.office365.com:587) --> [ Client connected ]
Nov  2 10:51:32 shdeaahrocop01 Email OAuth 2.0 Proxy: SMTP (192.168.16.8:1587; 192.168.14.75:41770->smtp.office365.com:587) <-> [ Starting TLS handshake ]
Nov  2 10:51:32 shdeaahrocop01 Email OAuth 2.0 Proxy: Caught connection error in SMTP (192.168.16.8:1587; 192.168.14.75:41770->smtp.office365.com:587) - you have set `local_certificate_path` and `local_key_path`; is your client using a secure connection? Error type <class 'ssl.SSLErro>

All settings I can see are right.
The connection between the sending client and the proxy is without tls or ssl. It seems like the error is while connecting to m365,

Do you have any idea or am I missing something?

For better understanding:
Client: 192.168.14.75
oAuth Proxy: 192.168.16.8

The account settings are working fine for imap.

Kind regard
André

**Comment by simonrob** [comment]
The error message explains the issue: _"you have set `local_certificate_path` and `local_key_path`; is your client using a secure connection?"_

If you set these parameters in the configuration file then you must configure your client to use a secure connection, and (if applicable) make sure it supports self-signed certificates. Please check your client's setup.

**Comment by andre13794** [comment]
I just needed to double check.
My configuration does not have those parameters set:

```
[Email OAuth 2.0 Proxy configuration file]
[Server setup]
[SMTP-1587]
local_address = 192.168.16.8
server_address = smtp.office365.com
server_port = 587

[Account setup]
[mail@domain.com]
permission_url = https://login.microsoftonline.com/TENANT/oauth2/v2.0/authorize
token_url = https://login.microsoftonline.com/TENANT/oauth2/v2.0/token
oauth2_scope = https://outlook.office365.com/IMAP.AccessAsUser.All https://outlook.office365.com/POP.AccessAsUser.All https://outlook.office365.com/SMTP.Send offline_access
redirect_uri = http://localhost
client_id = CLIENTID
client_secret = SECRET

[emailproxy]
delete_account_token_on_password_error = True
encrypt_client_secret_on_first_use = False
allow_catch_all_accounts = False
```

**Comment by simonrob** [comment]
In this case, there is probably an issue with your Python installation's SSL configuration. You've cut off part of the error message here - it should read _"[...] Error type <class 'ssl.SSLError'> with message: [...]"_. What is the message that is given?

You might find that installing [certifi](https://pypi.org/project/certifi/) fixes the problem.

(You can also remove the first two lines and `[Account setup]` from the configuration file if needed)

**Comment by simonrob** [comment]
To follow up, e98e4f2 clarifies the error message here, only showing the part about local certificates when it actually applies.

**Comment by andre13794** [comment]
I just went from scratch to eliminate any possbile error.
Just installed Linux, installed pip, installed gir1.2-ayatanaappindicator3-0.1, changed the config and the error seems to be the same - IMAP still works fine.

The missing part for the error is:
secure connection? Error type <class 'ssl.SSLError'> with message: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:997)

**Comment by simonrob** [comment]
Ah – you've removed the STARTTLS setting from the example configuration file for some reason. The proxy used to detect this, but it is more complex now with the added support for various SSL configurations. I'll think about how this could be achieved again.

Office 365's SMTP server uses STARTTLS, and because the proxy needs to intercept the connection, it has to handle this on your behalf (see the readme). Re-adding `starttls = True` will fix this:

```
[SMTP-1587]
local_address = 192.168.16.8
server_address = smtp.office365.com
server_port = 587
starttls = True
```

**Comment by andre13794** [comment]
Thanks. Did the trick.
I thought this parameter was set so that the client needs to use starttls to connect to the oAuth Proxy.
