### ISSUE TITLE
Need Help:   CA Signed Certificate for Localhost

### ISSUE THREAD

**Issue by sflamm** [simonrob/email-oauth2-proxy#92]
@simonrob 

Need to configure the inbound connection to the emailproxy to use SSL - the connections are coming from my CRM that is co-located on LOCALHOST...    

Updated my configuration file to read the certificate:

_[POP-1995]
server_address = outlook.office365.com
server_port = 995
local_certificate_path = localhost.pem
local_key_path = localhost.key

[SMTP-1587]
server_address = smtp.office365.com
server_port = 587
starttls = True
local_certificate_path = localhost.pem
local_key_path = localhost.key_

Generated a local CA and installed it into the Trusted Certificate Authority on the server (Windows).
Also generated the signed certificate for LOCALHOST to be used by the email proxy:

_// private key for CA
openssl genrsa -des3 -out localhostCA.key 2048
// generate root (CA) certificate 
openssl req -x509 -new -nodes -key localhostCA.key -sha256 -days 3650 -out localhostCA.pem
// private key for localhost 
openssl genrsa -out localhost.key 2048
// create CSR for localhost
openssl req -new -key localhost.key -out localhost.csr
// create  X509 V3 certificate extension config file

localhost.ext (text file)

	authorityKeyIdentifier=keyid,issuer
	basicConstraints=CA:FALSE
	keyUsage = digitalSignature, nonRepudiation, keyEncipherment, dataEncipherment
	subjectAltName = @alt_names

	[alt_names]
	DNS.1 = localhost

// sign localhost certificate with CA
openssl x509 -req -in localhost.csr -CA localhostCA.pem -CAkey localhostCA.key -CAcreateserial -out localhost.crt -days 3650 -sha256 -extfile localhost.ext
// view certificate
openssl x509 -text -noout -in localhost.crt_

Everything looks fine... but when running the emailproxy I receive the following error  (Thunderbird is the test email client co-located on the same machine as the emailproxy - later the CRM will be the client ):

_2022-11-03 02:46:08: Initialising Email OAuth 2.0 Proxy from config file C:\Users\sflamm\Desktop\Email Proxy\ROPC Flow\compiled application\emailproxy.config
2022-11-03 02:46:08: Starting IMAP server at localhost:1993 (TLS) proxying outlook.office365.com:993 (SSL/TLS)
2022-11-03 02:46:08: Starting POP server at localhost:1995 (TLS) proxying outlook.office365.com:995 (SSL/TLS)
2022-11-03 02:46:08: Starting SMTP server at localhost:1587 (TLS) proxying smtp.office365.com:587 (STARTTLS)
2022-11-03 02:46:08: Initialised Email OAuth 2.0 Proxy - listening for authentication requests. Connect your email client to begin
*2022-11-03 02:46:13: POP (localhost:1995) Caught asyncore info message (client) - error : uncaptured python exception, closing channel <__main__.POPOAuth2ClientConnection connected 127.0.0.1:12470 at 0x17f52b49600> (<class 'ssl.SSLError'>:[SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:997) [asyncore.py|read|90] [C:\Python310\email-oauth2-proxy-ropcg\emailproxy.py|handle_read_event|781] [C:\Python310\email-oauth2-proxy-ropcg\emailproxy.py|ssl_handshake|768] [ssl.py|do_handshake|1342])**
2022-11-03 02:46:22: Stopping Email OAuth 2.0 Proxy
2022-11-03 02:46:22: Stopping IMAP server at localhost:1993 (TLS) proxying outlook.office365.com:993 (SSL/TLS)
2022-11-03 02:46:22: Stopping POP server at localhost:1995 (TLS) proxying outlook.office365.com:995 (SSL/TLS)
2022-11-03 02:46:22: Stopping SMTP server at localhost:1587 (TLS) proxying smtp.office365.com:587 (STARTTLS)_  

Not sure why it believes the CA is unknown... the certificate is signed by the local CA and the local CA is installed a trusted root CA

![root CA installed](https://user-images.githubusercontent.com/11237913/199813597-fb0329ad-09ea-49fb-8368-f1c68b044c03.jpg)

Thanks in advance for your help.

**Comment by simonrob** [comment]
This is not something the proxy is directly in control of – ultimately your client needs to trust the certificate that is presented. I may be wrong, but from a quick look at the series of commands you're using, it doesn't look like you're actually linking the CA and certificate?

Rather than handling this yourself, for local certificates I'd recommend using [mkcert](https://github.com/FiloSottile/mkcert), which makes this process much simpler and less error-prone.

**Comment by sflamm** [comment]
This command signs the localhost certificate with the CA certificate (links):

// sign localhost certificate with CA
openssl x509 -req -in localhost.csr -CA localhostCA.pem -CAkey localhostCA.key -CAcreateserial -out localhost.crt -days 3650 -sha256 -extfile localhost.ext


I realize that the error seems to be generated from the client... (Thunderbird in this case).   I would expect Thunderbird to pick up the CA from the local certificate store...    Trying to understand why this is happening.

I can take a look at mkcert as well...

**Comment by sflamm** [comment]
I've changed the certificate for the emailproxy to contain a full chain by concatenating with the CA certificate:

copy /b localhost.crt+localhostCA.pem localhost.pem

the error message from Thunderbird is:

![thunderbird-unverified-CA](https://user-images.githubusercontent.com/11237913/199861625-8a98f848-af5e-4e06-9b8d-3db473d44811.jpg)

I have not installed the CA cert into thunderbird's repository... that would likely fix it... but I was hoping to somehow get Thunderbird to trust it since it is in the Microsoft Certifcate Manager locally...    Any ideas if that is possible?

mkcert - would likely install it into the thunderbird repository too... 

Thoughts?

**Comment by simonrob** [comment]
Ah, I didn't realise this was Thunderbird (you initially mentioned a CRM). Thunderbird won't accept any self-signed certificates unless you add an exception as shown in your screenshot. Is your CRM any more flexible here?

If not, the only way around this is to host the proxy on an real domain that you can get a certificate for. Let's Encrypt will be useful here, but there really is nothing the proxy can do I'm afraid.

**Comment by sflamm** [comment]
Sorry about the confusion... I had buried that in my comment above:

"Everything looks fine... but when running the emailproxy I receive the following error (Thunderbird is the test email client co-located on the same machine as the emailproxy - later the CRM will be the client )"

I was trying to test it out as much as possible independent of the CRM to make the CRM transition seamless.   I do believe the CRM is likely to work with the self generated root CA  and the client certificate with the full-chain since it is a Microsoft product and is integrated into the Microsoft Cert Manager for IIS that the CRM depends on... 

In any case - I managed through some powershell magic and the use of the both the Microsoft  XRM tooling and Microsoft.Crm.PowerShell Module to turn off the CRM email profile requirement for 1) POP3/IMAP to be only over SSL 2)  basic auth only over SSL (two separate settings).    Now the On-prem Dynamics CRM is able to chat in the clear to the emailproxy which is co-located on the same server.   It appears to be working... will be testing over the next few days for reliability... and provide an update.

I may still configure it to use SSL for the emailproxy connection but right now it does not seem to be an absolute requirement anymore.

**Comment by simonrob** [comment]
Thanks for following up - glad this was able to be resolved.

**Comment by RuslanMaximum** [comment]
> In any case - I managed through some powershell magic and the use of the both the Microsoft XRM tooling and Microsoft.Crm.PowerShell Module to turn off the CRM email profile requirement for 1) POP3/IMAP to be only over SSL 2) basic auth only over SSL (two separate settings). Now the On-prem Dynamics CRM is able to chat in the clear to the emailproxy which is co-located on the same server. It appears to be working... will be testing over the next few days for reliability... and provide an update.

Good day. We faced the same issue, could you explain in more detail about powershell magic was used and which xrm tool  was used in the toolbox? Sorry for disturbing.
