### ISSUE TITLE
oauth token issue

### ISSUE THREAD

**Issue by VenceFu** [simonrob/email-oauth2-proxy#97]
Hi ,

I'm using Microsoft o365  POP & SMTP  service ,  I found issue at 10 Nov , i do not change any settings and config file before this day (The system was working fine until then), 
program show " Authorisation request received for [my email address] (interactive mode)" , and system is hold.

So i into debug mode and see detail message , i tried to remove all settings and re-auth with "--local-server-auth" . 
First i using POP try to connect ,  system will show "Please visit the following URL to authenticate account " , and i send token to redirect_uri ,  i can see " Successfully authenticated POP connection"  mesage  and this token can run with POP auto update , 

In this time , i check the "emailproxy.config" , i can see token is write to config file. 

But if i send mail (SMTP) , system show " Retrying login due to exception while requesting OAuth 2.0 credentials: InvalidToken()" 
and told me should re-run the auth process : " Authorisation request received for [my email address] (local server auth mode)" 

Now i check "emailproxy.config" again , token message are empty . 
if i finished to re-run auth , POP will broken and system log : 

[ Successfully authenticated SMTP connection - removing proxy ]
Retrying login due to exception while requesting OAuth 2.0 credentials: InvalidToken()
Authorisation request received for  (local server auth mode)
Email OAuth 2.0 Proxy Local server auth mode: please authorise a request for account 
Local server auth mode (localhost:8080): unable to start local server. Please check that the redirect_uri for account  is unique across accounts, specifies a port number, and is not already in use. See the documentation in the proxy's configuration file for further detail

that step will loop .

My friend have same environment, his python are running normally, of course I refer to his settings, but issue will happened at my environment. 

So i re-install the new VM , build same environment with my friend , running his configuration , issue will happened  again.... 
I think that issue maybe some compatibility issue between the program and Microsoft Azure API, 

Can you help us to check it ?

**Comment by simonrob** [comment]
There are lots of different things happening here, and I'm not sure I follow completely what you're describing, but if POP works fine and SMTP does not I'd assume either:

- SMTP auth is disabled for your O365 account/tenant (see [Microsoft's documentation](https://learn.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/authenticated-client-smtp-submission)); or,
- You've entered different passwords for POP and SMTP. Set `delete_account_token_on_password_error = False` to help isolate this if needed (see the [example configuration file](https://github.com/simonrob/email-oauth2-proxy/blob/main/emailproxy.config)).

There should be no difference between interactive mode and `--local-server-auth` with respect to the errors you are seeing here, and similar for a new environment.

If it really is the case that importing a working configuration (i.e., both the proxy script and configuration file) and attempting to log in with your friend's account produces the same error for their configuration that does not appear when tried on their own setup then I'll need more detail to trace the issue.

**Comment by VenceFu** [comment]
Hi , 

I following  [example configuration file](https://github.com/simonrob/email-oauth2-proxy/blob/main/emailproxy.config)
and add config to bottom :
[emailproxy]
delete_account_token_on_password_error = False 
encrypt_client_secret_on_first_use = False
allow_catch_all_accounts = False

so if token auth fail , default action will delete it .

Finally found the cause of the problem ,  i check newer Azure API ,  if the service is different than token cannot be shared. SMTP and POP will requires separate tokens. 
(Old token can be share to use . that is so why my friend can working normally. )

So i split the SMTP config and port to copied service , change code with  : 
APP_NAME = 'SMTP OAuth 2.0 Proxy'
APP_SHORT_NAME = 'smtpproxy'
APP_PACKAGE = 'ac.robinson.SMTP-oauth2-proxy'

Because the smtpproxy.config are different file, they can be written as different tokens, 
and copy /etc/systemd/system/emailproxy.service to smtpproxy.service , change python path , that is work !!

Thanks you very much for your help .

**Comment by simonrob** [comment]
I'm not aware of an Azure requirement for different clients or tokens between POP and SMTP, but will monitor going forward because as you've pointed out the proxy doesn't currently support more than one per account. Thanks for following up with the solution you found – I really appreciate this.
